### PR TITLE
don't abspath in EnvVar

### PR DESCRIPTION
**Pull request by scopatz**
This is a hotfix for not expanding relative paths in EnvVar, as reported in #1214.  @melund, would you mind trying this out and merging it :) It seems to work on my machine.  Sorry again about merging the other one. I had no idea Windows had that behaviour. Mea culpa

### CODE REVIEW

**Comment by melund** [comment]
@scopatz I get this error. If you think it is unrealated. Then I am happy to merge. We really need this in. I think it could also be causing the slowdown #1268. Since xonsh now considers all files executable, it looks through all files on the PATH on every command.

**Comment by melund** [comment]
```
snail@sea ~\Documents\xonsh nabs $ ls                                                                                                                                            {dev_info}
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "C:\Users\mel\Documents\xonsh\xonsh\ptk\shell.py", line 100, in push
    locs=None)
  File "C:\Users\mel\Documents\xonsh\xonsh\__amalgam__.py", line 16083, in compile
  File "C:\Users\mel\Anaconda3\envs\x\lib\inspect.py", line 1464, in stack
    return getouterframes(sys._getframe(1), context)
  File "C:\Users\mel\Anaconda3\envs\x\lib\inspect.py", line 1441, in getouterframes
    frameinfo = (frame,) + getframeinfo(frame, context)
  File "C:\Users\mel\Anaconda3\envs\x\lib\inspect.py", line 1414, in getframeinfo
    lines, lnum = findsource(frame)
  File "C:\Users\mel\Anaconda3\envs\x\lib\inspect.py", line 758, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "C:\Users\mel\Anaconda3\envs\x\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "C:\Users\mel\Anaconda3\envs\x\lib\linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "C:\Users\mel\Anaconda3\envs\x\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 482: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\envs\x\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\mel\Anaconda3\envs\x\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mel\Documents\xonsh\xonsh\main.py", line 269, in <module>
    main()
  File "C:\Users\mel\Documents\xonsh\xonsh\main.py", line 245, in main
    shell.cmdloop()
  File "C:\Users\mel\Documents\xonsh\xonsh\ptk\shell.py", line 120, in cmdloop
    self.default(line)
  File "C:\Users\mel\Documents\xonsh\xonsh\__amalgam__.py", line 13192, in default
  File "C:\Users\mel\Documents\xonsh\xonsh\ptk\shell.py", line 104, in push
    print_exception()
  File "C:\Users\mel\Documents\xonsh\xonsh\__amalgam__.py", line 5892, in print_exception
  File "C:\Users\mel\Anaconda3\envs\x\lib\traceback.py", line 159, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "C:\Users\mel\Anaconda3\envs\x\lib\traceback.py", line 100, in print_exception
    type(value), value, tb, limit=limit).format(chain=chain):
  File "C:\Users\mel\Anaconda3\envs\x\lib\traceback.py", line 474, in __init__
    capture_locals=capture_locals)
  File "C:\Users\mel\Anaconda3\envs\x\lib\traceback.py", line 358, in extract
    f.line
  File "C:\Users\mel\Anaconda3\envs\x\lib\traceback.py", line 282, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "C:\Users\mel\Anaconda3\envs\x\lib\linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "C:\Users\mel\Anaconda3\envs\x\lib\linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "C:\Users\mel\Anaconda3\envs\x\lib\linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "C:\Users\mel\Anaconda3\envs\x\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 482: invalid start byte
```

**Comment by scopatz** [comment]
@melund, do you see this error if you start xonsh with with XONSH_DEBUG=1?

**Comment by scopatz** [comment]
Also what are your `$XONSH_ENCODING` and `$XONSH_ENCODING_ERRORS` set to?  I actually think this is an unrelated issue cause by the amalgamation.

**Comment by melund** [comment]
I saw it both with and without debug. 
```
snail@sea ~\Documents\xonsh $ $XONSH_ENCODING_ERRORS  
'surrogateescape'
snail@sea ~\Documents\xonsh $ $XONSH_ENCODING 
'utf-8'
```

**Comment by melund** [comment]
Ohh. They may not have had those values before I merged.

**Pull request merged**
