### PR TITLE
repr() all attributes in CommandPipeline.__repr__

### LINKED ISSUE #3938: Attributes in CommandPipeline.__repr__ are str() instead of repr()
## xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.9.24          |
| Python           | 3.9.0           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 3.0.5           |
| shell type       | prompt_toolkit  |
| pygments         | 2.6.1           |
| on posix         | True            |
| on linux         | True            |
| distro           | fedora          |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | False           |
| jupyter kernel   | None            |
+------------------+-----------------+

```

</details>

## Expected Behavior

When I do `!(echo hello)`, I expect all attributes in the returned CommandPipeline repr string to be repr instead of str.

## Current Behavior

```
$ !(echo hello)                                                                                                     
CommandPipeline(stdin=<_io.BytesIO object at 0x7fc900c645e0>, stdout=<_io.BytesIO object at 0x7fc900c64310>, stderr=<_io.BytesIO object at 0x7fc900c64360>, pid=5286, returncode=0, args=['echo', 'hello'], alias=None, stdin_redirect=['<stdin>', 'r'], stdout_redirect=[9, 'wb'], stderr_redirect=[12, 'w'], timestamps=[1603982511.7501793, 1603982511.7609427], executed_cmd=['echo', 'hello'], input=, output=hello
, errors=None)
```

Note the newline printed in the middle of that object, because `output` is not a repr-escaped string.

## Steps to Reproduce

See above

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

---

I'll have a PR really soon. This should be super easy to fix.

### PR DESCRIPTION
**Pull request by carmenbianca**
Fixes #3938. Super simple fix. Currently on a super slow machine, so waiting to see if any tests break on CI because of this.

### CODE REVIEW

**Comment by scopatz** [comment]
This is a long overdue change! Thanks @carmenbianca!

**Comment by anki-code** [comment]
What if format the output like this?
```
!(ls)
CommandPipeline(
    stdin=<_io.BytesIO object at 0x7f2e5f4fd7c0>, 
    stdout=<_io.BytesIO object at 0x7f2e5f4fd720>, 
    stderr=<_io.BytesIO object at 0x7f2e5f4fd9f0>, 
    pid=75152, 
    returncode=0, 
    args=['ls'], 
    alias=['ls', '--color=auto', '-v', '--group-directories-first', '-A'], 
    stdin_redirect=['<stdin>', 'r'], 
    stdout_redirect=[7, 'wb'], 
    stderr_redirect=[9, 'w'], 
    timestamps=[1603984877.781368, 1603984877.7937686], 
    executed_cmd=['ls', '--color=auto', '-v', '--group-directories-first', '-A'], 
    input='', 
    output='.idea\n123\n', 
    errors=None)

```

**Comment by scopatz** [comment]
Yeah, that is more readable @anki-code, but probably a separate PR.

**Comment by anki-code** [comment]
May be just to avoid time on merging conflict do it here? The change is simple:
```
    def __repr__(self):
        s = self.__class__.__name__ + "(\n  "
        s += ",\n  ".join(a + "=" + repr(getattr(self, a)) for a in self.attrnames)
        s += ")"
        return s
```
Looks like:
Screenshot_20201029_183701

I can create separate PR also.

**Comment by carmenbianca** [comment]
I'm good either way. Considering maintainers have write access to this PR, feel free to make the necessary changes to this PR :)

**Comment by anki-code** [comment]
Hah, I'm not the maintainer :) I'm only learn :) Okay, I'll create a PR after your changes will be mergedto avoid conflicts.

**Comment by scopatz** [comment]
Thanks @carmenbianca!

**Pull request merged**
