### PR TITLE
feat: support var-args signature for aliases

### PR DESCRIPTION
**Pull request by jnoortheen**
it fixes following scenarios

problem-signature

even though they are the same objects, different signature returned when referenced from aliases dict.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Review by daniel-shimon — CHANGES_REQUESTED** [review]
Looks good! Can you add tests for this scenario?

**Comment by jnoortheen** [comment]
@daniel-shimon try checking now.

**Comment by daniel-shimon** [comment]
Hey @jnoortheen, listen it's a bit difficult when you do these non-related changes like you did here by removing the `xonsh_execer` fixture from other tests.

It is just inserted into some non related commit without any explanation or reasoning and makes the CR process longer.
For instance now I need to go to those fixture and tests and make sure that it makes sense and doesn't break anything else instead of just approving and merging the PR.

I would very much prefer you do these changes in separate PRs so we can have faster and easier CR processes in the project.

**Comment by jnoortheen** [comment]
@daniel-shimon it was just I first tried to add the test and some fixtures in the test_aliases.py. Later moved them to pipelines test. I've created a separate PR.

**Review by daniel-shimon — APPROVED** [review]
Great! Thanks!

**Pull request merged**
