### PR TITLE
feat: some python libraries depend on isatty to check for terminal ca…

### PR DESCRIPTION
**Pull request by jnoortheen**
…pabilities

related to #4008

### CODE REVIEW

**Comment by jnoortheen** [comment]
image

the same seems to be the case for alias functions as well. That too has a custom std wrapper. There are two things, handle and default while default seems to be returning correct isatty result.

**Comment by jnoortheen** [comment]
I don't know the implementation detail. So please review this more carefully eventhough it is a small change.

**Comment by jnoortheen** [comment]
@gforsyth could you check this?

**Comment by gforsyth** [comment]
Thanks @jnoortheen !  I think this is a reasonable change, but if other things break, we should revisit

**Comment by jnoortheen** [comment]
Yes sure

**Pull request merged**
