### PR TITLE
Vend ptk

### PR DESCRIPTION
**Pull request by melund**
This adds a builtin version of PTK to xonsh. As discussed in https://github.com/xonsh/xonsh/issues/3622#issuecomment-668400321

It is used as fall back if prompt_toolkit is not available or too old.

### CODE REVIEW

**Comment by melund** [comment]
Ok. Error seems to be `Errors seems to be the annoying: AttributeError: module 'builtins' has no attribute '__xonsh__'`. I will try to restart the tests and see if we can get it all green. Super annoying.

**Comment by scopatz** [comment]
This looks great @melund! I am OK with merging this if you are

**Comment by melund** [comment]
I am good with it.

**Comment by melund** [comment]
Strike that. Can you wait a bit. I think I forgot the only hard dependency of ptk. So I need to add the "wcwidth" as well.

**Comment by melund** [comment]
@scopatz Problem fixed. Now we also vend the small "wcwidth" library which is only hard dependency of PTK.

**Comment by scopatz** [comment]
Thanks a ton @melund!

**Comment by laloch** [comment]
Does this really work for you?
Running `xonsh-in-docker.py` yields:
```
$ ./xonsh-in-docker.py --python 3.8 PYTHONOLDPARSER=0 XONSH_DEBUG=1 XONSH_SHOW_TRACEBACK=True
Building and running Xonsh
Using python  3.8
Using prompt-toolkit  2.0.4
[...lots of docker setup omitted...]
/usr/local/lib/python3.8/site-packages/xonsh/shell.py:166: UserWarning: Installed prompt-toolkit version < v2.0.0 is not supported. Falling back to the builtin prompt-toolkit.
  warnings.warn(
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/xonsh/main.py", line 423, in main
    args = premain(argv)
  File "/usr/local/lib/python3.8/site-packages/xonsh/main.py", line 359, in premain
    env = start_services(shell_kwargs, args)
  File "/usr/local/lib/python3.8/site-packages/xonsh/main.py", line 308, in start_services
    builtins.__xonsh__.shell = Shell(execer=execer, **shell_kwargs)
  File "/usr/local/lib/python3.8/site-packages/xonsh/shell.py", line 212, in __init__
    from xonsh.ptk_shell.shell import PromptToolkitShell as shell_class
  File "/usr/local/lib/python3.8/site-packages/xonsh/ptk_shell/shell.py", line 16, in <module>
    from xonsh.ptk_shell.history import PromptToolkitHistory, _cust_history_matches
  File "/usr/local/lib/python3.8/site-packages/xonsh/ptk_shell/history.py", line 5, in <module>
    import prompt_toolkit.history
  File "/usr/local/lib/python3.8/site-packages/xonsh/vended_ptk/prompt_toolkit/__init__.py", line 16, in <module>
    from .application import Application
ModuleNotFoundError: No module named 'prompt_toolkit.application'
Xonsh encountered an issue during launch
Failback to /bin/sh
```

**Comment by melund** [comment]
That is weird. Does the docker image have an old version of prompt toolkit installed?

**Comment by laloch** [comment]
Nope. It's being installed in the setup process:
```
...
Sending build context to Docker daemon  74.28MB
Step 1/6 : from python:3.8
 ---> 4f7cd4269fa9
Step 2/6 : RUN pip install --upgrade pip && pip install   prompt-toolkit==2.0.4   pygments
 ---> Using cache
 ---> 2c1b5c08a2b2
Step 3/6 : RUN mkdir /xonsh
 ---> Using cache
 ---> 96e8ca86249f
Step 4/6 : WORKDIR /xonsh
 ---> Using cache
 ---> 3bd2204cadef
Step 5/6 : ADD ./ ./
 ---> Using cache
 ---> a2fe7235690d
Step 6/6 : RUN python setup.py install
 ---> Using cache
 ---> f1dad544ca00
...
```

**Comment by melund** [comment]
Ok. But your traceback shows the warning about the version beeing to old. So why does prompt-kit fail the version test here: 
https://github.com/xonsh/xonsh/blob/master/xonsh/shell.py#L165

I think failure comes from having two versions of prompt-toolkit on path...

**Comment by laloch** [comment]
`xonsh-in-docker.py` is outdated and installs by default `prompt-toolkit==2.0.4` - **2**.0.4.
My point is, that the mechanism, that should make sure we're not using an old PTK version does itself make us fail to start completely.

**Comment by melund** [comment]
Why isn't __amalgam__.py not always regenerated when running pip installl (arrgh....)

**Comment by melund** [comment]
It is beeing regerenated... But it doesn't have the newest code from source

**Comment by laloch** [comment]
Because I run "XONSH_DEBUG=1". The amalgamized version fails to start in the same way.

**Comment by melund** [comment]
I ran "pip install -e" and now the files are updated. I will try to see why the ptk_above_min_support() doesn't work as expected. I can reproduce your issue now. Sorry about that.

**Comment by laloch** [comment]
Could you please update xonsh-in-docker.py in the process?
- I think it should not install PTK unless requested.
- It shouldn't run `pypy3 setup.py install` anymore.
- It could install pytest by default.

**Comment by melund** [comment]
There was a problem with the code:

``` 
@functools.lru_cache(1)
def ptk_above_min_supported():
    return ptk_version_info() and ptk_version_info()[:2] >= minimum_required_ptk_version
```

It shouldn't strip third version entry (`ptk_version_info()[:2]`)

**Comment by melund** [comment]
Fallback works for me with prompt_toolkit less that 2.

image

**Comment by melund** [comment]
But a normal `pip install .` doesn't create a `__amalgam__.py` for me. And at first it did but seems to be an outdated version from a cache.

**Comment by laloch** [comment]
I can confirm, that it fixes the issue.

> But a normal `pip install .` doesn't create a `__amalgam__.py` for me.

That's something we should definitely get fixed, or maybe we could always run debug version in docker.

**Comment by melund** [comment]
It seems pip does generate all the correct files in the temporary build folder that pip creates. But the files are newer copied.

**Comment by laloch** [comment]
Does it mean that the setup is currently broken in general, or that it only fails to use the generated files in docker for some reason?

**Comment by melund** [comment]
Yes. Seems that `python setup.py install` copies files generated in the build process but `pip install .` doesn't do that. @scopatz

**Comment by laloch** [comment]
hmm, but `xonsh-in-docker.py` runs `python setup.py install` and you say, that it doesn't work either...

**Comment by melund** [comment]
No I think that is something else. The fact that `pip install .` doesn't tables and __amalgam__ files. Can you try to run `pip install .` in a clean xonsh repo. I.e. one where the __amalgam__.py  files doesnot exits. Then check if it generates the __amalgam__ files in the distribution. (also make sure to wipe Lib/site-packages/xonsh first

**Comment by laloch** [comment]
Sure. Here's what I did:
```
$ docker run -i -t python /bin/bash

root@573ef16bf41b:/# git clone https://github.com/xonsh/xonsh.git && cd xonsh
Cloning into 'xonsh'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 41681 (delta 5), reused 8 (delta 2), pack-reused 41661
Receiving objects: 100% (41681/41681), 21.50 MiB | 4.82 MiB/s, done.
Resolving deltas: 100% (29735/29735), done.

root@573ef16bf41b:/xonsh# pip install .
Processing /xonsh
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: xonsh
  Building wheel for xonsh (PEP 517) ... done
  Created wheel for xonsh: filename=xonsh-0.9.19-py3-none-any.whl size=584207 sha256=ea575aafaf6723aaa0b58c652a2509c440bd86e270eb68b50c38cad3de264673
  Stored in directory: /tmp/pip-ephem-wheel-cache-85n9s5n_/wheels/af/c9/4d/18a0d614ed72ebbde4270564172eda666bf092d1024fd3ace6
Successfully built xonsh
Installing collected packages: xonsh
Successfully installed xonsh-0.9.19
WARNING: You are using pip version 20.1.1; however, version 20.2.2 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.

root@573ef16bf41b:/xonsh# cd /
root@573ef16bf41b:/# find . -name amalgam.py
root@573ef16bf41b:/#
```
No amalgam.py for me either.

**Comment by melund** [comment]
Great. I have created an issue for it here. https://github.com/xonsh/xonsh/issues/3681

I have no time to do anything about the next weeks so if anyone knows something about pip, feel free.

**Pull request merged**
