### PR TITLE
Handle regex error

### PR DESCRIPTION
**Pull request by AkshayWarrier**
This PR fixes https://github.com/xonsh/xonsh/issues/4993

I'm only specifically catching that error and throwing an error message. Let me know if I need to change something or maybe phrase the error message better.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Comment by AkshayWarrier** [comment]
Hi, what's the status of this issue? Do I need to do something or will this PR get merged?

**Comment by jnoortheen** [comment]
pre-commit.ci autofix

**Comment by jnoortheen** [comment]
Hi @AkshayWarrier , the PR is fine, I've triggered autoformat of the code. Please wait for the members to review the PR.

**Comment by gforsyth** [comment]
I'm going to merge this -- we can sort of the flake8 errors from the new version of flake8 in a follow-up.

Thanks for the PR @AkshayWarrier !

**Pull request merged**
