### PR TITLE
#3402 set the exit code for single commands

### LINKED ISSUE #3402: xonsh always returns zero when used as the shell in vim/neovim
## Expected Behavior
If I run a command within vim/neovim and that command fails, I should see a non-zero return code in `v:shell_error`.

## Current Behavior
If the shell for vim/neovim to use is xonsh, `v:shell_error` always contains zero.

## Steps to Reproduce
open vim/neovim
```
:set shell=bash
:!rm non-existent-file
/usr/bin/rm cannot remove 'non-existent-file': No such file or directory

shell returned 1

Press ENTER or type command to continue
:echo(v:shell_error)
1

:set shell=xonsh
:!rm non-existent-file
/usr/bin/rm cannot remove 'non-existent-file': No such file or directory

Press ENTER or type command to continue
:echo(v:shell_error)
0
```

## xonfig
+------------------+-----------------+
| xonsh            | 0.9.8           |
| Python           | 3.7.5           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.10          |
| shell type       | prompt_toolkit2 |
| pygments         | 2.3.1           |
| on posix         | True            |
| on linux         | True            |
| distro           | ubuntu          |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+

## Further Info
This works fine outside vim/neovim within a terminal running xonsh:
```
!(rm non-existent-file)
/usr/bin/rm: cannot remove 'non-existent-file': No such file or directory
CommandPipeline(stdin=<_io.BytesIO object at 0x7f056e858d10>, stdout=<_io.BytesIO object at 0x7f056e858d70>, stderr=<_io.BytesIO object at 0x7f056e858dd0>, pid=32062, returncode=1, args=['rm', 'non-existent-file'], alias=None, stdin_redirect=['<stdin>', 'r'], stdout_redirect=[9, 'wb'], stderr_redirect=[11, 'w'], timestamps=[1576055751.5550349, 1576055751.5620785], executed_cmd=['/usr/bin/rm', 'non-existent-file'], input=, output=, errors=/usr/bin/rm: cannot remove 'non-existent-file': No such file or directory)
```

It even works fine within a vim/neovim terminal when xonsh is the shell:
open vim/neovim
```
:set shell=xonsh
:terminal
!(rm non-existent-file)
/usr/bin/rm: cannot remove 'non-existent-file': No such file or directory
CommandPipeline(stdin=<_io.BytesIO object at 0x7fb79b2af410>, stdout=<_io.BytesIO object at 0x7fb79b2af470>, stderr=<_io.BytesIO object at 0x7fb79b2af4d0>, pid=31794, returncode=1, args=['rm', 'non-existent-file'], alias=None, stdin_redirect=['<stdin>', 'r'], stdout_redirect=[7, 'wb'], stderr_redirect=[9, 'w'], timestamps=[1576055686.1392198, 1576055686.1452942], executed_cmd=['/usr/bin/rm', 'non-existent-file'], input=, output=, errors=/usr/bin/rm: cannot remove 'non-existent-file': No such file or directory)
```

Possibly related to #3309

## Update
Confirmed as showing identical behaviour on OSX (description above is from Ubuntu).

### PR DESCRIPTION
**Pull request by dyuri**
Attempt to fix #3402 .

```
$ touch file_exists
$ xonsh -c "rm file_exists"
$ _.rtn
0
$ xonsh -c "rm no_such_file"
/usr/bin/rm: cannot remove 'no_such_file': No such file or directory
$ _.rtn
1
$ xonsh -c "sys.exit(123)"
$ _.rtn
123
```

(But it still does not seem to fix the issue with Fugitive.)

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks for putting this in @dyuri! Can you add a case or two here to the integration tests?

**Comment by dyuri** [comment]
Sure, on it.

**Comment by dyuri** [comment]
(I have no access to any windows machine so I've added `@skip_if_on_windows` for now.)

**Comment by scopatz** [comment]
Thanks! I think skipping windows makes sense for this feature.  Also, can you please add a news item?

**Comment by dyuri** [comment]
News entry added.

**Comment by dyuri** [comment]
Sorry, I just noticed that on macOS `ls` returns 1 for non-existing entry (but I created the tests under linux where it returns 2). I'll replace it with something else.

**Comment by dyuri** [comment]
Ok, now it seems to be fine, for some reason the checks for this PR used the old code (?), but in my fork they are all OK now: https://github.com/dyuri/xonsh/actions/runs/186758594

**Comment by scopatz** [comment]
So I tried restarting and it didn't do anything.  Maybe try merging from master?

**Comment by dyuri** [comment]
Yep, saw that, trying.

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
