### PR TITLE
Create xonshpytest.yml

### PR DESCRIPTION
**Pull request by gforsyth**
Trying out github actions for CI matrix

### CODE REVIEW

**Comment by gforsyth** [comment]
Hey @xonsh/xore -- any thoughts on this approach?  I was mostly playing with github actions, but the matrix over versions + operating systems is nice.  Only thing it wouldn't cover is doc builds (still on travis for the moment)

**Comment by melund** [comment]
I think it looks great. Nice and simple. I don't care much which we use. But going for something simple and well integrated like gh actions is a good idea. So +1 from me

**Comment by scopatz** [comment]
Yep! This is awesome! Thanks a ton @gforsyth! 

My only comment here is that we should probably reinstate the OSX builds on travis until the GH actions work on OSX too.

**Comment by gforsyth** [comment]
> My only comment here is that we should probably reinstate the OSX builds on travis until the GH actions work on OSX too.

I'm bummed because they _were_ working, but I kept getting timeout failures.  I'll re-enable OSX on travis for the moment and then we can track down flaky tests afterwards

**Comment by scopatz** [comment]
The circle error is just because we are no longer using it :wink:

**Comment by gforsyth** [comment]
I just deleted all of our unused webhooks (codecov, circle, azure) so they should stop showing up in PRs from now on

**Pull request merged**
