### PR TITLE
Added repl.it to the docs

### PR DESCRIPTION
**Pull request by scopatz**
Regains the xonsh live idea!  It isn't perfect, but I think it is good enough.  

Thanks again to @astronouth7303! The events system was essential here to routing around some weird bugs in repl.it

### CODE REVIEW

**Comment by scopatz** [comment]
Feedback is much appreciated!

**Comment by melund** [comment]
This is interesting. It is kind of a shame that much of the shell part is missing. Seems subprocess are not possible on repl.it as well as tab completion. Or am I wrong? That is a big part of what makes up xonsh.

**Comment by scopatz** [comment]
subprocesses worked for me, things like `ls`, `echo`, `python` etc.  It is a little funny because the `xonsh` command doesn't actually get installed.

Yeah, it is a real shame that tab completion fails.  I have opened an issue with them.  A big part of the definicency is that they haven't implement a full xterm terminal, they just kinda did a partial job. My hope is that things improve.

**Comment by melund** [comment]
He he. I was too hasty. `ls` does work for me. Just clear didn't do its thing.

**Comment by melund** [comment]
I think we should just add this. On a side note; I do miss the asciinema video we once had on frontpage. @scopatz Did you make some ghosttyping once. Could we get something like that to produce the asciinema videos. I imagine it was crazy hard to record.

**Comment by scopatz** [comment]
Yeah we could add that too. It wasn't too hard to record, I don't think. The annoying thing was just executing the script correctly.

I am not suprised that clear doesn't work, since it isn't a real terminal. I'll open an issue.

Also it looks like some of the file contents were deleted?! Weird. Maybe this isn't ready for prime-time...

**Comment by scopatz** [comment]
Well, I think I got it working again.

**Comment by scopatz** [comment]
Apperently they are working on ANSI escape codes: https://repl.it/bugs/p/clear-command-doesnt-work-in-terminal  Hopefully all of the current issues will be fixed when that occurs.

**Comment by timmyichen** [comment]
Hey all, Tim from Repl.it here.  Just to give some more details and context, right now we're using [jqconsole](https://github.com/replit/jq-console) (which we created a while ago) but are moving to [xtermjs](https://xtermjs.org/) to provide bash support + ANSI escape sequences, etc.  Let me know if you'd be interested in testing it when we have a beta version ready. :)

**Comment by scopatz** [comment]
Hey @timmyichen! Thanks for reaching out. I really appreciate all of the hard work that your team has put into repl.it!  We'd love to test it when there is a beta version available. That'd be great. I'm glad youare moving to xtermjs!

**Comment by melund** [comment]
I am all for getting this on the development docs now.

**Comment by scopatz** [comment]
Thanks @melund! It would be nice to put out a release this week. Are there any objections to having this hit the front page?

**Pull request merged**
