### PR TITLE
Interruptable Proc Proxies

### PR DESCRIPTION
**Pull request by scopatz**
This should address #830, finally.

### CODE REVIEW

**Comment by mitnk** [comment]
In this PR the `bash` process not killed fully. It is left as a zombie (on Mac at least) after `^C`:
```
USER   PID  PPID  PGID TPGID STAT COMMAND
hugo 25960 25959 25959 25959 S+   Python -u xonsh
hugo 25965 25960 25965 25959 Z    (bash)   # <-- sleep process was killed, but not bash
```

This issue #830 is not an issue in PR #2177 branch (without the patch of this PR). And `bash`, `sleep` processes was killed successfully. So I suggest PR #2177 to go master first then we check how it affects the jobs control issues including these: #2133 and this one?

**Comment by scopatz** [comment]
> In this PR the bash process not killed fully. It is left as a zombie (on Mac at least) after ^C

Hmm that is very strange. On Linux the process it completely gone.  I am happy with waiting, but in any event it does seem to fix the problem on Linux.

**Comment by mitnk** [comment]
So this PR also clean the pipes opened, so I think it is good to go. no zombie issue anymore with current master.

**Comment by gforsyth** [comment]
Merge away, @mitnk !

**Comment by mitnk** [comment]
@gforsyth I thought we may have different plans, any way, merged! :)

**Pull request merged**
