### PR TITLE
Ptk 2.0!

### PR DESCRIPTION
**Pull request by tgoodlet**
Works towards completing #2564.

There's been one trivial patch I needed to make to `ptk` namely accepting a `_` for `pygments` style names in the regex pattern [here](https://github.com/jonathanslenders/python-prompt-toolkit/blob/2.0/prompt_toolkit/styles/style.py#L138).

I'm stuck at the moment trying to get the prompt tokens to render. It's failing currently with:

```python
Unhandled exception in event loop:
  File "/home/tyler/repos/python-prompt-toolkit/prompt_toolkit/eventloop/posix.py", line 149, in _run_task
    t()
  File "/home/tyler/repos/python-prompt-toolkit/prompt_toolkit/eventloop/context.py", line 115, in new_func
    return func(*a, **kw)
  File "/home/tyler/repos/python-prompt-toolkit/prompt_toolkit/application/application.py", line 312, in redraw
    self._redraw()
  File "/home/tyler/repos/python-prompt-toolkit/prompt_toolkit/application/application.py", line 372, in _redraw
    self.renderer.render(self, self.layout)
  File "/home/tyler/repos/python-prompt-toolkit/prompt_toolkit/renderer.py", line 511, in render
    layout.container.preferred_height(size.columns, size.rows).preferred)
  File "/home/tyler/repos/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 206, in preferred_height
    for c in self._all_children]
  File "/home/tyler/repos/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 206, in <listcomp>
    for c in self._all_children]
  File "/home/tyler/repos/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 564, in preferred_height
    return self.content.preferred_height(width, max_available_height)
  File "/home/tyler/repos/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 206, in preferred_height
    for c in self._all_children]
  File "/home/tyler/repos/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 206, in <listcomp>
    for c in self._all_children]
  File "/home/tyler/repos/python-prompt-toolkit/prompt_toolkit/layout/containers.py", line 1946, in preferred_height
    if self.filter():
  File "/home/tyler/repos/python-prompt-toolkit/prompt_toolkit/filters/base.py", line 213, in __call__
    return self.func()
  File "/home/tyler/repos/python-prompt-toolkit/prompt_toolkit/shortcuts/prompt.py", line 85, in has_before_fragments
    for fragment, char in get_prompt_text():
  File "/home/tyler/repos/python-prompt-toolkit/prompt_toolkit/shortcuts/prompt.py", line 693, in _get_prompt
    return to_formatted_text(self.message, style='class:prompt', auto_convert=True)
  File "/home/tyler/repos/python-prompt-toolkit/prompt_toolkit/formatted_text.py", line 55, in to_formatted_text
    assert isinstance(value[0][0], six.text_type)
```
This seems to be failing due to `value` being `[(Token.Color.NO_COLOR, '\n '), (Token.Color.GREEN, '>>> ')]`

@jonathanslenders @scopatz any tips would be appreciated :)

I've also put a couple comments in where I've been unsure what to do.

### CODE REVIEW

**Comment by scopatz** [comment]
Hi @tgoodlet, thanks for putting this in!  I have two thoughts:

1. Is PTK v2 backwards incompatible with v1?  It looks like it is.  If so, we should probably have a separate shell type for it ('prompt_toolkit2'?) so that both can be supported.  We don't want to merge this and then break everyone's shell :)

2. Those tokens that it is failing on are the xonsh custom tokens.  They are added in xonsh.pygutils and enable xonsh custom colors: http://xon.sh/tutorial.html#customizing-the-prompt If PTK is doing something radically different, from pygments it needs to have its own color formatter. An example can be seen in `xonsh.pygutils` and also in `xonsh.ansi_colors`.

I hope this helps! Let me know if you have other questions.

**Comment by astronouth7303** [comment]
Is upstream still supporting PTKv1?

**Comment by scopatz** [comment]
> Is upstream still supporting PTKv1?

It will probably be in the distros for a while...

**Comment by jonathanslenders** [comment]
1. Yes, there are some breaking changes between these two versions. It was the only way to move forward. I'm not sure that supporting both prompt_toolkit versions is really worth the effort, I never really thought about that.

2. prompt_toolkit 2.0 uses the concept of "FormattedText". This can be constructed from plain text, ANSI escape sequences, some limited form of HTML, a list of (style, text) tuples, or a list of (PygmentsToken, text) tuples. If you want to keep using these pygments tokens, you can wrap it in ``PygmentsTokens``. See this class: https://github.com/jonathanslenders/python-prompt-toolkit/blob/2.0/prompt_toolkit/styles/pygments.py#L44
I'm not sure that an automatic conversion in prompt_toolkit is feasible, because I don't want to depend on Pygments anymore.

**Comment by tgoodlet** [comment]
>We don't want to merge this and then break everyone's shell :)

@scopatz My thought would be don't release this until `1.0` then. I'm not a huge fan of maintaining legacy components but it's of course up to you.

>if you want to keep using these pygments tokens, you can wrap it in PygmentsTokens

@jonathanslenders awesome thanks for the tip 👍 

>I'm not sure that an automatic conversion in prompt_toolkit is feasible, because I don't want to depend on Pygments anymore.

Wait does that mean `xonsh` has to adapt to the new `FormattedText` system immediately?

**Comment by asmeurer** [comment]
Even without backwards support, it's impossible to have both 1.0 and 2.0 installed at the same time in the same environment, unless @jonathanslenders renames the package. So if you are stuck with something that isn't updated for 2.0 you won't be able to update xonsh, assuming it becomes 2.0-only (or you would be forced to use the readline shell).

**Comment by scopatz** [comment]
> @scopatz My thought would be don't release this until 1.0 then. I'm not a huge fan of maintaining legacy components but it's of course up to you.

I think we have no choice but to support both for the short term, though we may want to slap a deprecation warning on v1.0 after v2.0 comes out.

> Wait does that mean xonsh has to adapt to the new FormattedText system immediately?

I think he is saying that we can use `PygmentsTokens` for the moment, but eventually we'll want to migrate over.

**Comment by jonathanslenders** [comment]
Would it be possible or make sense to "vendor" prompt_toolkit as part of Xonsh when 2.0 is ready? So, to include it and import it as ``xonsh.vendor.prompt_toolkit`` or something like that?

``PygmentsTokens`` is an adaptor indeed. In the future, you can indeed use (style,text) tuples. They look like this:

- ``[('class:myclass', 'some text'), ...]``  (refer to a classname in the style sheet.)
- ``[('bg:ansired', 'some text'), ...]``  (inline style.)
- ``prompt_toolkit.formatted_text.HTML('<ansired>some text</ansired>')`` (using "HTML".)

**Comment by tgoodlet** [comment]
@jonathanslenders I used the `pygments_token_to_classname` func (after patching it to actually work) with some success but I'm now hitting this:

```python
Unhandled exception in event loop:                                                              
  File "/home/tyler/repos/python-prompt-toolkit/prompt_toolkit/eventloop/posix.py", line 149, in _run_task                                                                                                                                                                         
    t()                                                                                                                                                                                                                                                                            
  File "/home/tyler/repos/python-prompt-toolkit/prompt_toolkit/eventloop/context.py", line 115, in new_func
    return func(*a, **kw)                                                                            
  File "/home/tyler/repos/python-prompt-toolkit/prompt_toolkit/application/application.py", line 312, in redraw                                                                                                                                                                    
    self._redraw()                                                                                                                                                                                                                                                                 
  File "/home/tyler/repos/python-prompt-toolkit/prompt_toolkit/application/application.py", line 372, in _redraw
    self.renderer.render(self, self.layout)                                                                          
  File "/home/tyler/repos/python-prompt-toolkit/prompt_toolkit/renderer.py", line 549, in render                                                                                                                                                                                   
    previous_width=(self._last_size.columns if self._last_size else 0))                                                                                                                                                                                                            
  File "/home/tyler/repos/python-prompt-toolkit/prompt_toolkit/renderer.py", line 170, in _output_screen_diff
    output_char(new_char)                                                                                     
  File "/home/tyler/repos/python-prompt-toolkit/prompt_toolkit/renderer.py", line 112, in output_char                                                                                                                                                                              
    _output_set_attributes(attrs_for_style_string[char.style])                                                                                                                                                                                                                     
  File "/home/tyler/repos/python-prompt-toolkit/prompt_toolkit/renderer.py", line 231, in __missing__
    result = self.get_attrs_for_style_str(style_str)    
  File "/home/tyler/repos/python-prompt-toolkit/prompt_toolkit/styles/style.py", line 309, in get_attrs_for_style_str                                                                                                                                                              
    return self._merged_style.get_attrs_for_style_str(style_str, default)                                                                                                                                                                                                          
  File "/home/tyler/repos/python-prompt-toolkit/prompt_toolkit/styles/style.py", line 234, in get_attrs_for_style_str
    inline_attrs = _parse_style_str(part)
  File "/home/tyler/repos/python-prompt-toolkit/prompt_toolkit/styles/style.py", line 133, in _parse_style_str                                                                                                                                                                     
    attrs = attrs._replace(color=_colorformat(part))                                                                                                                                                                                                                               
  File "/home/tyler/repos/python-prompt-toolkit/prompt_toolkit/styles/style.py", line 54, in _colorformat
    raise ValueError('Wrong color format %r' % text)
                                                                         
Exception Wrong color format 'pygments.color.no_color' 
```
Any ideas?

**Comment by jonathanslenders** [comment]
Why the patch? Did it fail otherwise?

The ``pygments_token_to_classname`` function only generates the classname. This means that if you want to use it in a formatted text list, you have to prefix it with ``'class:'``.  E.g. ``class:pygments.color.no_color``.
The reason is that in these places you can either refer to a class name, or directly use inline styling, like ``bg:red``.

**Comment by jonathanslenders** [comment]
If you have some time, please have a look at this question I have, regarding whether or not we have to change the name of the prompt_toolkit package:
https://github.com/jonathanslenders/python-prompt-toolkit/issues/568

**Comment by tgoodlet** [comment]
@jonathanslenders I've gotten to a point where now I'm out of my league in terms of how to debug ptk. 

I've got `xonsh` to start up and not crash and I can enter input. Currently the shell seems to just swallow input and not return output. I also can't kill it with the normal `c-d` or `c-c` combos. I'd appreciate your help to debug this further. I've also proposed a couple changes in jonathanslenders/python-prompt-toolkit#569

@scopatz I've adjusted the patch to handle both ptk `1.0` and `2.0` as requested. I'd appreciate your feedback on the current approach for that :)

I haven't had a chance to look through the CI failures yet..

**Comment by jonathanslenders** [comment]
In prompt_toolkit 2.0, c-c and c-d send respectively KeyboardInterrupt and EOFError, like the built-in input() function. In prompt_toolkit 1.0, this was configurable with an AbortAction. It's best to correctly handle the exceptions in xonsh/ptk/shortcuts.py when calling the run() function.

Furter, I think you need this patch:

```diff
diff --git a/xonsh/ptk/completer.py b/xonsh/ptk/completer.py
index 2c867e45..e9af9c75 100644
--- a/xonsh/ptk/completer.py
+++ b/xonsh/ptk/completer.py
@@ -84,7 +84,7 @@ class PromptToolkitCompleter(Completer):
     def suggestion_completion(self, document, line):
         """Provides a completion based on the current auto-suggestion."""
         cli = self.shell.prompter.cli
-        sug = self.hist_suggester.get_suggestion(cli, cli.current_buffer, document)
+        sug = self.hist_suggester.get_suggestion(cli.app.current_buffer, document)
         if sug is None:
             return None
         comp, _, _ = sug.text.partition(' ')
@@ -92,8 +92,10 @@ class PromptToolkitCompleter(Completer):
         return prev + comp
```
I hope this helps. I think there are a couple of other changed required. I'll see in the coming weeks whether I find some time to help you. It looks like Xonsh is one of the more complex projects to convert, it's using a lot of prompt_toolkit internals.

**Comment by tgoodlet** [comment]
@jonathanslenders made the change you suggested for the suggester.

Things are looking slightly better after pulling the latest ptk 2.0 updates but now I'm stuck seeing a couple oddities:
- a blank bottom toolbar seems to always show up
- whenever I hit enter I get a multi-line prompt instead of seeing output

Again, any pointers are greatly appreciated.

**Comment by gforsyth** [comment]
Hey @tgoodlet -- thanks for all of your work on this!  The PTK backend has evolve with PTK itself and is a bit of a frankenstein at this point, sorry for the pain!
The issue with always getting a multiline prompt is, I think, to do with the `carriage_return` function in `key_bindings.py`.  We overload the `Enter` key to always be a multiline-Enter, but then if the command can be compiled, we execute it -- if the behavior of `validate_and_handle` has changed, then it would stop this from working.

**Comment by tgoodlet** [comment]
@gforsyth thanks!
I'll toy with the funcs you've suggested to see if I can make some more progress.

**Comment by jonathanslenders** [comment]
A few required changes due to a recent rename:
```diff
diff --git a/xonsh/ptk/shell.py b/xonsh/ptk/shell.py
index 3d58987d..2f41a9d1 100644
--- a/xonsh/ptk/shell.py
+++ b/xonsh/ptk/shell.py
@@ -4,7 +4,10 @@ import sys
 import builtins

 from prompt_toolkit.auto_suggest import AutoSuggestFromHistory
-from prompt_toolkit.layout.lexers import PygmentsLexer
+try:
+    from prompt_toolkit.layout.lexers import PygmentsLexer
+except ImportError:
+    from prompt_toolkit.lexers import PygmentsLexer

 from xonsh.platform import ptk_version_info
 from xonsh.base_shell import BaseShell
@@ -30,8 +33,8 @@ else:  # ptk 2.0
     from prompt_toolkit.shortcuts import print_formatted_text as ptk_print
     from prompt_toolkit.shortcuts import CompleteStyle
     from prompt_toolkit.formatted_text import PygmentsTokens
-    from prompt_toolkit.styles.pygments import (
-        style_from_pygments, Style, pygments_token_to_classname)
+    from prompt_toolkit.styles.pygments import Style, pygments_token_to_classname
+    from prompt_toolkit.styles.pygments import style_from_pygments_cls as style_from_pygments
```

**Comment by jonathanslenders** [comment]
A couple of fixes here:
https://github.com/tgoodlet/xonsh/pull/1/files

- The ``reserve_space`` thing: it's pretty fragile, the way it works, but this should fix it for now. (This depends on some internal implementation details of prompt_toolkit. I'll try my best not to break Xonsh, but we might have a look at a better way for doing this.)
- ``b.accept_action.validate_and_handle(cli, b)`` became ``b.validate_and_handle()``.
- ``app.current_buffer_name`` became ``app.current_buffer.name`` (PTK1 did not had a ``name`` attribute for ``Buffer``.)
- ``ControlM`` became ``ControlJ``: PTK1.0 had a bug where it translated ``\r`` into ``\n`` automatically. This was bad because we couldn't bind different key bindings to ``c-m`` and ``c-j``. There was however no way of fixing this without breaking many applications. Binding the enter key to both solves it for Xonsh.
- ``return self.cli.prompt(message=message, **kwargs)``: Here the return was missing, which explains why nothing was executed ever.
- The bottom toolbar is displayed if something not ``None`` is passed to the ``bottom_toolbar`` argument.

**Comment by scopatz** [comment]
Any updates on this?

**Comment by tgoodlet** [comment]
Sorry @scopatz not yet..
I've been real distracted with other projects currently.
I'll do my best to get to this this week.

**Comment by scopatz** [comment]
Thanks!

**Comment by SolarAquarion** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20740, in main
    args = premain(argv)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20693, in premain
    env = start_services(shell_kwargs, args)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20645, in start_services
    builtins.__xonsh_shell__ = Shell(execer=execer, **shell_kwargs)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 13154, in __init__
    from xonsh.ptk.shell import get_ptk_shell as shell_class
  File "/usr/lib/python3.6/site-packages/xonsh/ptk/shell.py", line 18, in <module>
    from xonsh.ptk.shortcuts import get_prompter
  File "/usr/lib/python3.6/site-packages/xonsh/ptk/shortcuts.py", line 17, in <module>
    from prompt_toolkit.shortcuts import Prompt
ImportError: cannot import name 'Prompt'

**Comment by jonathanslenders** [comment]
Ok. ``Prompt`` should become ``PromptSession``. Further, there are some changes in the history class. Prompt_toolkit has now natively support for async loading of the history, and because of that, the API changed a little.

**Comment by tgoodlet** [comment]
Oh boy. Yeah really need to get back to this..hehe.
I'm going to try my best tonight!

**Comment by scopatz** [comment]
That would be awesome @tgoodlet!

**Comment by melund** [comment]
@tgoodlet  Any news on this :) It a shame if xonsh should hold people back from using PTK2.

**Comment by scopatz** [comment]
I am going to try working on this from @tgoodlet's fork now. We'll see how far I get :)

**Comment by tgoodlet** [comment]
@scopatz @melund yeah sorry I'm the worst... I keep trying to start again and then getting distracted with other stuff.

@scopatz if you haven't pushed something by tonight I'm going to start toying with it again.

**Comment by melund** [comment]
> I keep trying to start again and then getting distracted with other stuff.
@tgoodlet I know it all too well.

 I think @scopatz did continue on this the other day. Building on top of your work. You can see his branch here: https://github.com/xonsh/xonsh/tree/ptk_2.0

**Comment by tgoodlet** [comment]
Nice! Glad it's moving forward. @scopatz is far more qualified then me anyway :)
I still want to play with 2.0 more then ever so hopefully it gets in soon :+1:

**Comment by tgoodlet** [comment]
Hmm I wonder if this PR can be altered to use @scopatz's new branch?

**Comment by gforsyth** [comment]
> I wonder if this PR can be altered to use @scopatz's new branch?

The target of the PR can be changed but not the source.  It would be nice to have the history of this PR included in everything, though.  Also, @tgoodlet, thanks for all of your work on this.  It was a big undertaking to get it this far in the first place.  

If you check the "allow edits from maintainers" I can push up the changes from @scopatz branch to this PR.

**Comment by tgoodlet** [comment]
>f you check the "allow edits from maintainers" I can push up the changes 

@gforsyth that box seems checked but I re-checked just in case.

> Also, @tgoodlet, thanks for all of your work on this. It was a big undertaking to get it this far in the first place.

My pleasure. Sorry I didn't take it to completion (would have liked the cred with you bunch) but I just have had too many non-software projects take up time recently.

**Comment by DNGros** [comment]
Hi, I was wondering what the status of this was. I'm excited to see this integrated in. 

While this is being resolved, should possibly behavior in main.py be changed to fallback to the readline shell if prompt_toolkit>=2.0 is installed. Obviously proper prompt_toolkit 2.0 support is preferred, but this could be quick fix which would at least avoid showing an error message and failing to running xonsh at all.

**Comment by gforsyth** [comment]
> While this is being resolved, should possibly behavior in main.py be changed to fallback to the readline shell if prompt_toolkit>=2.0 is installed. Obviously proper prompt_toolkit 2.0 support is preferred, but this could be quick fix which would at least avoid showing an error message and failing to running xonsh at all.

Hey @DNGros -- I think that's a great idea.  Do you want to put in a PR with the temporary fix?  I should be able to get to it later this week otherwise.  And after it's in we can put out a "fix" release.

**Comment by DNGros** [comment]
@gforsyth sure, I can take a look at it and submit a PR.

**Comment by DNGros** [comment]
I implemented the above mentioned fallback quickfix on [DNGros:xonsh/ptk2fallback](https://github.com/DNGros/xonsh/tree/ptk2fallback) with [b6662e25](https://github.com/DNGros/xonsh/commit/b6662e2589116d095dbab46a54722c8e153b3823). The fallback seems to work fine. However, when I tried out downgrading to ptk 1.0.15 to test that out, I now get this error on launch:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20795, in main
    args = premain(argv)
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20748, in premain
    env = start_services(shell_kwargs, args)
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20700, in start_services
    builtins.__xonsh_shell__ = Shell(execer=execer, **shell_kwargs)
  File "/usr/local/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 13216, in __init__
    ctx=self.ctx, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/xonsh/ptk/shell.py", line 51, in __init__
    events.on_ptk_create.fire(self.prompter, self.history, self.pt_completer, self.key_bindings_manager)
TypeError: fire() takes 1 positional argument but 5 were given
Xonsh encountered an issue during launch
Failback to /bin/bash
```
I see this same behavior with ptk 1.0.15 on master as well. I am not sure what is going on. After the downgrade `xonsh --shell readline` still works just fine.

Anyone seen something similar or have any ideas?

**Comment by gforsyth** [comment]
Hey @DNGros -- I just tried out your fix and it works for me.  Go ahead and open a PR and we can try to replicate and then fix the issue.

**Comment by DNGros** [comment]
@gforsyth , thanks for trying it out and letting me know. I opened PR #2700 for it.

**Comment by scopatz** [comment]
Closing due to the merger of #2716

**Pull request closed without merging**
