### PR TITLE
Addressed double equals issue, and others

### PR DESCRIPTION
**Pull request by scopatz**
This is a fix for #1754

### CODE REVIEW

**Comment by laerus** [comment]
this doesn't seem to fix the issue still getting an error in subproc mode:

```
$ pip3 install django==1.9.9
.......
SyntaxError: <xonsh-code>:1:21: ('code: ==',)
![pip3 install django==1.9.9]
                     ^
```

**Comment by scopatz** [comment]
hmm, what if you do `echo django==1.9.9`?  The test I added passed....

**Comment by laerus** [comment]
I tried a plain `echo ==` and I still get the issue, but now that I think of it I always had issues on develop mode with not catching up the changes on the parser, will try again. Maybe I must delete the parser table.

**Comment by scopatz** [comment]
Oh! That might be a separate bug :)

**Comment by laerus** [comment]
allright! the problem was local after all, this works great, thanks @scopatz !

**Pull request merged**
