### PR TITLE
Ptk 2.0 Try Again

### PR DESCRIPTION
**Pull request by scopatz**
This uses and supersedes @tgoodlet's awesome work in #2570, and adds support for PTK.  It also adds some extra features along the way.

### CODE REVIEW

**Comment by tgoodlet** [comment]
Woot! Excited to try this out :+1:

**Comment by melund** [comment]
This works fantastically well on Windows. Thanks a lot, @scopatz and @gforsyth. Now I am able to use xonsh again after #2703... 

I still need to test this on older versions of Windows, where PTK can't use the new ANSI/VT100 backend.

**Comment by melund** [comment]
I say go :) I haven't been able to test it on Windows 8, but I can't wait to get this in...

**Comment by scopatz** [comment]
Woohoo! Thanks to @tgoodlet @gforsyth and @melund for helping out with this!  I'll go ahead and cut a release so that it works for everyone!

**Comment by DNGros** [comment]
Awesome! Thanks for your great work!

**Pull request merged**
