### PR TITLE
Better Append Newline Default

### LINKED ISSUE #2603: cat file without eol
In bash:
```
worldmind@host:~$ cat file
FILEDATASTRworldmind@host:~$
```
in xonsh
```
worldmind@host ~ master $ cat file
worldmind@host ~ master $
```
we don't see string from file
looks like problem with buffering

### PR DESCRIPTION
**Pull request by scopatz**
Should close #2603

### CODE REVIEW

**Comment by gforsyth** [comment]
lgtm, thanks @scopatz!

**Comment by gforsyth** [comment]
Hmm, so travis passed here but then failed on Python3.4 on OSX when it tried to build off of master...

**Comment by scopatz** [comment]
Hmm weird.  There seem to be some test instabilities I can't reproduce locally.

**Comment by gforsyth** [comment]
I can't reproduce them either.  Could possibly be a weird travis hiccup?

**Comment by scopatz** [comment]
Yeah, it is weird. I am looking at the rawlambda failure in #2606 and it seems like it isn't actually picking up the changes.

**Pull request merged**
