### PR TITLE
Replace StopIteration with return

### PR DESCRIPTION
**Pull request by WouldYouKindly**
[PEP-479](https://www.python.org/dev/peps/pep-0479/) says 
"Finally, the proposal also clears up the confusion about how to terminate a generator: the proper way is return, not raise StopIteration."

This addresses [https://github.com/xonsh/xonsh/issues/2593](https://github.com/xonsh/xonsh/issues/2593)

### CODE REVIEW

**Comment by WouldYouKindly** [comment]
Not sure if it deserves a news item...

**Comment by scopatz** [comment]
Hi @WouldYouKindly - thanks for the fix!  I think this defintiely needs a news item (especially if it solves another issue).  

One small issue here is that this would break compatabilty with Python 3.4 because PEP-479 didn't go into effect until v3.5 (if I am not mistaken).  Also v3.4 [doesn't reach end-of-life until 2019-03-16](https://devguide.python.org/#status-of-python-branches). So I think we need an if-statement here that checks if we are on Python v3.4

**Comment by scopatz** [comment]
Oh! I thought it would! If it doesn't, that's great.

**Comment by scopatz** [comment]
Thanks a million @WouldYouKindly!

**Pull request merged**
