### PR TITLE
Another pipeline fix

### PR DESCRIPTION
**Pull request by adqm**
I believe this should fix the original issue described in #1330, by making sure all the processes in a pipeline are part of the same process group.

### CODE REVIEW

**Comment by adqm** [comment]
I have done some testing on my own and this seems to do the trick.  This might be a big enough bug that this warrants a micro-release, assuming it looks okay to everyone else.

**Comment by scopatz** [comment]
looks good to me!

**Comment by scopatz** [comment]
Thanks @adqm!

**Comment by scopatz** [comment]
Also, feel free to do a micro release whenever you feel like it. I have already done one today, so I will tap out myself :)

**Pull request merged**
