### PR TITLE
Add circle-ci build status badge to readme

### PR DESCRIPTION
**Pull request by nigeltea**
Issue 1696

### CODE REVIEW

**Comment by laerus** [comment]
thank you for this @nigeltea!

**Comment by willingc** [comment]
Thanks @nigeltea! @laerus @gforsyth @Carreau,  I had the pleasure of meeting @nigeltea at PyData Carolinas when @scopatz and I shared xonsh and Jupyter with others. 🎉

**Comment by nigeltea** [comment]
Thank you for merging @laerus. This was my first public contribution, looking forward to many more. Thank you @willingc for the guidance and @scopatz + many more at PyData Carolinas for the motivation to finally get started!

**Comment by willingc** [comment]
You are very welcome @nigeltea. Just ask these folks if you need a suggestion for the next contribution :wink:

P.S. @gforsyth is a wonderful teacher too. I took his Numba tutorial with Lorena Barba this summer. Gil, check out slides 5-7 from my PyData talk for a small chuckle http://www.slideshare.net/willingc/data-decision-making-and-being-human

**Comment by gforsyth** [comment]
:blush: thanks, @willingc !  I'm looking forward to watching the video of your PyData talk!

**Pull request merged**
