### PR TITLE
Make iglobpath() more robust

### PR DESCRIPTION
**Pull request by scopatz**
This should address #2554

### CODE REVIEW

**Comment by astronouth7303** [comment]
Is there a matching Python bug?

**Comment by scopatz** [comment]
I didn't easily find one.  It is probably worth reporting upstream, if it is reproducible.

**Comment by astronouth7303** [comment]
well, we should probably have our own test case so we make sure it doesn't happen again.

**Comment by scopatz** [comment]
I agree, but I am not sure how to write one since it involves `os.scandir()` returning an empty string inside of `glob.iglob()`  I guess we could monkey path scandir and listdir for the test....

**Comment by scopatz** [comment]
Does anyone know the proper pytest-foo to do that?

**Comment by astronouth7303** [comment]
I would guess https://pypi.python.org/pypi/pytest-mock

**Comment by melund** [comment]
I would say something like: 

```
import os
import glob

def test_iglob(monkeypatch):
    def mockscandir(path):
        yied ''
    monkeypatch.setattr(os, 'scandir', mockscandir)
    assert glob.iglob('some/path')
```

**Comment by scopatz** [comment]
Thanks @melund @astronouth7303! I have added a monkeypatch test.

**Comment by gforsyth** [comment]
Thanks @scopatz !

**Pull request merged**
