### PR TITLE
adopt NEP-0029

### PR DESCRIPTION
**Pull request by jnoortheen**
## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Comment by jnoortheen** [comment]
closes #4560

**Comment by jnoortheen** [comment]
@gforsyth could you review this PR?

**Review by gforsyth — CHANGES_REQUESTED** [review]
Nice!  I think we should also bump the `python_requires` in `setup.py`

**Comment by jnoortheen** [comment]
> Nice! I think we should also bump the `python_requires` in `setup.py`

@gforsyth updated it

**Review by gforsyth — APPROVED** [review]
to the future!

**Pull request merged**
