### PR TITLE
Improvements to 'autopair' behavior

### PR DESCRIPTION
**Pull request by Danmou**
Implements improvements suggested in #2520

### CODE REVIEW

**Comment by astronouth7303** [comment]
Great work! Can you add a news item per http://xon.sh/devguide.html#changelog ?

**Comment by Danmou** [comment]
I just made a small improvement, so nested brackets should work as expected. It should be all ready now.

**Comment by astronouth7303** [comment]
I don't know PTK well. Is this code testable?

**Comment by Danmou** [comment]
Maybe, but to be honest I have no experience with unit testing. The changes I've made are pretty simple, since it's just a restriction of the cases where the autopair behavior should take place. It's difficult to define a 'correct' behavior, because it is somewhat dependent on personal preference, but I've made it so it pretty closely follows the behavior in Sublime Text (with the exception that ST sometimes changes it's behavior if there are unmatched brackets or quotes, which I think would be overkill in our case).

There's a more detailed description of the behavior in #2520

**Comment by gforsyth** [comment]
It's not easily testable, since the keybindings are all inner functions and rely on a lot of the prompt_toolkit machinery.  

On the (long) todo list is to rewrite the way we define the keybindings so it's more reusable and more easily tested. This code looks reasonable to me right now and seems to work as expected. If there's some gotcha in there, it will only be an annoyance so I'm good to merge this in as is.

**Pull request merged**
