### PR TITLE
Fix aliases that reference them self

### PR DESCRIPTION
**Pull request by melund**
I think this should fix the problem with aliases that reference them self. #1240 

@scopatz  You had this problem as well, could you verify that this work. 

Also @gforsyth maybe you better check that it doesn't break something else for you.

### CODE REVIEW

**Comment by adqm** [comment]
Unless I'm mistaken, we aren't guaranteed to have `binary_loc` defined at that point, so I think there is a chance this won't work as intended.  So I think we may also want to set `binary_loc = None` around [line 437](https://github.com/xonsh/xonsh/pull/1271/files#diff-32a5e51471ce3482f01745a4592320c1R437).

**Comment by melund** [comment]
I think you are mistaken. But I see why it is not obvious. I will add a `binary_loc=None` further . Should also make it more robust to future changes.

**Comment by gforsyth** [comment]
Hey @melund -- this makes no change on my machines, so that's good!  Just waiting on @scopatz to verify that it fixes things on his end and this is good to go.

**Comment by scopatz** [comment]
Hmm On this branch I am now seeing:

```
scopatz@localhost ~ $ ls
Desktop                       cycamore        fc-bench-method      miniconda              regolith        temp.txt  xe no .sh
Downloads                     cyclus          fc-deploy-opt        nltk_data              sandbox         test.py   xin
HW03-sol.ipynb                cyclus-release  file.txt             origen22               sdcard          test.xml  xo
PlayOnLinux's virtual drives  cymetric        foo                  pcre-feedstock         sometests.tty   umdone    xonsh
TEST                          downloads       fuelcycle.org        pycon2016              staged-recipes  urwid     xonsh-feedstock
allfuncs.sh                   emch558         george               pymoab                 sympy           wiz.xsh   xonsh-test-cdpath-home
archetype-paper               ergs-sandbox    gettext-feedstock    pyne                   sympy-paper     x         xo no .sh
cc                            ergs-website    ipython              pyne-ci                temp            x.log
courses                       faculty         libsigcpp-feedstock  python-prompt-toolkit  temp.sh         xeno.sh
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/base_shell.py", line 167, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/codecache.py", line 66, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/built_ins.py", line 635, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/built_ins.py", line 531, in run_subproc
    wait_for_active_job()
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/jobs.py", line 172, in wait_for_active_job
    _give_terminal_to(_shell_pgrp)  # give terminal back to the shell
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/jobs.py", line 153, in _give_terminal_to
    st = _shell_tty()
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/jobs.py", line 117, in _shell_tty
    _st = sys.stderr.fileno()
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/base_shell.py", line 82, in fileno
    return sys.stderr.fileno()
<snip>
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/base_shell.py", line 82, in fileno
    return sys.stderr.fileno()
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/base_shell.py", line 82, in fileno
    return sys.stderr.fileno()
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/base_shell.py", line 82, in fileno
    return sys.stderr.fileno()
  File "/home/scopatz/.local/lib/python3.5/site-packages/xonsh/base_shell.py", line 82, in fileno
    return sys.stderr.fileno()
RecursionError: maximum recursion depth exceeded
```

**Comment by scopatz** [comment]
Note that I don't see that on master.

**Comment by scopatz** [comment]
OK nevermind, I have now seen this on other branches.  This should be good to go!

**Comment by scopatz** [comment]
Thanks @melund!

**Pull request merged**
