### PR TITLE
Fix IndexError with commands 'cd' or 'ls' a repo

### PR DESCRIPTION
**Pull request by luizoti**
## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Comment by gforsyth** [comment]
@jnoortheen -- can you take a look at the failing test here?  It's consistently failing and it's from the recent commands cache PR.

**Comment by gforsyth** [comment]
Thanks for putting this in, @luizoti !

**Comment by jnoortheen** [comment]
@gforsyth sure I will check it.

**Comment by jnoortheen** [comment]
@gforsyth  sorry it seems to appear only on mac+3.9. I dont have access to a mac machine to test.

**Comment by anki-code** [comment]
It's cool to have MacOS in Virtualbox - https://github.com/myspaghetti/macos-virtualbox

**Comment by jnoortheen** [comment]
@anki-code I tried setting up the docker-osx and this script as well. They failed with some errors. I need to do some digging to get them working.

**Comment by luizoti** [comment]
Strange, this modification should not interfere with anything serious, these automatic tests from github are new things for me yet, but I will try to verify that as well.

**Comment by jnoortheen** [comment]
> Strange, this modification should not interfere with anything serious, these automatic tests from github are new things for me yet, but I will try to verify that as well.

@luizoti it is not related your changes. It is related to a PR that I created (https://github.com/xonsh/xonsh/pull/4106). It was passing before. If you are on macos, please try adding a fix for it. You can run the test suit by `xonsh run-tests.xsh test`

**Comment by anki-code** [comment]
@gforsyth this PR looks good! We're ready to merge.

**Pull request merged**
