### PR TITLE
add empty split method to fix pygments

### PR DESCRIPTION
**Pull request by gforsyth**
Mostly just checking if this works -- can't reproduce the errors
reported

### CODE REVIEW

**Comment by scopatz** [comment]
This looks good to me. Should we merge? I don't think we should wait for travis today...

**Comment by gforsyth** [comment]
Not yet -- another problem popped up

**Comment by scopatz** [comment]
Ho-kay!

**Comment by gforsyth** [comment]
Hey @sejktmcsdlmfhsc could you give this branch one more try and see if it fixes your issues?  I think I have them sorted now.

**Comment by laerus** [comment]
do we need a news item in this? or should we merge

**Comment by gforsyth** [comment]
It's a fix for errors I introduced recently, so I think it can go without a news item.  And I have confirmation that the fixes finally work so feel free to merge if it looks good.

**Comment by laerus** [comment]
looks good! thank you @gforsyth !

**Pull request merged**
