### PR TITLE
Complete while typing

### PR DESCRIPTION
**Pull request by scopatz**
This implements the desired feature in #2089. Thanks to @jonathanslenders for helping me debug!

### CODE REVIEW

**Comment by melund** [comment]
I am not the right person to test this. On windows, this gives huge performances issue. 1-second delay on every keypress is hard to work with. It may be unavoidable on Windows, but we better mention it in the docs.

**Comment by melund** [comment]
It is weird. I wonder if the bash completer gets called every time... That could explain why it is so slow.

**Comment by melund** [comment]
No wait.

**Comment by melund** [comment]
I think I accidently activated `$UPDATE_PROMPT_ON_KEYPRESS` instead. Dohh. That explains it.

**Comment by melund** [comment]
This works nicely.  I think will have this on by default in my setup.

**Comment by melund** [comment]
I think this is good to merge :) Awesome feature.

**Comment by scopatz** [comment]
Excellent! Thanks.

**Pull request merged**
