### PR TITLE
fix for xonsh exit

### LINKED ISSUE #1260: xonfig --version and --help arguments error
```
> xonsh --version
('xonsh/0.3.4',)
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 3, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 15893, in main
    args = premain(argv)
  File "/usr/local/lib/python3.5/dist-packages/xonsh/__amalgam__.py", line 15852, in premain
    exit()
TypeError: exit() missing 1 required positional argument: 'args'
```

same happens with --help options, it displays the help message and raises the same error

### PR DESCRIPTION
**Pull request by scopatz**
This should fix #1260. @laerus, would you mind testing this out please?

### CODE REVIEW

**Comment by laerus** [comment]
yes this fixes #1260

**Comment by adqm** [comment]
Looks ready to merge to me.  The only thing missing, I think, is a changelog entry.

**Comment by scopatz** [comment]
This was a break caused by the amalgamation PR so I didn't figure a CL was needed, but I am happy to add one if you want me to!

**Comment by adqm** [comment]
Oh, okay, great!  No worries then.  I'll merge in.

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
