### PR TITLE
docs: change theme to furo

### PR DESCRIPTION
**Pull request by gforsyth**
Trying out a new theme -- I really like the way `furo` looks and I think
it makes it easier to navigate our overly dense docs pages.

cc @anki-code -- interested in your design thoughts on this one

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Review by jnoortheen — APPROVED** [review]

**Comment by anki-code** [comment]
> cc @anki-code -- interested in your design thoughts on this one

Hi @gforsyth! Where I can review the new style? I tried https://xon.sh/dev/contents.html but it looks old.

**Comment by jnoortheen** [comment]
> I tried https://xon.sh/dev/contents.html but it looks old.

it shows what is on main branch. For this one, you have to check locally

**Comment by anki-code** [comment]
How to check this locally? (How to build the docs locally?)
May be we should have an article about this.

**Comment by jnoortheen** [comment]
> How to check this locally? (How to build the docs locally?) May be we should have an article about this.

Yes it can be in devguide. It is the same for all sphinx docs. 

```sh
# install sphinx and its extensions
pip install -e '.[doc]'

cd docs
make html
make serve
```

**Comment by anki-code** [comment]
I've got the error:
```bash
make html
# sphinx-build -b html -d _build/doctrees   . _build/html
# Running Sphinx v4.5.0
# [history.json] Enumerated 88 history files for 0.1223s.
# Theme error:
# no theme named 'furo' found (missing theme.conf?)
# make: *** [Makefile:39: html] Error 2
```

**Comment by jnoortheen** [comment]
> Hm, I already did it.

did you get any warning when doing pip install ? otherwise you can explicitly install it .

**Comment by jnoortheen** [comment]
I am merging this as it will be easier to test it out .

**Pull request merged**
