### PR TITLE
using --porcelain to find out if git directory dirty

### PR DESCRIPTION
**Pull request by xsteadfastx**
a pull request for #1776

### CODE REVIEW

**Comment by laerus** [comment]
thanks for this @xsteadfastx! Can you add an entry in the `news/vc_branch.rst` in the `Fixed` section?

**Comment by xsteadfastx** [comment]
@laerus done. im thinking about to add tests as well. i never contributed anything to xonsh before... so i will see how hard it is to write tests for xonsh.

**Comment by xsteadfastx** [comment]
and another question is... if we should readd the `include_untracked` argument.

**Comment by laerus** [comment]
Thank you! Another PR with tests would be awesome, i guess we should mock out the subprocess call to git to test this.

**Pull request merged**
