### PR TITLE
Line continuation in implicit subproc

### PR DESCRIPTION
**Pull request by scopatz**
This should address #693 #893 and #1704, and is probably waaay overdue.

### CODE REVIEW

**Comment by laerus** [comment]
works with prompt_toolkit

readline raises exception
```
laerus@hive$ echo test \
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/laerus/src/xonsh/xonsh/execer.py", line 164, in _parse_ctx_free
    debug_level=(self.debug_level > 2))
  File "/home/laerus/src/xonsh/xonsh/parsers/base.py", line 335, in parse
    tree = self.parser.parse(input=s, lexer=self.lexer, debug=debug_level)
  File "/home/laerus/src/xonsh/xonsh/ply/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/laerus/src/xonsh/xonsh/ply/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/laerus/src/xonsh/xonsh/ply/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/home/laerus/src/xonsh/xonsh/parsers/base.py", line 2694, in p_error
    column=p.lexpos))
  File "/home/laerus/src/xonsh/xonsh/parsers/base.py", line 466, in _parse_error
    raise err
  File "<string>", line None
SyntaxError: <xonsh-code>:1:5: ('code: test',)
echo test \
     ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laerus/src/xonsh/xonsh/base_shell.py", line 407, in compile
    locs=None)
  File "/home/laerus/src/xonsh/xonsh/execer.py", line 109, in compile
    transform=transform)
  File "/home/laerus/src/xonsh/xonsh/execer.py", line 79, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/home/laerus/src/xonsh/xonsh/execer.py", line 182, in _parse_ctx_free
    line, nlogical = get_logical_line(lines, idx)
  File "/home/laerus/src/xonsh/xonsh/tools.py", line 361, in get_logical_line
    line = line[:-1] + lines[idx]
IndexError: list index out of range
```

**Comment by scopatz** [comment]
Ok, I have added a fix for readline. However, this uncovered another bug, that seems to be independent of the shell and is probably in the parser somewhere. The first two cases lack the whitespace that they should have.  

```console
scopatz@artemis ~ $ echo hello \
`·.,¸,.·*¯`·.,¸,.·* world
`·.,¸,.·*¯`·.,¸,.·* 
helloworld
scopatz@artemis ~ $ ![echo hello \
`·.,¸,.·*¯`·.,¸,.·* world]
`·.,¸,.·*¯`·.,¸,.·* 
helloworld
scopatz@artemis ~ $ ![echo hello 
`·.,¸,.·*¯`·.,¸,.·* world]
`·.,¸,.·*¯`·.,¸,.·* 
hello world
```

I still think this is better than what is on master, so if you want to merge this in, we can open up another issue for this error.

**Comment by laerus** [comment]
merging, thank you @scopatz!

**Comment by Cheaterman** [comment]
Well... `xonsh/0.9.17.dev2` here, and this is broken again.

Also @scopatz the examples you showed above now work a bit differently - to get line continuation, I was forced to use both explicit subproc mode `![]` AND to end each line with ` \` (space + backslash). Maybe the backslash wasn't necessary but EOL whitespace is a nono in my book :-)

Thanks!

**Comment by gforsyth** [comment]
@cheaterman, can you please open a new issue?

**Comment by Cheaterman** [comment]
Good idea @gforsyth, thanks! Done at https://github.com/xonsh/xonsh/issues/3532 .

**Pull request merged**
