### PR TITLE
chore: bring back codcoverage report

### PR DESCRIPTION
**Pull request by jnoortheen**
Also fix `run-tests.xsh test` accepting pytest arguments

### CODE REVIEW

**Comment by jnoortheen** [comment]
For some reason the coverage makes the tests slower inside CI machine. In my system it doesn't had such significant effect.

**Comment by jnoortheen** [comment]
> For some reason the coverage makes the tests slower inside CI machine. In my system it doesn't had such significant effect. Maybe I will try without conda and directly use the system's interpreter. Let's see if that brings any speedup. Here is the capture of current timings
> image

seems like there is not much room to improve with setup-python

**Comment by jnoortheen** [comment]
@gforsyth @scopatz any blockers ?

**Comment by gforsyth** [comment]
I was trying to figure out who removed code coverage in the first place so I could check why.

Turns out it was me 4 years ago 😆 -- anyway, then it was a bunch of noise because it never worked properly and no one wanted to get it fixed up.  Looks like you have, @jnoortheen so I'm happy to merge this in.

Thanks for getting it working!

**Comment by jnoortheen** [comment]
the anti-climax moment :)

**Pull request merged**
