### PR TITLE
fix for #1667, cd <singleCharacter> fails

### PR DESCRIPTION
**Pull request by bobhy**
My fault, here's a fix for #1667, sorry @astronouth7303.

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks @bobhy! There seems to be some legitimate Flake 8 failures here after the timeout issue...

**Comment by bobhy** [comment]
Fixed 'em, glad to oblige.  Ummm, not my code?  Last changed by @melund https://github.com/xonsh/xonsh/commit/22f86f69ee138b6381960322a97e6e34d9d15e3c#diff-98d8bac556553c35e711ef3a74387f4e

**Comment by melund** [comment]
True. Sorry for that.  I better start to use an editor that strips trailing whitespaces.

**Comment by scopatz** [comment]
Thanks @bobhy!

**Pull request merged**
