### PR TITLE
updates to webconfig

### PR DESCRIPTION
**Pull request by scopatz**
No news item needed

### CODE REVIEW

**Comment by laloch** [comment]
Black wants to reformat 23 files :scream:

**Comment by scopatz** [comment]
That's weird! This doesn't touch those at all.  I guess something changed in black.  I'll put in another PR

**Comment by laloch** [comment]
Thanks @scopatz!

**Comment by scopatz** [comment]
Thanks! It looks like there was an update to black 1 hr ago, which I guess changed the output results: https://github.com/psf/black/releases/tag/20.8b

**Pull request merged**
