### PR TITLE
Uptime

### PR DESCRIPTION
**Pull request by scopatz**
Hopefully this addresses some of the issue brought up in #2148

### CODE REVIEW

**Comment by scopatz** [comment]
OK, I think this is good to go. The mac failures are not correct. If you open it up you'll see that it passes.

**Comment by mitnk** [comment]
amazing! that's a lot of code for getting the boot time :) 

For Unix-like systems, could we just Popen('uptime') and parse output get the result?

**Comment by scopatz** [comment]
> For Unix-like systems, could we just Popen('uptime') and parse output get the result?

We could, but subprocess is relatively slow compared to just reading from `/proc/stat`. Also if uptime is not installed for some reason, it would fail. I think that this is a better approach ultimately, even if it is a lot of work for one number :)

**Comment by melund** [comment]
Yes. Pretty cool. I will restore the json files I delete and see if they are now cleaned up.

**Comment by melund** [comment]
It fixes the GC for me. Cool.

**Comment by scopatz** [comment]
Thanks @melund!

**Pull request merged**
