### PR TITLE
callable default skips validation

### PR DESCRIPTION
**Pull request by scopatz**
Minor quality of life improvement for env var registration

### CODE REVIEW

**Comment by scopatz** [comment]
@dotsdl - what is the need for the `is_callable_default`? I think I might have missed something here

**Comment by scopatz** [comment]
Is it just to make it more explicit?

**Comment by scopatz** [comment]
Oh I see, we pass in the env

**Comment by daniel-shimon** [comment]
This is great!
Could you add a test to make sure the validation runs correctly with `pytest.raises`?
Once in `getitem` with a default and once in `setitem`

Another good test might be that the default function only runs once after multiple `getitem`s

**Comment by scopatz** [comment]
Thanks for the review @daniel-shimon! Shouldn't those test you suggested be covered by other tests in the suite?  This really just affects the logic of `register()`

**Comment by scopatz** [comment]
I have resolved the conflicts with master and I think that this is ready for review @xonsh/xore!

**Comment by daniel-shimon** [comment]
> Thanks for the review @daniel-shimon! Shouldn't those test you suggested be covered by other tests in the suite?  This really just affects the logic of `register()`

I'm not sure about other tests, but these changes do affect the scenarios I suggested to test

**Comment by anki-code** [comment]
hi! Maybe there is a real life example of using callable default? It will be great to look at it.

**Comment by jnoortheen** [comment]
@gforsyth would you be kind to check this one too?

**Comment by gforsyth** [comment]
Thanks for the ping @jnoortheen !

Thanks for putting this in @scopatz and thanks @daniel-shimon for the review!

**Pull request merged**
