### PR TITLE
test fix for first redirect on windows

### PR DESCRIPTION
**Pull request by scopatz**
FOr #2469

### CODE REVIEW

**Comment by melund** [comment]
Thanks for taking a look at this @scopatz 

It doesn't seem to fix the problem though. 

```
C:\Users\mel\Documents\xonsh>xonsh
snail@sea ~\Documents\xonsh redirwin
$ $XONSH_SHOW_TRACEBACK = True
snail@sea ~\Documents\xonsh redirwin
$ echo "hello world" > test3.txt
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "C:\Users\mel\Documents\xonsh\xonsh\base_shell.py", line 328, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "C:\Users\mel\Documents\xonsh\xonsh\codecache.py", line 68, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "C:\Users\mel\Documents\xonsh\xonsh\built_ins.py", line 877, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "C:\Users\mel\Documents\xonsh\xonsh\built_ins.py", line 813, in run_subproc
    command = HiddenCommandPipeline(specs)
  File "C:\Users\mel\Documents\xonsh\xonsh\proc.py", line 1767, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "C:\Users\mel\Documents\xonsh\xonsh\built_ins.py", line 502, in run
    p = self._run_binary(kwargs)
  File "C:\Users\mel\Documents\xonsh\xonsh\built_ins.py", line 512, in _run_binary
    p = self.cls(self.cmd, bufsize=bufsize, **kwargs)
  File "C:\Users\mel\Documents\xonsh\xonsh\proc.py", line 552, in __init__
    os.set_handle_inheritable(self.stdout_fd, False)
OSError: [WinError 6] The handle is invalid
snail@sea ~\Documents\xonsh redirwin
$ echo "hello world" > test4.txt
snail@sea ~\Documents\xonsh redirwin
```

**Comment by santagada** [comment]
@scopatz want to try to fix this again?

**Comment by santagada** [comment]
just pinging people if someone wants to fix this, if not I will try to fix it

**Comment by scopatz** [comment]
I forgot where I was with this, so any help would be most welcome!

**Comment by santagada** [comment]
I don't know either, but apparently your fix didn't work. I think now you can run windows core on a docker container but the easiest way to get something going is the microsoft IE testing images for virtualbox: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by robdefriesse** [comment]
I noodled with the v0.6.7 source and I think I have a diagnosis.  The fix should be simple.  The call to os.set_handle_inheritable expects a Windows handle, but it is being passed a posix file descriptor:

proc.py line 551:
        if ON_WINDOWS and stdout is not None:
            os.set_handle_inheritable(stdout.fileno(), False)

fileno() returns a posix file descriptor which is a small integer.  The method os.set_inheritable() does accept a posix file descriptor.  The fix is to simply replace set_handle_inheritable to set_inheritable:

        if ON_WINDOWS and stdout is not None:
            os.set_inheritable(stdout.fileno(), False)

I have tried this fix and it corrected the problem for the limited use cases I checked.  For example, this did not work before, but did work after my fix:

echo Test >file

If you prefer to us set_handle_inheritable, the function msvcrt.get_osfhandle(fd) will allow you to obtain the handle.  (Link to the documentation below.)

I will submit a fix for this if you wish.  However, I am unfamiliar with git, so I'd be the proverbial chimpanzee with a loaded revolver.  I think it will be as easy for you to fix as it would be to review my fix.

I hope this helps. 


For additional context:

In the Python-3.6.5 source code you will find this in Modules/posixmodule.c line 11185:

```
static PyObject *
os_set_handle_inheritable_impl(PyObject *module, intptr_t handle,
                               int inheritable)
/*[clinic end generated code: output=021d74fe6c96baa3 input=7a7641390d8364fc]*/
{
    DWORD flags = inheritable ? HANDLE_FLAG_INHERIT : 0;
    if (!SetHandleInformation((HANDLE)handle, HANDLE_FLAG_INHERIT, flags)) {
        PyErr_SetFromWindowsErr(0);
        return NULL;
    }
    Py_RETURN_NONE;
}
```

Links:

https://docs.python.org/3.5/library/os.html#inheritance-of-file-descriptors
https://docs.python.org/3.0/library/msvcrt.html#file-operations

**Comment by scopatz** [comment]
Ahh thanks @robdefriesse!  Would you mind putting in a PR? That would help us a ton. Thanks!

**Comment by robdefriesse** [comment]
Of course.  It will take some time.  I am unfamiliar with git, so I need to get myself up to speed.

**Comment by robdefriesse** [comment]
I think I started out wrong.  I cloned your repository to my local machine and made the changes in a branch: code, regression test, and changelog info.  Now I'm not allowed to push my repository back to yours.  Was I supposed to fork or something?  Is the flow you use documented somewhere?

Thank you.

**Comment by santagada** [comment]
@robdefriesse take a look at https://help.github.com/articles/creating-a-pull-request/ I think they have answers to your questions... AFAIK you need to fork and then point your local disk branch to your fork, then you can push and create a PR. but the documentation seems pretty well written and might have a shortcut.

**Pull request closed without merging**
