### PR TITLE
potential fix for jupyter

### PR DESCRIPTION
**Pull request by scopatz**
I think we were redirecting too much. See #2099.

### CODE REVIEW

**Comment by gforsyth** [comment]
Hey @scopatz -- I did this, too, and it definitely makes things work again, which is good, but should subprocess commands print to Outputs or stdout?  I can't remember the old behavior

**Comment by scopatz** [comment]
I think the intended behaviour is outputs, right?  Like you wouldn't want to have to go and look at the terminal if you are in the notebook. Also, this is handled by ipykernel internally since they are the ones redirecting stdout & stderr to outputs. We are just reporting it back.

**Comment by scopatz** [comment]
Also, great minds think alike :)

**Comment by gforsyth** [comment]
Right, so should the outputs here have `Out[1]`, `Out[2]`, `Out[3]` by them?

2017-01-26-170513_1071x314

Obviously returning the jupyter kernel to any level of usability is better than the current state.

**Comment by scopatz** [comment]
Ahh right.  Let me dig into that.

**Comment by scopatz** [comment]
Ok, I couldn't figure out how to get `Out` back.  I am not sure it was ever there, actually.  I think it has something to do with changing `stream` to a different message type, but I couldn't figure out which message was the appropriate one (the [docs didn't help much](http://jupyter-client.readthedocs.io/en/latest/messaging.html)) and looking through IPython and ipykernel I couldn't find what value was really being set. @Carreau probably knows ;).  But for the time being, I think this is an improvement.

**Comment by Carreau** [comment]
Hum, haven't touched that in a while. I'll have a look.

**Comment by scopatz** [comment]
I think this is worth merging in even without the Out fix for the time being.

**Comment by melund** [comment]
On windows, I don't see any output. But the problem is the same on Master. 

However, this branch does fix `which ls`, which didn't work on master. So I am OK with merging..

image

**Comment by scopatz** [comment]
Yeah I think the Out entries have always been missing.

**Comment by melund** [comment]
> Yeah I think the Out entries have always been missing.

I believe you are right. But the output itself is missing on Windows :( 

This PR still fixes some issues with `which ls` failing. So I think it is OK to merge if you have no ideas why it is misbehaving on Win. Then I will create a new separate issue for it.

**Comment by scopatz** [comment]
Yeah, I think creating a separate PR would be best

**Comment by scopatz** [comment]
Err, a separate issue.

**Comment by melund** [comment]
Good. I will merge

**Pull request merged**
