### PR TITLE
Captured subproc $() returns lines 

### LINKED ISSUE #3924: Re-thinking the command substitution operators
# Abstract

This is a proposal for re-designing the command substitution (a.k.a command pipelines) mechanisms in xonsh.

A simple example for command substitution in bash:
```bash
echo hi $(whoami)
```

#### NOTE: This example is very basic and naïve. Please look at the usage examples below.

# Motivation

Command substitutions have a range of usage scenarios, and we want them all to be easy and concise.
These usages differ by two factors - stripping and splitting.

* Stripping: Most unix and windows cli commands append newlines to their output, which we might want to strip.
* Splitting: A program might output multiple values separated by spaces, newlines, tabs or other tokens, which we might want to split to multiple arguments.

#### Some of the more common combinations aren't easily expressed in xonsh currently.

Examples for each scenario (commands with the corresponding output format):

|                          | Strip trailing newline | No stripping | Strip all whitespace |
| ------------------------ | ---------------------- | ------------ | -------------------- |
| No splitting             | `whoami`, `uname`, `hostname`, `nproc` | `echo -n ... \| wc -l` | |
| Splitting by newline     | `find`, `git branch/log/diff --name-only` | | |
| Splitting by whitespace  | _Meaningless_ | _Meaningless_ | `groups`, `yay -Qdtq`, `pkg-config` |
| Splitting by other token | `parsing /etc/passwd` | | |

## Current xonsh behavior

| Operator | Strip | Split | Return value | Mode |
| -------- | ----- | ----- | ------------ | ---- |
| `$()` | No | No | String | Both |
| `!()` | No | No | CommandPipeline object | Python |
| `@$()` | Whitespace | Whitespace | List of args | Command |
| `$[]` | No | No | None | Both |
| `![]` | No | No | CommandPipeline object | Both |

## Current state and comparisons with other shells

The **first three** options are the more common ones according to our current examples.

| Strip                 | Split          | Xonsh | Bash | Zsh | Fish |
| --------------------- | -------------- | ----- | ---- | --- | ---- |
| **Trailing newlines** | **No**         | `@($(CMD).rstrip('\n'))` | - | `"$(CMD)"` | - |
| **Trailing newlines** | **Newlines**   | `@($(CMD).splitlines('\n'))` | - | - | `(CMD)` |
| **Whitespace**        | **Whitespace** | `@$(CMD)` | `$(CMD)` | `$(CMD)` | `(CMD \| string split ' ' --no-empty)` |
| No                    | No             | `$(CMD)` | - | - | - |
| Whitespace            | No             | `@($(CMD).strip())` | `"$(CMD)"` | - | - |
| No                    | Newlines       | `@($(CMD).split('\n'))` | - | - | - |
| Whitespace            | Newlines       | `@($(CMD).strip().split('\n'))` | - | - | `(CMD \| string trim \| string split ' ' --no-empty)` |
| Trailing newlines     | Token          | `@($(CMD).rstrip('\n').split(TOKEN))` | - | - | `(CMD \| string split TOKEN --no-empty)` |
| No                    | Token          | `@($(CMD).split(TOKEN))` | - | - | - |
| Whitespace            | Token          | `@($(CMD).strip().split(TOKEN))` | - | - | `(CMD \| string split TOKEN --no-empty \| string trim)` |

#### NOTE: As far as I can tell, none of the shells has an option to only strip the **single** last newline.

# Current proposals

## [XEP-2](https://github.com/anki-code/xonsh-operators-proposal/blob/main/XEP-2.rst) (by @anki-code)

See details and examples in the XEP - https://github.com/anki-code/xonsh-operators-proposal/blob/main/XEP-2.rst.
In short:

Mode | Current | Proposed
-- | -- | --
Python | $() returns output string. | $() returns CommandPipeline object.
Subproc | $() returns output string. | $() returns list of lines from output without trailing new line symbol.
Python | $[] returns None. | $[] returns HiddenCommandPipeline object.
Both | !() exists. | ~!() removed.~ UPD: discussion.
Both | ![] exists. | ~![] removed.~ UPD: discussion.

`CommandPipeline` (CP) class changes:

* Add str representation the same as `CP.out`.
* Remove trailing new lines in `CP.out`, `CP.lines` and `CP.__iter__`.
* Add all string methods i.e. the `$().split()` will return `CP.out.split()` that is IFS analogue in fact.
* Add all string methods for lines i.e. `$().lines_find(txt)` will return `[l.find(txt) for l in CP.lines]`.

## This issue's initial proposal with influence from @adqm

* Strip trailing newline in `$()`.
* Strip trailing newlines in `!().__iter__` (i.e. use `.splitlines()`).

### Pros:

* No type-changing back-compatibility issues.
* `!()` is consistantly iterated through.
* Splitting by whitespace remains unchanged (`@$()`).
* The complete output is still available easily via `!().out`.

### Cons:

* Python code that uses `$()` might need to change if the trailing newline is important.

## https://github.com/laloch/xonsh/commit/98363df (by @laloch)

Add `@$[]` operator to split by newlines.

### Pros:

* Completely backwards-compatible.

### Cons:

* More arbitrary syntax.
* Doesn't really extend `@$()` and `$[]` in a meaningful way.
* Still doesn't solve the most common `No split, Strip newline` scenario.

# Rejected proposals

## Initial proposal in this issue

Run `.rstrip('\n')` in `$()`.

### Cons:

* No easy way to use the complete output if a user needs it.

### Cons:

> this is a case where configuration would be bad, because xonsh scripts would either run or fail based on how the environment was configured.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### PR DESCRIPTION
**Pull request by anki-code**
#### UPD: The proposal description moved to 
[XEP-1 in xonsh-operators-proposal](https://github.com/anki-code/xonsh-operators-proposal)

### Changes

| Before | After |
|---|---|
|`$()` returns output string | `$()` returns list of lines from output |
| `!()` raises error in subproc mode | `!()` returns output string in subproc mode - the same as `$()` before |

### Why

It allows to write subproc commands clear and beauty - without explicit stripping:

| Before | After |
|---|---|
| `cat @($(echo filename).strip())` | `cat $(echo filename)` |
| `du -sh @$(ls)` - error around spaces in names | `du -sh $(ls)` |
|  `make -j @($(nproc).strip())` | `make -j $(nproc)` |
| `[f for f in $(ls).rstrip().split('\n')]` | `[f for f in $(ls)]` |
| `echo !(echo echo)` raises error | `echo !(echo echo)` works |

### Consistency
Current operators (xonsh 0.9.24):
|Operator| Subproc | Python |
|--------|---------|--------|
|`$()`   | output | output |
|`!()`   | - | object |
|`@(!())`   | output | - |
|`$[]`   | - | None |
|`![]`   | - | object |
|`@$()`  | splitted output | - |
|`@()`   | python susbstitution | - |

Current operators (xonsh 0.9.24) have a lack of consistency:
| Low: no splitting | Medium: lines splitting | High: full splitting |
|---|---|---|
| `$()` | - | `@$()` |

What changed:
|Operator| Subproc | Python |
|--------|---------|--------|
|`$()`   | ✔️ output lines | ✔️ output lines |
|`!()`   | ✔️ output | object |

Why `@$()` is not working for this?
* `@$()` already has behavior the same as bash splitting. The line `123\n1 2 3` becomes `['123','1','2','3']` that is very special and not be used for file names and another lines that contains spaces.

Why `$()` will be changed?
* `$()` operator is common and well known as command output substitution in many shells.
* and `!()` already works similar as suggested in PR in python mode: `echo @(!(echo 123))` returns `123`. Using it in subproc mode to getting pure output is consistent with python mode.

After this changes the operators logic becomes complete and has consistency::
| Low: no splitting | Medium: lines splitting | High: full splitting |
|---|---|---|
| `!()` | `$()` | `@$()` |

### Install and try
```
pip install -U git+https://github.com/anki-code/xonsh.git@captured_subproc
xonsh --no-rc
du -sh $(ls ~/.xonshrc)
cat /etc/passwd | grep $(whoami)
```

### Some examples
```python
repr($(echo 123))
# ['123']

repr(!(echo 123))
# CommandPipeline object

echo 123 > filename
cat $(echo filename)   # Runs: cat filename
# 123

# count of characters in original text
echo -n !(head filename) | wc -c

# substitution becomes clean
name = $(whoami)  # ['user']
cat /etc/passwd | grep @(name)

# getting a name string
name, = $(whoami)
name = str($(whoami))
name = $(whoami)[0]
name = $(whoami).pop()
```

### What about splitting the lines in `$()`?
The algorithm of splitting lines is Python built in. Nothing special:
```python
' 123\n321 \n'.splitlines()
#[' 123', '123 ']

echo -n ' 123\n321 \n' > qwe
$(cat qwe)
# [' 123', '321 ']
```

### What will break and how to fix:

<table>
<thead>
<tr>
<td>Error</td>
<td>Fix</td>
</tr>
</thead>

<tbody>

<tr>
<td valign="top" >
Using <code>$()</code> as a string argument but it will be a list after PR. <br><br>
<code>json.loads($(curl https://api.github.com/orgs/xonsh))</code><br>
TypeError: the JSON object must be str
</td>
<td valign="top" >
Replace <code>$()</code> to <code>!()</code><br><br>
<code>json.loads(!(curl https://api.github.com/orgs/xonsh))</code><br>
or <code>json.loads(str($(curl https://api.github.com/orgs/xonsh)))</code><br>

</td>
</tr>

<tr>
<td valign="top" >
Call string function.<br><br>
<code>$(whoami).strip()</code><br>
<s>AttributeError: 'OutputLines' object has no attribute 'strip'</s>
</td>
<td valign="top" >
✅ The lines wrapped into <code>OutputLines</code> class that have <code>list</code> behavior with additional <code>str</code> functions. And now you can call <code>$().strip()</code> like before.

</td>
</tr>

</tbody>

</table>

### Additional bonus

The lines wrapped into `OutputLines` class that have `list` behavior with additional `str` and  `lines_<str function>`functions. And now you can:
```python
$(head /etc/passwd).lines_split(':')
#[['root', 'x', '0', '0', 'root', '/root', '/bin/bash'],
# ['daemon', 'x', '1', '1', 'daemon', '/usr/sbin', '/usr/sbin/nologin']]

$(head -n 2 /etc/passwd).find('daemon')
# 32

$(head -n 2 /etc/passwd).lines_find('bin')
# [23, 26]  # positions of bin in every line
```

Closes #3924

### CODE REVIEW

**Comment by anki-code** [comment]
@scopatz before I will fix the tests could you please give complete feedback about the approach and the code. 

I tried to make the changes that should be understandable. For example I created distinct `_strip` version of `subproc_captured_stdout` function to point the behaviour explicitly and:
* Users who are using `__xonsh__.subproc_captured_stdout` api will not facing with changes. 
* Users who are using `@($().strip())` also will not facing

**Review by laloch — CHANGES_REQUESTED** [review]
I think before breaking every single script on the planet, we should first reach a consensus on how those operators should behave instead of making hasty naive changes. Let's have a serious discussion on the matter first.

**Comment by anki-code** [comment]
> I think before breaking every single script on the planet,

Could you please give the real example from your project that will be broken by this change?

**Comment by anki-code** [comment]
I believe the way to support ugly design because it used is not so good point. We should be free for changes because xonsh is a unique great concept and should be agile to evolution. *The question is* how to do this changes smoothly.

**Comment by anki-code** [comment]
Also I want to be clear in "xonsh vs sh" topic. I'm not the sh shells lawer. But I believe that there is minimal basic common used and well known sh shells functionality that works and if xonsh can have the same behavor without cons it more and more good to xonsh promotion and the progress than to create new distinct xonsh/python-specific solution.

In this case and in this PR is the good example. We created very clean solution that looks clean from sh and from python and from xonsh point of views. One barier - is backwards compatibility.

I don't want to discuss of filisophy the operators in xonsh. In this PR the behavior of operators extremely clear. I want to discuss this PR, solution behind it and how to release it smoothy with backwards compatibility.

**Comment by anki-code** [comment]
New point from chat:
> unfortunately this still doesn't behave like bash's $()
> My use case for $() is for the following command:
> yay -Rcs $(yay -Qdtq). This command (on arch linux with yay installed) makes each line of the output of $(yay -Qdtq) an argument for yay -Rcs, but xonsh doesn't seem to split arguments on newlines/spaces

@scopatz @laloch if we're thinking about change the behavior may be we'll think about making the same behavior of `$()` as bash completely? The `!()` will be for working with pure output.

**Comment by laloch** [comment]
> New point from [chat](https://gitter.im/xonsh/xonsh):
> 
> > unfortunately this still doesn't behave like bash's $()
> > My use case for $() is for the following command:
> > yay -Rcs $(yay -Qdtq). This command (on arch linux with yay installed) makes each line of the output of $(yay -Qdtq) an argument for yay -Rcs, but xonsh doesn't seem to split arguments on newlines/spaces
> 
> @scopatz @laloch if we're thinking about change the behavior may be we'll think about making the same behavior of `$()` as bash completely? The `!()` will be for working with pure output.

The above completely proves my point. It's exactly why I say that we should think first and make changes once we know what we want to achieve. This is not playing with colors anymore. This affects the core functionality. Good software is design-driven and there's no design in this whatsoever.

> I don't want to discuss the philosophy of operators in xonsh.

But you should!

> In this PR the behavior of operators extremely clear.

No, it's not. What about leading and trailing whitespace around the `$()`? Can you do `mkdir /tmp/$(whoami)/garbage`? You can't? Why? Is it the desired behavior?

**Comment by anki-code** [comment]
@laloch 

> But you should!

1. When I told that don't want to philosophy discussion I mean pattern when I get questions from maintainers more then solutions (with code examples) and when I should think about all entirely world but I have clear vision of local solution. I love thinking about world when I have no clear solution. But not in this case. You have more experience and more wide vision I understand and your help is appreciated. But in case the questions becomes blockers for progress it's just wasing time.

2. Are you agree that `@($().strip())` is ugly? Are you agree that new user will ask you how to do `cmd $(cmd)` you will feel a bit hasiatate when recommend do `cmd @($(cmd).strip())`?

> This is not playing with colors or self-promotion anymore. 

3. Haha, yeah I have many PRs around this. But among 68 PRs there are others.. 

> No, it's not. What about leading and trailing whitespace around the $() operator? Can you do mkdir -p /tmp/$(whoami)/garbage? You can't? Why? Is it the desired behavior?

4. Thanks for concrete example. I see that this is not working in current xonsh version now and not about this PR. I think it should work.

> The above completely proves my point.

5. Sorry but no. This means only that we should collect all cases of using `$()` and choose the best design. I suggest to make `$()` operator the same as bash.

**Comment by anki-code** [comment]
@laloch as I understand there in the history of this question nobody suggested using `!()` for pure output. And this was the cause why xonsh original `$()` behavior was strong. But now we have new great idea with using `!()` in subproces and this change the game. I'm still open to understand why suggested logic is unclear. Your example with `mkdir /tmp/$(whoami)` is not working in the current thersion of xonsh but should and it's not an argument why `$()`+`!()` logic is unclear.

**Comment by anki-code** [comment]
@laloch @scopatz I want to consolidate the current question:

❓ Are there a causes (backward support excluded) why we can't do this:
* `$()` = `output.strip().split('\n')`
* `!()` = `output`

As you can see I'm not doing `[o.strip() for o in output.split('\n')]` to avoid bash magical behaviour that don't like @scopatz . User can do it manually if he want.

**Comment by anki-code** [comment]
@laloch @scopatz I have new parallel with python:
```python
echo -n ' 123\n321 \n' > qwe

with open('qwe') as f:
      for l in f:
          print('*',repr(l))
```
How much lines we will have? 3 or 2? 2!
```
* ' 123\n'
* '321 \n'
```
So the logic of `$()` could be the python-way:

* `$()` = `(output[:-1] if output[-1] == '\n' else output).split('\n')`
* `!()` = `output`
* `@$()` = bash-like splitted output

**Comment by anki-code** [comment]
I've updated the description of the PR and it looks very delicious solution.
* @laloch happy because no rude stripping
* @scopatz happy because the logic is consistent between three operators
* @anki-code happy because it solve the main use cases beauty and people-oriented
* @daniel-shimon happy because it works!

=)

**Comment by anki-code** [comment]
xore! @gforsyth @AstraLuma @Carreau @mitnk @BYK @adqm @melund @jb-leger

Please take a look at the first message of the thread. The description, motivation and examples are there!

**Comment by daniel-shimon** [comment]
@anki-code so does `$()` return a list in python mode? This means stuff like `name = $(whoami)` won't work at all, I'm not sure that's a good thing

**Comment by anki-code** [comment]
>  so does $() return a list in python mode? This means stuff like name = $(whoami)

Yes, the same behavior. 
At this time in xonsh you should do `name = $(whoami).strip()`
After this PR many short variants:
```
name, = $(whoami)
name = $(whoami)[0]
name = $(whoami).pop()
```

**Comment by anki-code** [comment]
@scopatz (and xore), before I will fix the tests, review the docs and do my best to release this could you please give complete feedback:

1. Are you ready to change the default behavior of `$()`?

2. If YES, could you share the thoughts how it could be achieved smooth? How it will be connected to xonsh versions? We have xonsh 0.9 now. I suggest to release 0.10.0 with this changes.

3. If NO:
3.1. What I should to do? I should wait for comments during weeks, months and may be years like in PostgreSQL community?
3.2. Could it be released soon if I create environment variable that change the default behavior of subproc_captured_stdout? Two modes: "output" and "output lines".

4. If strongly NO. Why you think that current `$()` is good? Why you don't want to change it?

5. I created table with all operators (@scopatz asked) - https://github.com/xonsh/xonsh/issues/3924#issuecomment-716112320, and I've added examples and more description to the first message (https://github.com/xonsh/xonsh/pull/3926#issue-509393484) as you can see the changes is pretty clear. Could you give me concrete cases/examples/problems with this?

*PS: I'm working with xonsh from this PR two days and I'm incredible happy to avoid `strip` and do simple things simple and clean.*

**Comment by scopatz** [comment]
Hi All, I think this conversation has gotten a little heated. My opinion is that we were discussion options in #3924. Part of the issue with how we have been discussing these things is that we don't really have a formal enhancement proposal process (like PEPs) where we can review and discuss these kinds of major changes.  If someone wanted to start setting up a XEP process, that would be very welcome.

**Comment by thisch** [comment]
> ```python
> name = $(whoami).rstrip()  # 'user\n' -> 'user'
> cat /etc/passwd | grep @(name)
> ```

I want to mention that for this to work `.rstrip()` is not needed in the current xonsh version, because when `grep` is used in xonsh, newlines seem to be ignored. Maybe this should be reported as a bug.

`cat "name,address" | grep "name\n"` returns a match in xonsh, but no match in a different shell.

**Comment by anki-code** [comment]
Folks! Your help is needed. Please:
1. read the description of this PR (https://github.com/xonsh/xonsh/pull/3926#issue-509393484)
2. Optional: install it as described and make few tests.
3. If you like the changes please react with "thumb up" emoji 
4. If you see the problems please do step 2 and then write a short comment here.

This change is major for xonsh history and your review will help to have clear vision.

@blahgeek  @bobhy  @CJ-Wright  @santagada  @kseistrup  @gforsyth  @aig787  @virusbb001  @rbrewer123  @dyuri  @Eadaen  @chronitis  @GuillaumeLeclerc  @nicfit  @dannysepler  @Jitsusama  @vaaaaanquish  @dotsdl  @carmenbianca  @Granitosaurus  @derekbrokeit  @con-f-use  @VHarisop  @JohnLunzer  @moigagoo  @jnoortheen  @krader1961  @funkyfuture  @cryzed  @eode

**Comment by anki-code** [comment]
Folks! Your help is needed. Please:
1. read the description of this PR (https://github.com/xonsh/xonsh/pull/3926#issue-509393484)
2. Optional: install it as described and make few tests.
3. If you like the changes please react with "thumb up" emoji 
4. If you see the problems please do step 2 and then write a short comment here.

This change is major for xonsh history and your review will help to have clear vision.

@daniel-shimon  @cafehaine  @justinmoon  @jonathanslenders  @das-g  @cjrh  @ahundt  @jaraco  @knowsuchagency  @willsALMANJ  @zajaczajac  @wendellwt  @oprypin  @michaelaye  @bskinn  @Will-W  @youtux  @tamuhey  @koehlma  @traverseda @t184256  @rtpg  @ngoldbaum  @jmcrawford45  @jeremydonahue  @drmikecrowe  @aweltsch  @Siecje  @JakeHedman  @webmeister  @refi64  @mdraw  @mbollmann  @juanpabloaj  @jamiees2  @anula  @anddam  @Uglemat  @Terrance  @DNGros  @Achimh3011  @xsteadfastx  @techtonik  @seanfarley  @mariusvniekerk  @mardukbp  @kalekundert  @justcalamari  @imomaliev  @goodboy  @asmeurer  @WouldYouKindly  @StreakyCobra  @SirNickolas  @MrQubo  @ErickTucto  @BoboTiG  @Ad115  @AaronV77  @74th

**Comment by anki-code** [comment]
Folks! Your help is needed. Please:
1. read the description of this PR (https://github.com/xonsh/xonsh/pull/3926#issue-509393484)
2. Optional: install it as described and make few tests.
3. If you like the changes please react with "thumb up" emoji 
4. If you see the problems please do step 2 and then write a short comment here.

This change is major for xonsh history and your review will help to have clear vision.

@JakeHedman  @webmeister  @refi64  @mdraw  @mbollmann  @juanpabloaj  @jamiees2  @anula  @anddam  @Uglemat  @Terrance  @DNGros  @Achimh3011  @xsteadfastx  @techtonik  @seanfarley  @mariusvniekerk  @mardukbp  @kalekundert  @justcalamari  @imomaliev  @goodboy  @asmeurer  @WouldYouKindly  @StreakyCobra  @SirNickolas  @MrQubo  @ErickTucto  @BoboTiG  @Ad115  @AaronV77  @74th

**Comment by traverseda** [comment]
What? Why am I getting pinged for this? Don't send out unsolicited mass emails.

**Comment by anki-code** [comment]
> name = $(whoami).rstrip()  # 'user\n' -> 'user'
>  cat /etc/passwd | grep @(name)
> I want to mention that for this to work .rstrip() is not needed

@thisch thanks for your attention! Yeah, it's just an example. It could be another:
```
# old xonsh subproc
fname = $(ls | head -n 1)
du -sh @(fname)
# du: cannot access '111'$'\n': No such file or directory
```

**Comment by anki-code** [comment]
@traverseda because you're one of xonsh contributor and the message with mention has motivation.

**Comment by traverseda** [comment]
There are a lot of questions that are going to be really important to the community, but I don't think we should have a popularity contest or try to vote on every single decision.

It looks like there was a lot of discussion already over here: https://github.com/xonsh/xonsh/issues/3924

Just keep talking through the issues, the people in charge of this repo are probably reasonable and if they're not you can always find some people who agree with you and fork the project. Hell, you could probably find some way to make this problem solvable with extensions.

Don't try to get a random mob of people to make your technical arguments for you.

**Comment by anki-code** [comment]
> It looks like there was a lot of discussion already over here

No. In this questions there is a lack of feedback but it's core question.

> Hell, you could probably find some way to make this problem solvable with extensions.

No. This is core functionality.

> Don't try to get a random mob of people to make your technical arguments for you.

Not random. Only contributors.

@traverseda I've got your opinion and agree. Sorry.

**Comment by gforsyth** [comment]
I've locked this PR to avoid additional message being sent to everyone who was @'d in the previous messages.  

@anki-code -- everyone who maintains `xonsh`, works on `xonsh`, contributes to `xonsh`, and uses `xonsh` is a volunteer.  You can ask for the maintainers attention, but there are no guarantees about how we will / can allocate our time and attention.  All of us have jobs, all of us have responsibilities that lay outside of this project.

I think there are reasonable usage questions to be discussed that you and others have raised earlier in this PR and elsewhere, but those discussions cannot continue in this thread with many 10s of people being pinged on every message when they have not signed up to receive those notifications.

Please don't mass `@` people again in an issue or PR.

For continuing conversation regarding the changes proposed above, those should go to #3924

**Comment by laloch** [comment]
Closed per the author's request (#3943).

**Pull request closed without merging**
