### PR TITLE
Added FreeBSD support

### PR DESCRIPTION
**Pull request by scopatz**
Relatively minor change to support another platform.

### CODE REVIEW

**Comment by melund** [comment]
Look good

**Comment by scopatz** [comment]
This is reported as working: https://groups.google.com/d/msgid/xonsh/23b604b0-339e-47d7-976a-ef092b9c4a8b%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by gforsyth** [comment]
Yep, looks good to go!

**Comment by gforsyth** [comment]
Next up, Solaris support!

**Pull request merged**
