### PR TITLE
[WIP] Slugify

### PR DESCRIPTION
**Pull request by AstraLuma**
Implement #2159.

Trying to rewrite the executor so that it doesn't bend over backwards to make subprocess work.

Instead, use a library for the POSIX process/piping model ([slug](https://github.com/xonsh/slug)) to more concisely express what we're doing with processes and make the code somewhat readable.

TODO

* [x] Aliases
* [ ] PTYs (Single global PTY? PTY per job?) (Blocked on PTY support in slug)
* [ ] Output is not making it out
* [ ] Process stderr along with stdout (will probably change under PTYs)
* [ ] Add `FossilizedJob` for purposes of history backends?
* [ ] Confirm usages of bytes vs text (We should be using bytes internally, except for when consumers--xsh code--want text.)

### CODE REVIEW

**Comment by astronouth7303** [comment]
BTW, does any of the other coredevs have commentary on this direction? If I died in 3 weeks and you had to fix a bug, would you be ok with that or would it be terrible?

**Comment by mitnk** [comment]
It's not terrible, if I need fix a bug in it, rather, I'll die for a second time for it. The first time happened when I touched @scopatz 's version ;) I mean this part is (one of) the most intricate part of xonsh. I doubt it can be simplified that much.

My idea is when you feel it's ready for a beta test, we can join and test it. I believe you will encounter a lot of issues/bugs during it. If this direction (slug) can solve most of them easily, then I'd say I support it. Please ping me when you implemented the PTY part.

Nice +/- in diffs!

**Comment by melund** [comment]
@astronouth7303 ... I newer spent time on the old Excer so I wouldn't have much said in this. I always like abstractions, and I am starting to grasp the complexity by following the Slug repo,

What I am trying to say is, that I am all for this, if you convince @scopatz :)

**Comment by laerus** [comment]
only 3 tests failing on linux! 
oddly py36 passes all

pytests fails on app veyor, cannot import winapi from ctypes

**Comment by astronouth7303** [comment]
Unfortunately, those tests point to a bug in slug, which is going to be uber-fun to track down.

**Comment by astronouth7303** [comment]
So I added tests to slug for this output problem, and that seems to be working fine.

Unfortunately, output is still getting dropped somewhere by something.

**Comment by laerus** [comment]
feels like a buffer needs flushing, can't spot where yet.

**Comment by astronouth7303** [comment]
I don't think so? All of the buffers are kernel-native pipes.

**Comment by astronouth7303** [comment]
1. Syncronization usually means locks and such, which won't help.
2. Python does buffering around text-mode pipes, because read-by-line and UTF-8 decode. Slugify moves xonsh to be using binary under the hood, which I have not seen any signs of buffering yet.
3. I'm generally careful about EOF conditions in slug, which should be flushing things out. (Prove me wrong!)

**Comment by laerus** [comment]
do we run tests with `-u`? 
i will try to dig in this w/e.

**Comment by astronouth7303** [comment]
No, `-u` is never used (afaik)

**Comment by laerus** [comment]
we use -u on the shebang of xonsh startup script

**Comment by gforsyth** [comment]
Hey @astronouth7303 -- I recognize that the slugification of xonsh is a massive undertaking.  Do you have a preference between keeping this PR open vs closing it and reopening one when work continues?

**Comment by astronouth7303** [comment]
That's... complicated. I know you want to do cleanup, though.

**Comment by melund** [comment]
@astronouth7303 I read the other day that Windows 10 is now getting a true Pseudo Console (PTY). 

Hopefully, this would allow us to drop support for the Win32 API, and make the Slugify work a lot simpler.

**Comment by laerus** [comment]
This would be awesome but then xonsh won't work on windows7 and older. (i don't mind)

**Comment by melund** [comment]
> This would be awesome but then xonsh won't work on windows7 and older. (i don't mind)

I don't think that would matter. It would still be possible to use an older version of xonsh in that case.

**Comment by astronouth7303** [comment]
Umm... why? Did I write something not Windows 7 compatible?

**Comment by astronouth7303** [comment]
Actually, the slug library doesn't support PTYs at all yet.

It's using Win32 for true process pausing/continuing and process groups.

**Comment by astronouth7303** [comment]
I mean, that was super annoying. But no, I've maintained feature parity between Posix and Windows.

The real challenge is the less mainstream kernels. Currently don't test Cygwin, MSYS, WSL, *BSD, Haiku, etc.

**Comment by gforsyth** [comment]
Closing out old PRs, thanks!

**Pull request closed without merging**
