### PR TITLE
Fix for bash wsl

### PR DESCRIPTION
**Pull request by melund**
This a potential fix for the Error when Bash from Windows Subsystem for Linux is on the path. See #1200

### CODE REVIEW

**Comment by adqm** [comment]
Is there any way to test this?  I don't have access to WSL.

**Comment by melund** [comment]
Me neither. Windows insider updates are broken on my computer. @klonuo tested it here: https://github.com/xonsh/xonsh/issues/1200
As I understand, the fix worked for him. I don't think that xonsh would be able to use that version of bash since it runs in its own subsystem. 

But this should at least prevent it from crashing xonsh.

**Comment by adqm** [comment]
Okay, that works for me.  Merging in.

Actually, I don't know much/anything about Windows.  Is there a way to tell whether I have WSL?  Or a way to get it if I don't?

**Comment by gforsyth** [comment]
@adqm I think it's exclusive to Windows 10

**Comment by adqm** [comment]
I am on Win10 on one of my machines.  If I have it up to date, does that mean i have WSL?

**Comment by gforsyth** [comment]
I think so?  What happens if you run `bash` from the command prompt?

**Comment by melund** [comment]
No. It is only available to Windows Insiders Slow or Fast ring. That is MS's beta program.

**Comment by melund** [comment]
I guess you could install xonsh on WSL similar to what you would do on Ubuntu using apt-get. It uses the exact same binaries.

**Comment by klonuo** [comment]
> I am on Win10 on one of my machines. If I have it up to date, does that mean i have WSL?

@adqm, WSL is disabled by default. You'll need to enable it first in Windows Features:

untitled

and also you need to have build >= 14316.

**Comment by melund** [comment]
Just a question out of curiosity. Are there any significant improvement to the console. I heard it should be able to support full VT100 colors :)

**Comment by klonuo** [comment]
I heard about that too, for the anniversary update, together with support for many ANSI codes, but it seems that ANSI sequences wont be available to other terminal host, except internally interpreted on console.
Console is improved a lot compared to previous Windows version, but Linux terminal is far reach IMHO ;)

**Comment by klonuo** [comment]
> I guess you could install xonsh on WSL similar to what you would do on Ubuntu using apt-get. It uses the exact same binaries. 

@melund just to let you know, that latest update on fast ring (14366), added `listxattr` syscall, so it's possible to pip install xonsh in bash for Windows. 

Problem was described for example here: https://github.com/Microsoft/BashOnWindows/issues/385

**Comment by melund** [comment]
Sounds interesting. Which I could upgrade

**Pull request merged**
