### PR TITLE
Enable 3.8 tests for circleci

### LINKED ISSUE #3117: Add Python 3.8 to CI
Need to add Python 3.8 to the test suites

### PR DESCRIPTION
**Pull request by carmenbianca**
Ran into this while submitting #3304 

Fixes #3117

### CODE REVIEW

**Comment by carmenbianca** [comment]
I guess that doesn't work.

**Comment by astronouth7303** [comment]
I suspect this has more to do with the way we're doing things with conda.

I guess we have to wait for conda to publish a Python 3.8 package.

**Comment by scopatz** [comment]
Yeah, we are still waiting on conda-forge's Python 3.8 package.  Thanks for putting this in @carmenbianca!

**Comment by gforsyth** [comment]
Hey @carmenbianca -- I'm going to close this out because we've just dropped Circle CI in favor of github actions, but thanks for putting it in!

**Pull request closed without merging**
