### PR TITLE
NetBSD support

### PR DESCRIPTION
**Pull request by scopatz**
@krytarowski can you try this out please?

### CODE REVIEW

**Comment by krytarowski** [comment]
`ls -G` is FreeBSD specific, we don't have a switch for colorized output

**Comment by scopatz** [comment]
OK thanks for letting me know

**Comment by scopatz** [comment]
Does this look correct?

**Comment by krytarowski** [comment]
It works! Thanks!

**Comment by scopatz** [comment]
Great! This should be ready to go in, then.

**Comment by gforsyth** [comment]
Nice. Thanks @scopatz!

**Pull request merged**
