### PR TITLE
Ignore failed test on Darwin

### PR DESCRIPTION
**Pull request by anki-code**
The test was added in #4106. I suggest to ignore this test until @jnoortheen review it.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Comment by jnoortheen** [comment]
@anki-code as you have mentioned in one of your comments, it running fine on your macos. Is it possible to determine why this is caused? this seems to be happening non-deterministic. I think there are some architecture changes in Github CI. If you need any pointers on where to look I can help.

**Comment by anki-code** [comment]
@jnoortheen I see this error [in CI](https://github.com/xonsh/xonsh/pull/4253/checks?check_run_id=2494805289) for MacOS + 3.6:
```python
 >       assert cc.all_commands == bins
E       AssertionError: assert {'bin1': ('/p.../bin2', None)} == {'bin1': ('/s.../bin2', None)}
E         Differing items:
E         {'bin1': ('/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pytest-of-runner/pytest-0/test_commands_cache_uses_pickl0/bin1', None)} != {'bin1': ('/some-path/bin1', None)}
E         {'bin2': ('/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pytest-of-runner/pytest-0/test_commands_cache_uses_pickl0/bin2', None)} != {'bin2': ('/some-path/bin2', None)}
```
Do you have thoughts why the path looks `/private/...`?

**Comment by anki-code** [comment]
I've ran the test on Linux and after 10 runs I catched:
```
>       assert cc.all_commands == bins
E       AssertionError: assert {'bin1': ('/t.../bin2', None)} == {'bin1': ('/s.../bin2', None)}
E         Differing items:
E         {'bin2': ('/tmp/pytest-of-pc/pytest-4/test_commands_cache_uses_pickl0/bin2', None)} != {'bin2': ('/some-path/bin2', None)}
E         {'bin1': ('/tmp/pytest-of-pc/pytest-4/test_commands_cache_uses_pickl0/bin1', None)} != {'bin1': ('/some-path/bin1', None)}
```
@jnoortheen this looks that test suit for this is unstable.

**Comment by jnoortheen** [comment]
> 1. I've ran the test on Linux and after 10 runs I catched:
> 
> ```
> >       assert cc.all_commands == bins
> E       AssertionError: assert {'bin1': ('/t.../bin2', None)} == {'bin1': ('/s.../bin2', None)}
> E         Differing items:
> E         {'bin2': ('/tmp/pytest-of-pc/pytest-4/test_commands_cache_uses_pickl0/bin2', None)} != {'bin2': ('/some-path/bin2', None)}
> E         {'bin1': ('/tmp/pytest-of-pc/pytest-4/test_commands_cache_uses_pickl0/bin1', None)} != {'bin1': ('/some-path/bin1', None)}
> ```
> 
> @jnoortheen this looks that test suit for this is unstable.
> 
> Run this:
> 
> ```python
> for i in range(0, 20):
>       pytest tests/test_commands_cache.py
> ```

OK I will check this.

**Comment by anki-code** [comment]
@jnoortheen  I'm going to convert this PR to draft and will wait the fix from you in the distinct PR.

**Comment by jnoortheen** [comment]
> @jnoortheen I'm going to convert this PR to draft and will wait the fix from you in the distinct PR.

I think now this can be closed.

**Comment by anki-code** [comment]
Closed with reference to #4257

**Pull request closed without merging**
