### PR TITLE
fix: vox system_site_packages option not passed

### PR DESCRIPTION
**Pull request by jnoortheen**
## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Comment by daniel-shimon** [comment]
Are the test changes only a refractor or do they check the new behavior?

**Comment by jnoortheen** [comment]
> Are the test changes only a refractor or do they check the new behavior?

Just a refactor.

**Comment by daniel-shimon** [comment]
Can you add these tests to the pr? :)

**Comment by jnoortheen** [comment]
@daniel-shimon they are related to argparser change.

**Review by daniel-shimon — APPROVED** [review]

**Comment by daniel-shimon** [comment]
@jnoortheen in the future I'd prefer you do these things in a separate PR or at least a separate commit 🙌

**Pull request merged**
