### PR TITLE
stringify values that come from FORMATTER_DICT envvar

### PR DESCRIPTION
**Pull request by laerus**
#1564

### CODE REVIEW

**Comment by scopatz** [comment]
Looks like we have cross-the board-failures @laerus. What was the type that wasn't a string?

**Comment by scopatz** [comment]
For instance, I think if val is None then it should be skipped, or replaced with an empty string.

**Comment by laerus** [comment]
i'm looking for a temporal fix here so i can then try for a refactor, i think we need a proper `XonshPrompt` object in place of `$FORMATTER_DICT` that inherits from `MuttableMapping` and maybe `string.Fromatter` and later maybe move most of the work being done in the shells on the `XonshPrompt`, what do you think? also what would be a good name in place of `FORMATTER_DICT`, something like `$XONSH_PROMPT` ?

**Comment by laerus** [comment]
btw can i move `prompt.base` to `prompt.__init__` so we can just `import xonsh.prompt` or does this interfere with amalgamation ?

**Comment by derekbrokeit** [comment]
I'm new to xonsh, but have been very interested in the positive direction I see this shell moving. I was about to submit a bug report regarding a similar issue, but I found this issue and wanted to add my two cents.

Instead of stringify results of `$FORMATTER_DICT` it should attempt to use arbitrary objects. Here's an example of a useful application to have a universal date formatter:

```
import datetime
$FORMATTER_DICT['date'] = datetime.datetime.now
$PROMPT = "{date:%H:%M} >>> "
$RIGHT_PROMPT = "{date:%Y-%m-%d}"
```

A nice advantage of this would be improvements to the customizability of builtin formatters such as `gitstatus`. Instead of `"{gitstatus}"` the gitstatus formatter could return a `GitStatus` customized object with a `__format__` method that allows for customization: `{gitstatus:%(branch)|%(status)}` or something similar. Another possible addition would be that the object is turned into an empty string if the returned object is `None`. 

I think this would be a better long term step than just standard string conversion, which 529d933 seems to produce.

**Comment by scopatz** [comment]
Thanks @laerus!

Also @derekbrokeit, thanks for using xonsh!  Personally, I am all in favor of having improved / better prompt formatting mechanisms. Your suggestions do sound useful.  Pull requests are very welcome in this department, and more broadly.

**Pull request merged**
