### PR TITLE
changed internal usage of NO_COLOR to reset

### LINKED ISSUE #3833: PTK completion prefix matching is broken
I believe #3774 had a few unintended side-effects (and also laid out that we probably need more completion tests).

## xonfig

<details>

```
$ xonfig
+------------------+----------------------+
| xonsh            | 0.9.22.dev165        |
| Git SHA          | 580b675f             |
| Commit Date      | Sep 30 19:48:13 2020 |
| Python           | 3.8.5                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.7                |
| shell type       | prompt_toolkit       |
| pygments         | 2.6.1                |
| on posix         | True                 |
| on linux         | False                |
| on darwin        | True                 |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
+------------------+----------------------+
```

</details>

## Expected Behavior
When completing available options, we should insert the entirety of the matching prefix of all available options, nothing more.

E.g. if I have this folder structure:

```
dask/
  dask/
  distributed/
```

and I type

```
cd dask/<TAB>
```

it should fill in the common `d` and then stop.

## Current Behavior

In the above, when I type `cd dask/<TAB>` it autoselects `dask/dask`

## Steps to Reproduce

```
mkdir -p dask/dask dask/distributed
cd dask/<TAB>
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### PR DESCRIPTION
**Pull request by scopatz**
Closes #3833 CC @gforsyth

### CODE REVIEW

**Review by gforsyth — APPROVED** [review]
welp, that's hilarious.  Looks good.  I'll merge after CI passes.

Thanks @scopatz!

**Comment by scopatz** [comment]
haha yeah, mea culpa.... I really should have checked this in the original PR :wink:

**Comment by gforsyth** [comment]
whoops, also looks like #3833 was linked, instead of #3834 

I'll reopen #3833 after the merge closes it.

**Comment by gforsyth** [comment]
Thanks, @scopatz !

**Pull request merged**
