### PR TITLE
fix test failures due to absense of builtin 'echo' on Windows

### PR DESCRIPTION
**Pull request by bobhy**
Add 'echo' to list of aliases defined for Windows only.
Fixes these test failures on current master.  

```
$ py.test tests\test_xonsh.xsh
============================= test session starts =============================
platform win32 -- Python 3.5.1, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: n:\DevWork\work\xonsh, inifile: setup.cfg
plugins: xonsh-0.4.6
collected 3 items

tests\test_xonsh.xsh ..F

================================== FAILURES ===================================
________________________ xonsh test: test_xonsh_party _________________________
xonsh execution failed
  File "n:\DevWork\work\xonsh\tests\test_xonsh.xsh", line 17, in test_xonsh_party
    out = $(echo @(x + ' ' + y))
  File "n:\devwork\work\xonsh\xonsh\built_ins.py", line 642, in subproc_captured_stdout
    return run_subproc(cmds, captured='stdout')
  File "n:\devwork\work\xonsh\xonsh\built_ins.py", line 537, in run_subproc
    raise XonshError(e)
XonshError: xonsh: subprocess mode: command not found: echo
===================== 1 failed, 2 passed in 0.76 seconds ======================
$ py.test tests\test_ptk*.py
============================= test session starts =============================
platform win32 -- Python 3.5.1, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: n:\DevWork\work\xonsh, inifile: setup.cfg
plugins: xonsh-0.4.6
collected 18 items

tests\test_ptk_highlight.py ss...F...F
tests\test_ptk_history.py .
tests\test_ptk_multiline.py .......

================================== FAILURES ===================================
_________________________________ test_nested _________________________________

    def test_nested():
        check_token('echo @("hello")', [(Name.Builtin, 'echo'),
                                        (Keyword, '@'),
                                        (Punctuation, '('),
                                        (String.Double, 'hello'),
>                                       (Punctuation, ')')])

tests\test_ptk_highlight.py:83:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

code = 'echo @("hello")'
tokens = [(Token.Name.Builtin, 'echo'), (Token.Keyword, '@'), (Token.Punctuation, '('), (Token.Literal.String.Double, 'hello'), (Token.Punctuation, ')')]

    def check_token(code, tokens):
        """Make sure that all tokens appears in code in order"""
        lx = XonshLexer()
        tks = list(lx.get_tokens(code))

        for tk in tokens:
            while tks:
                if tk == tks[0]:
                    break
                tks = tks[1:]
            else:
                msg = "Token {!r} missing: {!r}".format(tk,
                                                        list(lx.get_tokens(code)))
>               pytest.fail(msg)
E               Failed: Token (Token.Name.Builtin, 'echo') missing: [(Token.Text.Whitespace, ''), (Token.Name, 'echo'), (Token.Text, ' '), (Token.Keyword, '@'), (Token.Punctuation, '('), (Token.Literal.String.Double, '"'), (Token.Literal.String.Double, 'hello'), (Token.Literal.String.Double, '"'), (Token.Punctuation, ')'), (Token.Text, '\n')]

tests\test_ptk_highlight.py:40: Failed
_________________________________ test_macro __________________________________

    def test_macro():
        check_token(r'g!(42, *, 65)', [(Name, 'g'),
                                       (Keyword, '!'),
                                       (Punctuation, '('),
                                       (Number.Integer, '42')])
        check_token(r'echo! hello world', [(Name.Builtin, 'echo'),
                                           (Keyword, '!'),
>                                          (String, "hello world")])

tests\test_ptk_highlight.py:133:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

code = 'echo! hello world'
tokens = [(Token.Name.Builtin, 'echo'), (Token.Keyword, '!'), (Token.Literal.String, 'hello world')]

    def check_token(code, tokens):
        """Make sure that all tokens appears in code in order"""
        lx = XonshLexer()
        tks = list(lx.get_tokens(code))

        for tk in tokens:
            while tks:
                if tk == tks[0]:
                    break
                tks = tks[1:]
            else:
                msg = "Token {!r} missing: {!r}".format(tk,
                                                        list(lx.get_tokens(code)))
>               pytest.fail(msg)
E               Failed: Token (Token.Name.Builtin, 'echo') missing: [(Token.Text.Whitespace, ''), (Token.Name, 'echo'), (Token.Keyword, '!'), (Token.Text, ' '), (Token.Name, 'hello'), (Token.Text, ' '), (Token.Name, 'world'), (Token.Text, '\n')]

tests\test_ptk_highlight.py:40: Failed
=============== 2 failed, 14 passed, 2 skipped in 2.12 seconds ================
```

### CODE REVIEW

**Comment by bobhy** [comment]
But, as you notice, I'm still having some problem with `test_xonsh.xsh'.  

```
$ py.test tests\test_xonsh.xsh
============================= test session starts =============================
platform win32 -- Python 3.5.1, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: n:\DevWork\work\xonsh, inifile: setup.cfg
plugins: xonsh-0.4.6
collected 3 items

tests\test_xonsh.xsh ..F

================================== FAILURES ===================================
________________________ xonsh test: test_xonsh_party _________________________
xonsh execution failed
  File "n:\DevWork\work\xonsh\tests\test_xonsh.xsh", line 18, in test_xonsh_party
    assert out == 'xonsh party\n', 'Out really was <' + out + '>, sorry.'
AssertionError: Out really was <"xonsh party"
>, sorry.
===================== 1 failed, 2 passed in 0.26 seconds ======================
```
But the extra double quotes do not repro at a command prompt.

```
$ aliases['echo'] = ['cmd', '/c', 'echo']
. aaa = $(echo foo)
. print(aaa)
. bbb = $(echo @('abc'))
. print(bbb)
.
foo

abc
```

I guess the extra double quotes are an artifact of the mockery we make of the environment in the unit test setup, but don't really know where to start.

Y

**Comment by scopatz** [comment]
Thanks @bobhy!  I have never gotten the test*.xsh files to work locally, myself.

**Comment by bobhy** [comment]
You may also be wondering why I modified the assert in `test_xonsh.xsh`.  Before I did so, I was getting this error:

```
$ py.test --assert=reinterp tests\test_xonsh.xsh
============================= test session starts =============================
platform win32 -- Python 3.5.1, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: n:\DevWork\work\xonsh, inifile: setup.cfg
plugins: xonsh-0.4.6
collected 3 items

tests\test_xonsh.xsh ..F

================================== FAILURES ===================================
________________________ xonsh test: test_xonsh_party _________________________
xonsh execution failed
  File "n:\DevWork\work\xonsh\tests\test_xonsh.xsh", line 19, in test_xonsh_party
    assert out == 'xonsh party\n'
  File "c:\python35\lib\site-packages\_pytest\assertion\reinterpret.py", line 36, in __init__
    source = source.getstatement(f.lineno, assertion=True)
  File "c:\python35\lib\site-packages\_pytest\_code\source.py", line 107, in getstatement
    start, end = self.getstatementrange(lineno, assertion)
  File "c:\python35\lib\site-packages\_pytest\_code\source.py", line 116, in getstatementrange
    ast, start, end = getstatementrange_ast(lineno, self)
  File "c:\python35\lib\site-packages\_pytest\_code\source.py", line 356, in getstatementrange_ast
    start, end = get_statement_startend2(lineno, astnode)
  File "c:\python35\lib\site-packages\_pytest\_code\source.py", line 326, in get_statement_startend2
    for x in ast.walk(node):
  File "c:\python35\lib\ast.py", line 217, in walk
    todo.extend(iter_child_nodes(node))
  File "c:\python35\lib\ast.py", line 182, in iter_child_nodes
    for name, field in iter_fields(node):
  File "c:\python35\lib\ast.py", line 170, in iter_fields
    for field in node._fields:
AttributeError: 'NoneType' object has no attribute '_fields'
===================== 1 failed, 2 passed in 0.26 seconds ======================
```

This has to do with `py.test` reinterpreting the `assert' and having some difficulty compiling the generated code.  I could make the error go away by running the tests as `py.test --assert=plain`, but then I had no idea what the failing value was.

I was able to discover that the source code being fed to `compile` was .xsh, not pure Python, but could not get any further.

**Comment by bobhy** [comment]
Well @scopatz, thanks for taking this fix with a minimum of fuss. 
But we do still have this failing test case that doesn't repro at the command prompt. 
Do we want to spend any cycles on debugging the test environment? I am willing to do so, but need some hint where to start looking.

**Comment by scopatz** [comment]
Well it passed CI, so I think local failures are worth dealing with, but they can be in a separate PR

**Pull request merged**
