### PR TITLE
more tilde expansions

### PR DESCRIPTION
**Pull request by scopatz**
It has been bothering me recently that tildes weren't expanded inside of expresions, like in Bash. I didn't know what was causing it. However, it is a pretty simple fix. Just a few lines.  You can read about the Bash semantics that I tried to match here: https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html

### CODE REVIEW

**Comment by scopatz** [comment]
I am a little confused why circle is running here since we haven't merged in the yaml file.

**Comment by gforsyth** [comment]
Hey @scopatz -- so CircleCI seems to have this mantra of "it just works!" and they try to automagically determine how to run tests, etc...
This... doesn't work, so any pushes without the `circle.yml` file will still run in circle, but will fail.  
I didn't realize this would happen -- it's pretty annoying.  We can merge in the circle CI stuff with the yaml file, or I can also revoke the deploy key so they will stop.

**Comment by scopatz** [comment]
Ahh ok, I will just gao ahead and merge in the corcle pr then

**Comment by scopatz** [comment]
Merged in from master to pick up the tilde expansion.

**Comment by scopatz** [comment]
Ping to whoever can merge it since @gforsyth is now AFK

**Comment by laerus** [comment]
seems like nightly fails somewhere on `test_ast.py`

**Comment by scopatz** [comment]
Ok seems to be working now

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
