### PR TITLE
Add xontrib that brings many useful shortcuts to xonsh.

### PR DESCRIPTION
**Pull request by AsafFisher**
Example:
https://user-images.githubusercontent.com/6796683/159818602-00460771-7965-4745-b12e-233c191afa5a.mp4

### CODE REVIEW

**Comment by jnoortheen** [comment]
@AsafFisher this is a case where the names will clash with what one has defined or the binary names. Like other shells it is better installed as an extension. Please create a xontrib for this, it will be helpful to others. 0lease check the template to fastrack the work - https://github.com/xonsh/xontrib-cookiecutter

**Comment by AsafFisher** [comment]
Puttying it in the xontrib folder is not enough?

**Comment by jnoortheen** [comment]
Yes they can be a separate Python packages installable along xonsh with pip. These kind of opinionated names are better kept as a separate package. If some has name clash they can simply update or fork

**Comment by AsafFisher** [comment]
How to I add 
https://github.com/AsafFisher/xontrib-oh-my-xonsh
to the default xontrib list?

**Comment by jnoortheen** [comment]
You can add it to https://github.com/xonsh/xonsh/blob/main/xonsh/xontribs_meta.py and create a PR

**Pull request closed without merging**
