### PR TITLE
Add tests and fix bugs for RichCompletion and Jedi xontrib

### PR DESCRIPTION
**Pull request by daniel-shimon**
Continuing #3643, I wrote some tests and fixed some small bugs

### CODE REVIEW

**Comment by scopatz** [comment]
Cool thanks! It looks like these tests you added are failing though. :wink:

**Comment by daniel-shimon** [comment]
> Cool thanks! It looks like these tests you added are failing though. 😉

Yeah.. It seems like I wasn't running the tests locally properly.
I'm having some trouble running them to achieve the same results like in the CI...

If I'm using `xonsh-in-docker.py` some tests fail (because the image doesn't have `man` installed for instance),
And if I try running it from my own machine (Ubuntu 20.04) all the tests run smoothly.

How do you run them locally?

**Comment by scopatz** [comment]
I just run `./run-tests.xsh` in the root level dir of the repo

**Comment by daniel-shimon** [comment]
@scopatz done 😄

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
