### PR TITLE
feat: Added ability to get arguments list in ExecAlias

### PR DESCRIPTION
**Pull request by anki-code**
This PR adds `$args` and `$arg0`..`$arg<n>` environment variables to the `ExecAlias` context. Motivation: https://github.com/xonsh/xonsh/pull/4201#issuecomment-810754606

Exampls:
```python
aliases['my'] = "echo Hello @($args)"    # ExecAlias
my 'world!'
# Hello world!
```
```python
aliases['cl'] = "cd $arg0 && ls $arg0"
cl /tmp
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Comment by anki-code** [comment]
@gforsyth please take a look ;)

**Comment by gforsyth** [comment]
Hey @anki-code !  
Is this inherently different from passing through alias arguments using the `def _func(args):` callable aliases?  Or is it the same (ish) and providing a simpler syntax for handling that?

**Comment by anki-code** [comment]
Yep, this is the simpler syntax. For example you want to create alias that do `cd` and `ls`:

You can't write one line using `$[]` because it has no `&&` support:
```python
aliases['cdls'] = $[cd @(args[0]) && ls @(args[0])]
# Syntax error around &&
```

You can write 4 lines:
```python
def _cd_and_ls(args):
    cd @(args[0])
    ls @(args[0])
aliases['cdls'] = _cd_and_ls 
```

Also you can write the syntax overloaded example:
```python
aliases['cdls'] = lambda args: execx(f"cd @({repr(args[0])}) && ls @({repr(args[0])})")
```

This PR allows to make ExecAlias completed by adding ability to use args and to write the sane alias:
```python
aliases['cdls'] = "cd $ALIAS_ARG0 && ls $ALIAS_ARG0"
```

Naming. Instead of `$ALIAS_ARGS` I thought about using `$ARGS` and `$ARG1`..`$ARGn` like in non-interactive xsh. But we can use aliases in the scripts and potentially we can want to use `$ARGS` of the script in the aliases. I prefer to make the name shorter but have no idea how to keep it sane. New shorter naming is welcome.

**Comment by anki-code** [comment]
The tests looks broken in the main branch.

**Comment by gforsyth** [comment]
Hey @anki-code -- thanks for the explanation!  I agree that this fits a model that is currently really awkward with `xonsh`, so I'm game to add it in.  
I'd like to sit and think a little bit -- I would love if we could re-use the `ARGn` identifiers, but you make a good point about potential collisions.

Either way we'd want to add a section to the docs about how to use this.

And yeah, not sure what's going on with the test suite.  That's a new wacky failure for me (or I've forgotten 😅 )

**Comment by anki-code** [comment]
Eurika! What about `$args` in lowercase?

```python
aliases['cdls'] = "cd $arg0 && ls $arg0"
```

**Comment by anki-code** [comment]
@gforsyth we're on the way to finish line here ;)

**Review by jnoortheen — APPROVED** [review]

**Comment by jnoortheen** [comment]
> @jnoortheen -- can you take a look at this and see what you think?

It all looks good, with small change we get a shorter way to specify alias function. Though I prefer having only one way to do things,  it looks reasonable addition (more bashy ).

**Comment by anki-code** [comment]
Hi @gforsyth! Let's go forward! :)

**Comment by gforsyth** [comment]
Thanks @anki-code !

**Comment by gforsyth** [comment]
And thanks for the review @jnoortheen !

**Pull request merged**
