### PR TITLE
Fixing branch and repo state...

### PR DESCRIPTION
**Pull request by Siecje**
Previously you had to run a git or hg command in order for the branch and repo
state to be displayed in the prompt.

### CODE REVIEW

**Comment by melund** [comment]
Will this mean that the `command_cache` is updated when xonsh starts? Can you test what this PR do to the startup time.

**Comment by Siecje** [comment]
Currently your prompt will be different depending if you have recently run git or hg.

This is a PR for the vc branch.

This is is removing checking ```builtins.__xonsh_commands_cache__``` so it does not update ```command_cache``` when ```xonsh``` starts.

This should not impact the startup time.

**Comment by laerus** [comment]
this will fail if we have no git/hg installed though.

**Comment by melund** [comment]
Yes. The problem now is that it doesn't show the branch info until after the `command_cache` has been updated. That is why it starts working when after you have run a 'git/hg' command. Actually, any subproc command would do.

But we don't want the `command_cache` to be updated at startup to keep the startup time low. Maybe we can evaluate the `command_cache` in a separate thread on startup.

**Comment by Siecje** [comment]
@laerus Good catch. I've updated the code to handle when hg is not installed.

@melund This PR doesn't use the ```command_cache```. It does try to run both ```git``` and ```hg``` if you are not in a repo. Using a cache might make ```xonsh``` faster when not in a repo. We can address this if it is an issue.

Another speed increase would be to figure out if it is a git or hg repo once, not in ```current_branch()``` and ```dirty_working_directory()```. 

Both of those function try to get the value for ```git``` and if it is not found get it for ```hg```.

**Comment by laerus** [comment]
We should handle the case when git is not installed aswell, also if we do not indeed have hg/git installed this will keep trying to run them on every prompt update and that is what `lazy_locate_binary` is speeding up.

**Comment by Siecje** [comment]
@laerus I was not able to trigger an error when ```git``` was not installed.

**Comment by laerus** [comment]
hey @siecje can you please add/change the news in `git_branch.rst` `hg_branch.rst` to cover this changes?

**Comment by Siecje** [comment]
This was a pull request for the ```vc``` branch in order for VCS branches and repo state to work for me.

I see you have merged ```vc```. If you don't need these changes then you can close this.

**Comment by laerus** [comment]
I've merged so we can merge this, just needs news tweaking so we dont lose track of whats what. i'll take a closer look when i will have more time.

**Comment by laerus** [comment]
my bad @siecje i thought this was a PR for master, if you want to add news and push to master i will merge asap.

**Comment by laerus** [comment]
@melund apparently `__xonsh_commands_cache__.is_empty` populates the cache when it returns True (strange), so this was always a part of the startup when formatting the first prompt.

**Comment by melund** [comment]
Well spotted @laerus. Maybe this will help speed up windows startup times then

**Comment by Siecje** [comment]
I'm going to close this because I may have been confused with the hg branch not working due to https://github.com/xonsh/xonsh/issues/1948

I'm sure this will come up again if it is still an issue.

**Pull request closed without merging**
