### PR TITLE
Return of the Jedi

### PR DESCRIPTION
**Pull request by scopatz**
Tab completion in Alderaan places. See #344 #2127

### CODE REVIEW

**Comment by gforsyth** [comment]
> Tab completion in Alderaan places

So yeah, this should be added to the list of catchphrases.

**Comment by gforsyth** [comment]
This is supposed to allow parameter completion in function names, yes? Not sure what's going on here...

```python
gil@theo ~ $ xontrib list
apt_tabcomplete     not-installed  not-loaded
autoxsh             not-installed  not-loaded
bashisms            installed      not-loaded
distributed         installed      not-loaded
docker_tabcomplete  not-installed  not-loaded
jedi                installed      loaded
mpl                 installed      not-loaded
prompt_ret_code     installed      not-loaded
scrapy_tabcomplete  not-installed  not-loaded
vox                 installed      not-loaded
vox_tabcomplete     not-installed  not-loaded
xo                  not-installed  not-loaded
xonda               installed      not-loaded
avox                not-installed  not-loaded
z                   not-installed  not-loaded
powerline           not-installed  not-loaded
prompt_vi_mode      not-installed  not-loaded
click_tabcomplete   not-installed  not-loaded
gil@theo ~ $ import numpy
gil@theo ~ $ numpy.zeros(<TAB>
Exception in thread Thread-90:
Traceback (most recent call last):
  File "/home/gil/miniconda3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/gil/miniconda3/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gil/miniconda3/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 840, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/home/gil/miniconda3/lib/python3.5/site-packages/xonsh/ptk/completer.py", line 42, in get_compls
    self.ctx)
  File "/home/gil/miniconda3/lib/python3.5/site-packages/xonsh/completer.py", line 35, in complete
    out = func(prefix, line, begidx, endidx, ctx)
  File "/home/gil/miniconda3/lib/python3.5/site-packages/xonsh/completers/base.py", line 20, in complete
    python_comps = complete_python(prefix, line, start, end, ctx)
  File "/home/gil/miniconda3/lib/python3.5/site-packages/xonsh/completers/python.py", line 53, in compln
    rtn = _complete_python(prefix, line, start, end, ctx)
  File "/home/gil/miniconda3/lib/python3.5/site-packages/xonsh/completers/python.py", line 77, in _compn
    args = python_signature_complete(prefix, line, end, ctx, filt)
  File "/home/gil/miniconda3/lib/python3.5/site-packages/xonsh/completers/python.py", line 174, in pythe
    sig = inspect.signature(val)                                                                        
  File "/home/gil/miniconda3/lib/python3.5/inspect.py", line 2987, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/home/gil/miniconda3/lib/python3.5/inspect.py", line 2737, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "/home/gil/miniconda3/lib/python3.5/inspect.py", line 2230, in _signature_from_callable
    skip_bound_arg=skip_bound_arg)
  File "/home/gil/miniconda3/lib/python3.5/inspect.py", line 2060, in _signature_from_builtin
    raise ValueError("no signature found for builtin {!r}".format(func))
ValueError: no signature found for builtin <built-in function zeros>
```

It looks like it's not being picked up by Jedi. And then there's a separate issue wherein python completion should at least fail gracefully.

**Comment by scopatz** [comment]
Yeah, it is hard to know when jedi should/shoudn't work.  And you are right about the default completer failure. Maybe that should have a separate issue?

**Comment by scopatz** [comment]
Done and done

**Comment by scopatz** [comment]
Anything else need to happen on this one?

**Comment by gforsyth** [comment]
Hey @scopatz , I'm going to try to take a look at this this weekend -- just hard to know if it's actually doing anything...

**Comment by scopatz** [comment]
Sounds good! I really appreciate it!

**Comment by scopatz** [comment]
pinging this again, for anyone who wants to take a look at it.

**Comment by gforsyth** [comment]
Hey @scopatz -- sorry for the delay on this (again). 
A few things:
1. It _does_ work. I've confirmed that the results I'm seeing in shell are the same as those returned by `jedi.api.Interpreter`, although it doesn't return any parameter completions, so far as I can tell, so I'm not sure if there's any benefit over our existing Python completions?

2. One side effect of loading Jedi completions is that it breaks the completions for `xontrib` and `completer` and possibly others, where it returns various parts of `__xonsh_ctx__` but not anything else (like the subcommands of those commands)

Oh... actually, i just realized that this breaks most completions, including all of bash completion. Loading the `jedi` xontrib and then doing a `ssh <TAB>` will return a bunch of python dunder methods, and not the `ssh` options

**Comment by scopatz** [comment]
Hi @gforsyth - thanks for taking a look! I think that this is because jedi always returns *some* completions options. However, the way our completer works is that the one that returns *any* completions first wins. I think this was done for performance(?). Maybe Jedi should come last and we should remove the Python completer?

**Comment by gforsyth** [comment]
I think that should work?  I'll take a look.

**Comment by scopatz** [comment]
I just pushed up a changed that implements that. It seems to work much better for me.

**Comment by gforsyth** [comment]
That works on my end. I think that's probably enough for this to go in -- it is optional after all.

**Comment by gforsyth** [comment]
Hmm, is the AppVeyor failure one we've seen before?  Looks like a timeout only on Python 3.5?

**Comment by scopatz** [comment]
I have been noticing random integration test timeout failures on travis and appveyor. Restarting (sometimes many times) does seem to fix it.

**Comment by scopatz** [comment]
Yep, looks like it is passing now!

**Comment by gforsyth** [comment]
Thanks for the xontrib, @scopatz ! And your patience.

**Comment by scopatz** [comment]
NP! Thanks for the review!

**Pull request merged**
