### PR TITLE
News files

### PR DESCRIPTION
**Pull request by scopatz**
Added the ability for the release script to read in and merge news files. This should help prevent excessive merge conflicts.  This may be tested with the following:

```console
$./release.xsh --only-version-bump 0.3.5
$ git diff
$ git checkout -- .
```

Suffice to say, the sooner this is merged the better :)

### CODE REVIEW

**Comment by gforsyth** [comment]
Hmm, it seems like it might not be combining the various categories properly?

I created a `mybranch.rst` file as follows and then ran the release script.

```console
**Added:** 

* This is a test message that I have added
 
**Changed:** None
 
**Deprecated:** None

**Removed:** None

**Fixed:** None

**Security:** None
```

full generated file is here: https://gist.github.com/gforsyth/e2511ea4ab34f2b2b554161e1e8e12d8

My note was added under Security and spaced incorrectly

**Comment by scopatz** [comment]
Thanks for pointing this out @gforsyth! It was a minor regex error.  Can you try it out now?

**Comment by gforsyth** [comment]
That did it!  Merging now.

**Comment by adqm** [comment]
Woo-hoo!  So after 0.3.5 we'll switch to this?  Or should I switch my current PRs to this format?

**Comment by scopatz** [comment]
Great! @adqm - you should switch now, because this actually picks up the pre-existing "current developments"

**Pull request merged**
