### PR TITLE
Added support for slices in EnvPath

### PR DESCRIPTION
**Pull request by VHarisop**
Quick fix for #1279.

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks @VHarisop! This looks right to me. Would you mind adding a couple of tests please, and preferably none with relative paths ;)

**Comment by VHarisop** [comment]
Yeah, that would be no problem. Should I merge the changes you made in #1278 in my next commits, or should I just push the extra tests now and resolve any potential conflicts later?

**Comment by scopatz** [comment]
You should not merge that other PR.  However, to prevent potential conflicts, you should probably just add another test function.

**Comment by scopatz** [comment]
That would be deeply appreciated

**Comment by VHarisop** [comment]
@scopatz Sorry for the delay, work has been overwhelming lately. I'll try to get my hands on those failing windows tests mentioned in #1284 as soon as I can.

**Comment by scopatz** [comment]
No worries, @VHarisop.  @melund or @BYK would you mind testing this to see if it tests fine on Windows?  Alternatively @VHarisop, could you please merge from master so that we can trigger a new appveyor build? Thanks!

Code looks good to me, but I am not sure it will test on Windows since it doesn't contain a drive name.

**Comment by melund** [comment]
I just tried it and ran tests locally. They all pass. Thanks.

**Pull request merged**
