### PR TITLE
lazyasd: Fix typo in docstring

### PR DESCRIPTION
**Pull request by jcfr**
[ci skip]

### CODE REVIEW

**Comment by astronouth7303** [comment]
Thanks! 

I don't think individual typos require top-level news items, so I'm merging.

**Comment by thisch** [comment]
This fix should be cherry-picked to the xonsh/lazyasd repo.

**Comment by scopatz** [comment]
Thanks @jcfr!

@thisch - yes it should. In general, amalgame and lazyasd changes should happen in their own repos. I'll copy this over, now though. Not a problem.

**Comment by jcfr** [comment]
Thanks everyone for moving forward with the PR.

`lazyasd` looks like a very neat project, thanks for creating a reusable package outside of xonsh. :+1:

**Pull request merged**
