### PR TITLE
Add brackets to ambiguous data type

### PR DESCRIPTION
**Pull request by farisachugthai**
Without the brackets python defaults to assuming that the iterable is a tuple. In the reference guide `__all__` is explicitly stated to be of type `list`.

Functionally I'll admit this doesn't change anything but to observe the correct usage pattern of `__all__`, simply add the brackets.

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks @farisachugthai! I think that you need the fix in https://github.com/xonsh/xonsh/pull/3984 for this to pass

**Comment by daniel-shimon** [comment]
Hey @farisachugthai, please rebase on master for the checks to pass

**Comment by scopatz** [comment]
pinging this.  I don't have permission to push to the @farisachugthai's branch.  Though I suppose someone could reopen this in a new PR

**Comment by farisachugthai** [comment]
Hey guys sorry for the delay! I merged upstream into master. Let me know if it needs a rebase or if everything looks cleanly okay.

**Review by daniel-shimon — APPROVED** [review]
This probably doesn't need a news file
@scopatz can you merge it?

**Comment by gforsyth** [comment]
Thanks @farisachugthai !

**Pull request merged**
