### PR TITLE
Signal Interrupt Responsiveness 

### PR DESCRIPTION
**Pull request by scopatz**
This should hopefully address the Ctrl-C issues folks have been living with (see #2599). Kind of an interesting algorithm to make it more responsive.  

I have done some testing and it seems to perform well or better than 0.6.1 with respect to CPU and memory, especially on the edge cases like `yes` where every other character is a newline.

### CODE REVIEW

**Comment by scopatz** [comment]
Appveyor seems to be totally stalled right now...

**Comment by gforsyth** [comment]
This seems to work well and I don't know if it makes sense to wait on Appveyor?

**Comment by gforsyth** [comment]
oooh, scratch that.  that's an... interesting failure on appveyor

**Comment by gforsyth** [comment]
```
_____________________________ test_script[case2] ______________________________
case = ("\ndef _f(args, stdin, stdout, stderr):\n    print('The Truth is Out There', file=stderr)\n\naliases['f'] = _f\nf e>o\n", 'The Truth is Out There\n', 0)
    @pytest.mark.parametrize('case', ALL_PLATFORMS)
    def test_script(case):
        script, exp_out, exp_rtn = case
        out, err, rtn = run_xonsh(script)
>       assert exp_out == out
E       assert 'The Truth is Out There\n' == 'e ThTruth is Out There\n'
E         - The Truth is Out There
E         ?   --
E         + e ThTruth is Out There
E         ? ++
tests\test_integrations.py:243: AssertionError
============= 1 failed, 2992 passed, 34 skipped in 54.57 seconds ==============
```

**Comment by melund** [comment]
Yes. That is an interesting failure. Is that really from @scopatz change... Seems weird. Anyway, I really like the algorithm with adaptive read sizes...

**Comment by scopatz** [comment]
Ahh Yeah, I saw this error yesterday during development. It turns out is is releated to queue size and redirection. Bumping the queue size should fix it.  I'll do that now.

> Anyway, I really like the algorithm with adaptive read sizes...

Thanks!

**Comment by gforsyth** [comment]
```
case = ("\ndef _f(args, stdin, stdout, stderr):\n    print('The Truth is Out There', file=stderr)\n\naliases['f'] = _f\nf e>o\n", 'The Truth is Out There\n', 0)
    @pytest.mark.parametrize('case', ALL_PLATFORMS)
    def test_script(case):
        script, exp_out, exp_rtn = case
        out, err, rtn = run_xonsh(script)
>       assert exp_out == out
E       assert 'The Truth is Out There\n' == 'e Truth is Out There\nTh'
E         - The Truth is Out There
E         ? --
E         + e Truth is Out There
E         + Th
tests\test_integrations.py:243: AssertionError
```
Some people, when confronted with a problem, think, “I know, I’ll use threads,” and then two they hav erpoblesms.

**Comment by gforsyth** [comment]
Oof, and it hit Circle on 3.5 this time...

**Comment by scopatz** [comment]
I think this was not ulimately the correct solution.

**Pull request closed without merging**
