### PR TITLE
Fix f-string parsing in Python 3.9

### LINKED ISSUE #3865: f-string with env vars raises syntxc error in 0.9.23 under Python 3.9
f-strings with env vars in expressions give an error. When you type into the repl

    f"hallo {$PATH}" 

you get an error:

_SyntaxError: <xonsh-code>:1:0: f-string: invalid syntax_

### xonfig

<details>

```
+------------------+-----------------+
| xonsh            | 0.9.23          |
| Python           | 3.9.0           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | None            |
| shell type       | prompt_toolkit  |
| pygments         | None            |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
| on jupyter       | False           |
| jupyter kernel   | None            |
+------------------+-----------------+

```

</details>

### PR DESCRIPTION
**Pull request by laloch**
The f-strings parser is very sensitive to changes in the textual representation of the exceptions raised by the Python parser. There seems to be a bug introduced in Python 3.9 causing the exception text to be terminated by an extra newline character.

Fixes #3865

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks @laloch!

**Comment by tirkarthi** [comment]
@laloch Is the issue related to xonsh or something that happened in Python 3.9 that caused this? If you have a reproducer that explains the changes in Python 3.9 with respect to this it would be helpful to know if this is an upstream Python 3.9 bug. 

Thanks.

**Comment by laloch** [comment]
@tirkarthi yeah, it's an upstream change that made `text` field of `SyntaxError` exception object newline terminated. It does not make much sense, but I'm not going to file a bug report just bacause of that.

**Comment by tirkarthi** [comment]
Thanks @laloch

**Pull request merged**
