### PR TITLE
Add missing word in text on xontrib

### PR DESCRIPTION
**Pull request by tbekolay**
Noticed a missing word in the config wizard as I was going through it. Hopefully the first of many xonsh contributions from me!

### CODE REVIEW

**Comment by adqm** [comment]
Thanks for the patch, @tbekolay!  And welcome!

**Comment by tbekolay** [comment]
Thanks!

**Comment by scopatz** [comment]
Thanks a million @tbekolay! Also thanks a ton for coming to the talk!  Sorry we didn't get a chance to hangout at PyCon :(

**Comment by tbekolay** [comment]
No problem! And no worries, there will be many more opportunities I'm sure :)

**Pull request merged**
