### PR TITLE
Fix issues #2584 and #2430

### PR DESCRIPTION
**Pull request by jmcrawford45**
Fix issues #2584 and #2430

### CODE REVIEW

**Comment by jmcrawford45** [comment]
Any advice on fixing the build_black failure? From the test output, it's not clear what the issue is.

**Comment by jmcrawford45** [comment]
@scopatz after the black format changes, the AppVeyor build is failing on Python36. I don't think the format changes should be affecting the build. Perhaps this was an intermittent failure? Help would be appreciated.

**Comment by gforsyth** [comment]
Hey @jmcrawford45 -- thanks for putting this in!  The Appveyor failure is a known intermittent issue and not related to this PR as you suspect.

It also looks like `black` was updated to handle [Numeric literals](https://github.com/ambv/black#numeric-literals) since we used it to reformat everything.  I'll open an issue to pin the version of `black ` we're using so this doesn't just bite whomever happens to open a PR after there's a new version of `black` released that changes something.

Thanks again for this!

**Comment by scopatz** [comment]
Thanks again @jmcrawford45!

**Pull request merged**
