### PR TITLE
Add python 3.9 to CI on an experimental basis

### PR DESCRIPTION
**Pull request by AstraLuma**
On the request of @laloch 

I have concerns about the conda availability of 3.9?

### CODE REVIEW

**Comment by laloch** [comment]
That's why I asked whether it's possible or not :wink:

**Comment by carmenbianca** [comment]
#3928 probably fixed this.

**Comment by scopatz** [comment]
Yeah, this can probably be closed

**Comment by gforsyth** [comment]
Closing this out as 3.9 was added to CI elsewhere.  Thanks for the work here @AstraLuma !

**Pull request closed without merging**
