### PR TITLE
xonfig colors preview

### PR DESCRIPTION
**Pull request by funkyfuture**
let's users set an argument to preview a color palette, eg `xonfig colors monokai`.

----

(propably should be moved to an issue)

i noticed in the chat that an extension of `xonfig styles` was discussed. i could amend that, provided there's an agreed feature set. i can come up with two proposals:

`xonfig style list` (like `styles`), `xonfig style set <name>`, `xonfig style unset`

or 

`xonfig get color_style`, `xonfig set color_style <name>`, `xonfig set color_style`

whether to store to `xonshrc` or `config.json` could be selected by switches. and by a setting in one of them.

is there already an api to manipulate the config files?

### CODE REVIEW

**Comment by melund** [comment]
Good idea. I have been dragging this snippet around in my `.xonshrc` file which does the same kind of preview
```
from xonsh.tools import print_color
from xonsh.xonfig import _tok_colors
def show_style(stylename):
    oldstyle, $XONSH_COLOR_STYLE = $XONSH_COLOR_STYLE, stylename
    s =  builtins.__xonsh_shell__.shell.styler._smap
    print_color(_tok_colors(s,100))
    $XONSH_COLOR_STYLE  = oldstyle
````

**Comment by melund** [comment]
I was thinking. When previewing the style it may be more convenient to see a colored xonsh code snippet instead of all the pygments tokens.

**Comment by funkyfuture** [comment]
ah, so `_smap` it is. (the docstring of `XonshStyle` says manipulating its `style_name` would do the job, but doesn't. is it a bug?)

i think both, full palette and snipped, preview are legit.

**Comment by scopatz** [comment]
+1 to this, but I think @melund should handle it!

**Comment by melund** [comment]
@funkyfuture Sorry for being slow at looking at this. I will try one of the coming days. Anyway I thing I kind you first suggestion on the cli interface

**Comment by melund** [comment]
The  colors styles are implemented in several layers in ChainMap. `_smap` is the pygments styles. That is what was most interesting for me when fixing the colors on Win. I think it is OK to show the entire thing: `builtins.__xonsh_shell__.shell.styler` as we currently do. I just think it is important to also show some coloured snippets. That would be really usefull to select a good style

**Comment by gforsyth** [comment]
Hey @funkyfuture -- this has conflicts with master now.

**Comment by funkyfuture** [comment]
so, is this supposed to be merged?

**Comment by gforsyth** [comment]
I'm just trying to gauge where people are on some of the stalled pulled requests.  To my knowledge, there's no built in way in xonsh to quickly take a peek at what a new style looks like

**Comment by funkyfuture** [comment]
my impression is that @melund was delegated to care about this here.

**Comment by scopatz** [comment]
Delegated is probably too strong of a word.  But @melund knows the most about what looks good in Windows, so I defer to him on this stuff.

**Comment by melund** [comment]
@funkyfuture the PR is very welcome. I think @scopatz was talking about reviewing the PR when he said it was delegated to me.  I still think this feature would be really useful, so feel free to finish it if you feel like it.

**Comment by funkyfuture** [comment]
rebased onto master.

**Comment by gforsyth** [comment]
Hey @funkyfuture -- this looks good to me! Just the one issue with the xonfig parser duplication.

**Comment by funkyfuture** [comment]
thanks for spotting. fixed.

**Comment by gforsyth** [comment]
Ok, looks good!  Thanks @funkyfuture!

**Pull request merged**
