### PR TITLE
Remove test reordering in pytest plugin

### PR DESCRIPTION
**Pull request by melund**
The xonsh pytest plugin no longer messes up the test order for pytest. 
The original attempt to run xsh test first was a workaround 
for bug where certain test would not run after each other. This workaround
is no longer needed. 

fixes: #3380

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks @melund! It looks like there are a lot of test failures now :cry:

**Comment by melund** [comment]
Ahh. So we still have problems with the test suite and the fact some test can't run after each other. I was hoping it was fixed. 

Anyway, I reimplement the ordering in more predictable way, so we can still close #3380

**Comment by scopatz** [comment]
This looks great to me! Thanks!

**Comment by andry81** [comment]
I don't see how this changes the reorder. On mine side nothing has changed. I just rewrited `pytest_plugin.py` and saw the same order.

**Comment by melund** [comment]
@andry81 Maybe you reiterate what the problem was. 

You are right that it still reorders the tests by moving the `test_*.xsh` files first. That is unfortunately necessary because the fixtures used in the normal xonsh `test_*.py` files doesn't clean up after them self. Thus, the `test_*.xsh` files can't run after some of those tests. 

I thought the problem was a random order of the tests. I could see how the old implementation could cause a random order. Now it should only move the `xsh` test first.

**Comment by andry81** [comment]
> That is unfortunately necessary because the fixtures used in the normal xonsh test_\*.py files doesn't clean up after them self. Thus, the test_\*.xsh files can't run after some of those tests.

Why do you need to change the test order to fix tests? May be the problem was in a badly designed tests?

> I thought the problem was a random order of the tests. I could see how the old implementation could cause a random order. Now it should only move the xsh test first.

That behaviour was before the change.

**Comment by melund** [comment]
> Why do you need to change the tests order to fix tests? May be the problem was in a badly designed tests?

Sure. The fixtures which emulate a xonsh environment in pytest is a bit extensive. I don't know why it doesn't clean up nicely. I suspect it is pytest problem, but I really don't know. I hope this change fixes the most important things for you.

**Comment by andry81** [comment]
> I hope this change fixes the most important things for you.

But is does not fix the initial problem. And actually I not much care, I just don't relie on pytest collection phase, instead I run each test in a separate pytest process to avoid any problems with plugins.

**Comment by melund** [comment]
@andry81 Sorry, but what was the initial problem. I can see that a randomization of the tests would be a problem, but I can't see that moving certain test first is a problem?

**Comment by andry81** [comment]
> @andry81 Sorry, but what was the initial problem. I can see that a randomization of the tests would be a problem, but I can't see that moving certain test first is a problem?

Under the `random tests order` I've meant the dependency on something else than on a file name or on a test case name. What the kind of randomization is not actually matter because externally it is observable as a "random" order instead of predefined order by the pytest.

**Comment by melund** [comment]
Ok. But what did break for you? Currently, the order is still kept within the group of all `test_*.py` files, and the `test_*.xsh` files

**Comment by andry81** [comment]
> Ok. But what did break for you? Currently, the order is still kept within the group of all `test_*.py` files, and the `test_*.xsh` files

the pytest order without plugin:
```
01_test.py -> test_01_foo()
02_test.xsh -> test_02_foo()
```
with plugin:
```
02_test.xsh -> test_02_foo()
01_test.py -> test_01_foo()
```

**Comment by melund** [comment]
Sorry @andry81 I am bit slow here. But I thought it only ran the `test_*.xsh` if the plug-in was installed. So how did you see the different ordering without the plug-in. 

Also, what does the fact that `xsh` tests run first break?

**Comment by andry81** [comment]
> Sorry @andry81 I am bit slow here. But I thought it only ran the `test_*.xsh` if the plug-in was installed. So how did you see the different ordering without the plug-in.

If you create .py and .xsh tests in the same directory, then pytest will run both.

> Also, what does the fact that xsh tests run first break?

Because it should not in first place. Pytest has it's own order for that by name of a test case function. Plugin changes the default pytest order.

**Comment by andry81** [comment]
> But I thought it only ran the `test_*.xsh` if the plug-in was installed.

And I think you should not do like that, because it may break name conventions has configured somewhere else except of your plugin code:
http://doc.pytest.org/en/latest/example/pythoncollection.html#changing-naming-conventions

**Pull request merged**
