### PR TITLE
rm -i and cmake fixes

### LINKED ISSUE #3025: [regression] `rm -i` prompt is failing (again)
### xonfig

<details>

```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.8.10          |
| Python           | 3.7.2           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.8           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.3.1           |
| on posix         | True            |
| on linux         | True            |
| distro           | arch            |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

</details>

## issue

Looked through the old issues and it seems like this problem should be solved. So this might be a regression.

```
$ xonsh --no-rc
$ touch file1 file2 file3 file4
$ rm -i file*
/usr/bin/rm: remove regular empty file 'file1'? /usr/bin/rm: remove regular empty file 'file2'? /usr/bin/rm: remove regular empty file 'file3'? /usr/bin/rm: remove regular empty file 'file4'? /usr/bin/rm: error closing file
```

I checked that `rm` is not aliased to anything else in Bash. I also tried with `xonsh --no-rc --shell-type readline` with the same result. Finally, setting `$XONSH_STORE_STDOUT` to True or False makes no difference.

### versions

<details>

```
$ rm --version
rm (GNU coreutils) 8.30
$ uname -a
Linux 4.20.8-arch1-1-ARCH #1 SMP PREEMPT Wed Feb 13 00:06:58 UTC 2019 x86_64 GNU/Linux
```

</details>

### PR DESCRIPTION
**Pull request by scopatz**
This reverts the empty oldmask change because it was causing too many problems. This builds on #3026. It should fix #3025 and #3020.  However it will reopen #3003. However, I think this is a reasonable trade off for the time being.  I have spent days trying to figure this out to no avail. It might be best to wait for an async subproc / jobs refactor once we drop 3.4 support.

### CODE REVIEW

**Comment by scopatz** [comment]
@xonsh/xore - I think that this is ready for review

**Comment by melund** [comment]
It looks like it includes stuff from the previous PR. Anyways this is good to go in.

**Comment by scopatz** [comment]
Yes, thanks!

**Comment by laerus** [comment]
hey. when are we dropping 3.4 support?

**Comment by scopatz** [comment]
In a couple of weeks.  v3.4 reaches end-of-life on March 16th: https://devguide.python.org/#status-of-python-branches

**Pull request merged**
