### PR TITLE
Attempted fix for PermissionError and ProcessLookupError on Cygwin

### PR DESCRIPTION
**Pull request by adqm**
This is the first attempt at a fix for the `ProcessLookupError` and `PermissionError` exceptions under Cygwin (discussed in #541).

@OllieTerrance, @ellocogato, @jivanyatra: would you mind testing this out?  As I mentioned, I am unable to reproduce the issue.

### CODE REVIEW

**Comment by scopatz** [comment]
Code looks good to me, thanks for really pushing on cygwin @adqm!

**Comment by OllieTerrance** [comment]
This looks good -- I can still get a `ProcessLookupError` on master, but fixed with this patch.  :+1:

**Comment by adqm** [comment]
Okay, I think this is ready for another look, too, @scopatz!  Some comments in #514, and seems to be confirmed working.

**Comment by scopatz** [comment]
Looks great thanks!

**Pull request merged**
