### PR TITLE
Initial CI for Python 3.8

### PR DESCRIPTION
**Pull request by scopatz**
Here goes nothing!

### CODE REVIEW

**Comment by scopatz** [comment]
Just touches CI.  No news needed

**Comment by scopatz** [comment]
CC @xore - doesn't really do much because most platforms don't support it, but it is here.

**Comment by scopatz** [comment]
Closes #3118

**Comment by gforsyth** [comment]
Hey @scopatz -- sorry for the delay!  This looks good -- can you merge/rebase from master to clear the conflicts?

**Comment by scopatz** [comment]
Done! Thanks for the reminder

**Comment by gforsyth** [comment]
Thanks, @scopatz !

**Pull request merged**
