### PR TITLE
Fix missing completions

### PR DESCRIPTION
**Pull request by melund**
This fixes the missing completions in https://github.com/xonsh/xonsh/issues/1201

If any of the completions needs to be quoted then all completions gets quoted.

### CODE REVIEW

**Comment by gforsyth** [comment]
Hey @melund -- this breaks a bunch of stuff on my system.  If I do `cd <TAB>` the only two options are `.` and `..` and it also seems to interfere with both fuzzy matching and subsequence matching

**Comment by melund** [comment]
Weird. I don't see that effect. Maybe we better have @adqm to take a look at my fix. Maybe something more is needed.

However, I did find another instance of env.defaults... So a fix is on it way for that.

**Comment by gforsyth** [comment]
Super weird:  I just noticed that the behavior I described only occurs in my home directory...

**Comment by gforsyth** [comment]
And again, I was wrong about it messing with subsequence matching -- that was just some weird fluke

**Comment by gforsyth** [comment]
Ahh, ok, it's not only my home directory, it's any directory that contains a folder that has a space in the name

**Comment by melund** [comment]
Ahh. I see it too. I guess, `.` and `..` are not getting quoted like the rest of the completions and prompt_toolkit then only presents them.

**Comment by melund** [comment]
I guess we should wait with merging this until we hear from @jonathanslenders that this is actually the intended behaviour. Must the completions be quoted in the same way.

**Comment by melund** [comment]
Well. @jonathanslenders just confirmed that this shouldn't really happen. https://github.com/jonathanslenders/python-prompt-toolkit/issues/320#issuecomment-226318126

So I guess this PR should just be closed.

**Comment by adqm** [comment]
This branch seems to fix things (at least for me).

@jonathanslenders released a new version that had a supposed fix, but even with that update, I am not seeing the completions unless I am running from this branch.  @melund, are you having similar experience?

**Comment by gforsyth** [comment]
Still not working for me on this branch.  In fact now, in a directory that contains a folder with a space in the name, doing `cd <TAB>` completes to a single quote `'` and then offers no further options.

**Comment by melund** [comment]
Ahh. Now I spotted the real error. The quoted directories are stripped by https://github.com/xonsh/xonsh/blob/master/xonsh/completers/path.py#L280

I completely rebased with this new fix.

@adqm and @gforsyth Can you see this makes a difference for you?

**Comment by gforsyth** [comment]
woohoo!  That fixed it on my end, @melund!

**Comment by adqm** [comment]
Ah, yes!  That would make sense.

I'm not sure that is quite the right fix (we could have `r"` strings, for example).  I think the real right thing might be either to try a regex match to see if something is a string (happy to provide that regex if it's helpful) or to try to `ast.literal_eval` everything before the `os.path.isdir` check.

**Comment by melund** [comment]
Well. `ast.literal_eval` doesn't work well on windows when filenames ends with backslash. 

```
snail@sea C:\ $ ast.literal_eval('"Windows\\"')                                                                                                    env:x py:3.5.1 b:quoted_path_completions
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
  File "<unknown>", line 1
    "Windows\"
             ^
SyntaxError: EOL while scanning string literal
```

You guys are welcome to finish it. Otherwise, it will have to wait until tomorrow night.

**Comment by melund** [comment]
@adqm Does this seem right to you. It should ensure that the first and last quotes are the same and allow for a `r"` `u"` and `b"` strings.

**Comment by adqm** [comment]
I think we actually need something a bit more complicated (I think this one will let certain things through in a way such that the groups don't quite capture what we need, mainly because `q2` can be empty).

Actually, there may be an easier way.  Although it's currently "private" and not well documented (both my fault), the `_path_from_partial_string` function in `xonsh.completers.path` can actually do this.  It will return `None` in the case that something isn't quoted, and if all it contains is the repr for a string, it should return a tuple that has the contents of that string in position 1.

So I think a little check like the following might work:

```
from_partial_string = _path_from_partial_string(original)
if from_partial_string is None:
    real_name = original
else:
    real_name = from_partial_string[1]
```

and then you can do the `isdir` check on `real_name`.

This may or may not be easier than tweaking the regex to get it right.

**Comment by melund** [comment]
I think that is much nicer. But can you give me an example where the regex would fail?

**Comment by melund** [comment]
If I for example have folder called `'bad` which is then quoted as `"'bad"` then `_path_from_partial_string()[1]` returns `bad` where as the regex gives me: `'bad`

**Comment by adqm** [comment]
The one that jumps out is that it misses triple-quoted strings.

I had thought that it might fail for other kinds of strings, too, but it looks like it is catching all of those (at least the cases I am throwing at it).  I think it wouldn't work well if we were looking at strings more generally or using it to tokenize strings that might be invalid (it allows a bare `'` inside of a string wrapped in `''`, for example), but for the purpose we're using it here (where there is just a single validly-formatted string and nothing else), it seems to hit all the important cases.

It looks like it also can't catch an empty string (though I think that is fine because an empty string can't be a directory's name).

**Comment by melund** [comment]
I can probably add triple quoted strings

**Comment by adqm** [comment]
> If I for example have folder called 'bad which is then quoted as "'bad" then _path_from_partial_string()[1] returns bad where as the regex gives me: 'bad 

Ah yes, that is true.  I guess working with `_path_from_partial_string` might be harder than I had thought...

**Comment by adqm** [comment]
In a separate project I had used:
```
SINGLE_STRING = r"'((\\(.|\n))|([^'\\]))*'"
DOUBLE_STRING = r'"((\\(.|\n))|([^"\\]))*"'
TRIPLE_SINGLE_STRING = r"'''((\\(.|\n))|([^'\\])|('(?!''))|\n)*'''"
TRIPLE_DOUBLE_STRING = r'"""((\\(.|\n))|([^"\\])|("(?!""))|\n)*"""'
```

and then combined them with something like:

```
strings = (SINGLE_STRING, DOUBLE_STRING, TRIPLE_SINGLE_STRING, TRIPLE_DOUBLE_STRING)
STRING_MATCH = "[bBrRuU]*" + '(' + '|'.join(strings) + ')'
```

In that case, I hadn't needed to grab the _insides_ of the strings, so this could be modified to use named groups for the innards in `SINGLE_STRING`, `DOUBLE_STRING`, et al.

Then again, if your approach can be modified to account for triple-quoted strings, that might be better.


-------------

That said, there _is_ actually a function in `xonsh.tools` that can do this: `check_for_partial_string`.  There you can check not only whether a string was started, but also whether it was ended.  By looking at the first two elements in the return tuple there, it should be pretty easy to figure out whether we had a fully-formed string.  To me, that beats regex hacking :)

**Comment by adqm** [comment]
(not only because it avoids some painful regex hacking, but also because it avoids duplicating a bunch of code).

**Comment by adqm** [comment]
Also, I'm boarding a plane now, so I'll be AFK for a bit.  But happy to talk more once I have an Internet connection again.

**Comment by melund** [comment]
Ok. It was easy to add triple quotes to the regex. I will have to look at `check_for_partial_string` later this week.

**Comment by scopatz** [comment]
Thanks for putting this in @melund!

**Comment by melund** [comment]
I think I found a bug in this. So wait until I got this sorted.

**Comment by melund** [comment]
So I finally came up with a regex that worked `(?:[r]?(?P<q>"|'|"""|'''))(?:(?!(?P=q))(.+)|)(?:(?P=q))$` just to realize that it could be done in a much simpler way. 

I added a filter function to `complete_path` which is called before quoting. @adqm Is this a reasonable solution?

**Comment by gforsyth** [comment]
Hey @melund -- I'm horrified of and impressed with your regex.  
All dirs with spaces are showing up in the completion list -- do we want them to be sorted so they appear within the other folders?  As it  is, they sit at the top of the list of possible completions (before `../` and `./`)

**Comment by melund** [comment]
> All dirs with spaces are showing up in the completion list -- do we want them to be sorted so they appear within the other folders? As it is, they sit at the top of the list of possible completions (before ../ and ./)

Definitely :)  Already a separate PR #1249

**Comment by gforsyth** [comment]
No wonder I was so confused. I could've sworn you had already added in the sorting but I thought it was in this pr and couldn't find it.  OK, merging in now

**Pull request merged**
