### PR TITLE
Create a pre-commit hook for black

### PR DESCRIPTION
**Pull request by seanfarley**
After sitting next to @gforsyth and seeing him have broken tests due to not running `black`, he mentioned [pre-commit](https://pre-commit.com) and I was _hooked_[1]. So, I put it into a PR and sent it up.

[1] @scopatz and @gforsyth have been making terrible puns all week.

### CODE REVIEW

**Comment by astronouth7303** [comment]
What on earth is `pre-commit`?

**Comment by scopatz** [comment]
Seems like it is this https://pre-commit.com/

**Comment by scopatz** [comment]
@seanfarley - I assume these are ignored if you don't have `pre-commit` installed?

**Comment by scopatz** [comment]
CI fixes here: #3230

**Comment by seanfarley** [comment]
Oops, sorry, I didn't mean to leave the question not answered! Got distracted during the sprint :-(

Yes, it's pre-commit.com (linked to in my original comment) and does nothing at all unless `pre-commit install` is run. Though, this is my first time using pre-commit so please correct me if I'm wrong!

**Comment by seanfarley** [comment]
Thanks for the appveyor fixes! I totally missed those files.

Do you want a follow-up PR to consolidate the requirements files?

**Comment by scopatz** [comment]
No worries! And thanks for the answer.  And no need to consolidate the requirements

**Pull request merged**
