### PR TITLE
Vendore deps

### PR DESCRIPTION
**Pull request by jnoortheen**
- now it will be easy to upgrade vendored dependencies

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks for this massive effort @jnoortheen! I thought we wanted to get rid of vending anything but PLY and instead use the `xonsh[full]` install procedure. Maybe I missed a discussion though?

**Comment by jnoortheen** [comment]
> Thanks for this massive effort @jnoortheen! I thought we wanted to get rid of vending anything but PLY and instead use the `xonsh[full]` install procedure. Maybe I missed a discussion though?

Yes that is good. Is there any timeline/version planned to drop vended_ptk ?

**Comment by scopatz** [comment]
I think whenever someone wants to put in a PR and update the docs :wink:

**Comment by jnoortheen** [comment]
OK then I will close this PR and will open one to remove vended_ptk from the xonsh source. 

One other thing, I want to vendor my lib https://github.com/jnoortheen/arger within xonsh to make redundant alias functions/CLIs to be more pleasant to write and type check with mypy . Also this will enable us to generate autocompletions from the parsers itself, instead of updating manually. what do you think ? I made it for this purpose without depending on 3rd party libs.

**Comment by gforsyth** [comment]
I think I missed a few conversations -- we recently started including PTK in `xonsh` itself -- I don't have strong feelings one way or the other, but if we're now going to remove it (or not!) we should probably stick to that decision for a bit.  

Also pinging @halloleo since they were also looking at updating the vended version of `xonsh`

**Comment by jnoortheen** [comment]
Yes I am also fine with either cases. This is just to make the vendoring painless. If we are going to keep it vendored, then it should be easy to upgrade to new versions.

**Comment by halloleo** [comment]
I probably don't understand the `git` mechanics correctly, but I though in the `Makefile` is so far _no_ entry for PTK, which (as far as I can see) means PTK is vendored by copying in, not automaticlly via a `git pull`.

Anyway, do these efforts here make vendoring PTK via  #3956 obsolete?

**Comment by jnoortheen** [comment]
The idea is to have an easy way to upgrade to vendored dependencies and pin the versions. If you change the deps.txt to 3.0.3 and rerun the command, there will not be any change at all.

The Makefile has ply vendoring not for ptk.

**Comment by halloleo** [comment]
Thanks @jnoortheen. Ok, so the vendoring of PTK is done through the new `task.xsh` file, while the vendoring of PLY is done through the Makefile, right? Plus PLY is included via git's `subtree` command, but PTK is included via `pip`. 

Looks a bit like a mess to me, but maybe this is the first step to moving everything over to `task.xsh`? I'm not an expert in git, so I don't know whether subtree-ing is better or worse than including pip'ed (i.e. copied) files...

**Comment by jnoortheen** [comment]
> Thanks @jnoortheen. Ok, so the vendoring of PTK is done through the new `task.xsh` file, while the vendoring of PLY is done through the Makefile, right? Plus PLY is included via git's `subtree` command, but PTK is included via `pip`.
> 
> Looks a bit like a mess to me, but maybe this is the first step to moving everything over to `task.xsh`? I'm not an expert in git, so I don't know whether subtree-ing is better or worse than including pip'ed (i.e. copied) files...

Yes you got it right. 

PLY is another matter. Its pypi package doesn't have all the files. Also I dont think it will receive any future release. Last one was in [2018](https://pypi.org/project/ply/) . The author has created a new library [sly](https://github.com/dabeaz/sly) though.

**Comment by jnoortheen** [comment]
@gforsyth can we decide on this? I favour removing the vendored ptk. But was there any reason to add it in the first place?

**Comment by gforsyth** [comment]
Also, though, I think if we have a reason to vend other dependencies in the future (although I would like to avoid that) that the `task.xsk` laid out here seems like a nice way to do that.  

`ply` as it exists today is intended to be a vended dependency.

**Comment by jnoortheen** [comment]
@gforsyth  Ok then I shall proceed closing this and create a PR to remove the `vended_ptk`?

**Comment by gforsyth** [comment]
> @gforsyth Ok then I shall proceed closing this and create a PR to remove the `vended_ptk`?

Yeah, let's do that and if someone screams we can reconsider.

**Pull request closed without merging**
