### PR TITLE
Make readline completes to max prefix

### PR DESCRIPTION
**Pull request by mitnk**
Trying address #1397. May not be the right way, but open it here for discussions.

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks for putting this in @mitnk! It seems like this is failing on linux for some reason.  Is this related to #1899 at all?

**Comment by gforsyth** [comment]
Just a flake error

FLAKE8-check(ignoring E122 E402) _______________________
/home/ubuntu/xonsh/xonsh/completers/path.py:139:9: E128 continuation line under-indented for visual indent

**Comment by mitnk** [comment]
@scopatz I'll check the failed cases; no, it is not related with #1899 which is fixing readline side issue, and this PR is for the procedures of computing paths in xonsh before hand out to readline.

@gforsyth Thanks. I'll check the lint stuff, when we feel the direction of this PR is ok.

**Comment by mitnk** [comment]
Putting more details here

say we have two dirs:
```
$ ls -F
foo/     foo bar/
```
Before this commit:
```
$ cd f<TAB>
(Nothing happened)
$ cd f<TAB><TAB>
$ cd f    # <---- no further completes 
'foo bar/'  foo/
````=
After this commit:
```
$ cd f<TAB>
$ cd 'foo  # <---- completes to 'foo by readline

$ cd 'foo<TAB><TAB>
'foo bar/'  'foo/'
```

**Comment by scopatz** [comment]
I think @adqm and/or @gforsyth should handle this one, since my mind is pretty far from completions right now :)

**Comment by adqm** [comment]
Haven't had a chance to test this, but how does it work if we are already completing something with a starting quote other than the default single quote `'`?

E.g., if we do `r"""something with spa<TAB>`, will everything get the right `r"""` as start and `"""` as end, to make everything have the same prefix?

**Comment by mitnk** [comment]
@adqm it seems so:

```
$ cd r"""f<Tab>
$ cd r"""foo<Tab><Tab>
r"""foo bar/"""  r"""foo/"""

$ cd r'foo<Tab><Tab>
r'foo bar/'  r'foo/'

$ cd r'''foo<Tab><Tab>
r'''foo bar/'''  r'''foo/'''

$ cd 'foo<Tab><Tab>
'foo bar/'  'foo/'
$ cd "foo<Tab><Tab>
"foo bar/"  "foo/"
```

**Comment by adqm** [comment]
I am totally on board with this; makes good sense to me and makes completion a lot more usable in readline.  I haven't tried with PTK, but I assume this is a win there as well, or at least a break-even.

Not sure which way is actually faster, but the `needs_quotes` line could be refactored to:
```
need_quotes = any(re.search(PATTERN_NEED_QUOTES, x) or (backslash in x and slash != backslash) for x in paths)
```

Definitely getting rid of the `[]` in those expressions will speed things up (making them generator expressions instead of list comprehensions).  It's also likely that having just the one generator expression is going to be faster, but I'm not 100% on that.

**Comment by mitnk** [comment]
@adqm agreed on the suggestions, thanks. new commit added.

**Comment by gforsyth** [comment]
Hey @mitnk -- this seems ready to go.  Could you add an entry in the `news` folder?  Instructions are available here: https://github.com/xonsh/xonsh/blob/master/CONTRIBUTING.rst#changelog

**Comment by mitnk** [comment]
@gforsyth added, thanks.

**Comment by gforsyth** [comment]
Great.  Thanks again, @mitnk!

Oddly, this seems to have no effect on PTK, but it's not a regression in any case and it's a big improvement on the readline side.

**Pull request merged**
