### PR TITLE
Ap/history

### PR DESCRIPTION
**Pull request by jnoortheen**
## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Review by daniel-shimon — APPROVED** [review]
Awesome! Thanks!

**Comment by jnoortheen** [comment]
@daniel-shimon please check the other PRs. The tests pass locally. I will fix this later.

**Comment by jnoortheen** [comment]
It seems to be related to amalgam.

**Comment by jnoortheen** [comment]
@daniel-shimon you can check now. Now the tests are passing

**Review by daniel-shimon — APPROVED** [review]
Awesome! Thanks!

**Pull request merged**
