### PR TITLE
attempt at new tab PWD for vte

### LINKED ISSUE #1253: preserve path in the new shell tab
is there a way to preserve path in the new tab of gnome-shell for example by any chance?

### PR DESCRIPTION
**Pull request by scopatz**
Hey @dotsdl @uy-do-or-die can you try this and let us know! You need to add this to the front or end of your prompt, to get this to work:

Try `$PROMPT = '{new_vte_cwd}' + $PROMPT` and if that doesn't work, then please try `$PROMPT = $PROMPT + '{new_vte_cwd}'`

This is an attempt to fix #1253

### CODE REVIEW

**Comment by dotsdl** [comment]
@scopatz I'll give it a shot now; thanks!

**Comment by scopatz** [comment]
Also, please try it on readline if it doesn't work on PTK for some reason.

**Comment by scopatz** [comment]
Thanks a ton!

**Comment by dotsdl** [comment]
Either option seems to work when I set `xonsh` as my user shell! Very nice @scopatz!

**Comment by dotsdl** [comment]
And it works just fine on PTK. :D

**Comment by scopatz** [comment]
@dotsdl Great!  I have updated this and changed the key name.  

This is a relatively small amount of actual code, so maybe it would be a good first one for @laerus to review and merge, if you are interested!

**Comment by scopatz** [comment]
ping on this one, if anyone can review and merge please :)

**Comment by laerus** [comment]
@scopatz oops missed that one, i'm trying to reproduce the issue but in terminator the pwd is preseved in new terminal tabs, can't setup my gnome-terminal in xfce atm, but i will try to reproduce it.

**Comment by scopatz** [comment]
@laerus This doesn't happen all the time on gnome-terminal either, so you may not be able to reproduce it.  I think it is OK to merge because @dotsdl (who had the problem) said it is fixed for him :)

**Comment by laerus** [comment]
merging then!

**Comment by shadow-light** [comment]
I can't get this to work with Tilix. Anyone know how to? I have `$PROMPT = $PROMPT + '{vte_new_tab_cwd}'` in `.xonshrc`. And these settings in Tilix:

image

Tilix has [their own instructions](https://gnunn1.github.io/tilix-web/manual/vteconfig/) regarding the issue which haven't resolved it for me either. New tabs just default to `~`.

**Comment by scopatz** [comment]
hmm that is weird.  I seems like Tilix wants you to source `/etc/profile.d/vte-2.91.sh`  and then call `__vte_osc7`.  As far as I can tell, `'{vte_new_tab_cwd}'` does exactly the same thing as that, with the exception that we are not URL-encoding the path.  Do you have characters on your absolute path name that would need to be url encoded?

**Comment by Flimm** [comment]
> I can't get this to work with Tilix. Anyone know how to? I have `$PROMPT = $PROMPT + '{vte_new_tab_cwd}'` in `.xonshrc`.

Putting `$PROMPT + '{vte_new_tab_cwd}'` in `.xonshrc` worked for me. I'm using `xonsh` in Ubuntu's repositories (Ubuntu 21.10) and Tilix.

**Pull request merged**
