### PR TITLE
docs: update for release activity

### PR DESCRIPTION
**Pull request by jnoortheen**
## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Review by gforsyth — COMMENTED** [review]
thanks @jnoortheen

**Review by gforsyth — APPROVED** [review]

**Comment by jnoortheen** [comment]
@gforsyth can you do a release? I do not have PyPI access

**Comment by gforsyth** [comment]
Yes -- tried to yesterday but I'm on a work trip and internet has been frustratingly spotty

**Comment by jnoortheen** [comment]
> And we'll also get you set up with PyPI access

Ok. My username on PyPI is same `jnoortheen` as github

**Comment by gforsyth** [comment]
New release is out, adding you to pypi now

**Pull request merged**
