### PR TITLE
fix: Fix wrong verification for the simple output, introduced by PR5072

### PR DESCRIPTION
**Pull request by xmnlab**
Fix the issue pointed by https://github.com/xonsh/xonsh/commit/2a63f1f875754d04d71a1f4937ce68312223ea3c#r121718023
The error was introduced by #5072

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Comment by xmnlab** [comment]
cc @dev2718

**Comment by xmnlab** [comment]
this PR is ready for review, thanks!

**Review by jnoortheen — APPROVED** [review]

**Comment by jnoortheen** [comment]
LKTM, Thanks @xmnlab !

**Comment by xmnlab** [comment]
thanks for the review @jnoortheen !

**Pull request merged**
