### PR TITLE
Invalidate code cache whenever the xonsh version changes

### PR DESCRIPTION
**Pull request by scopatz**
This should address #1649

### CODE REVIEW

**Comment by adqm** [comment]
Should this also happen is the Python version changes (`sys.version_info`), just in case?  (If I'm not mistaken, for example, 3.5.2 has a different magic number than 3.5.0-1, despite having the same cache filename, even in `__pycache__`s)

**Comment by scopatz** [comment]
@adqm - ahh yeah that is a good point. I'll add that.

**Comment by scopatz** [comment]
Done!

**Comment by melund** [comment]
Looks good.

**Pull request merged**
