### PR TITLE
Zombie

### PR DESCRIPTION
**Pull request by scopatz**
This fixes a couple of bugs that were preventing command pipelines with certain unthreadable commands (cough *vim*) from completing successfully.  This should address #2002

### CODE REVIEW

**Comment by gforsyth** [comment]
Ooooooooooooo

Awesome. This actually fixed a few other issues I was running into but hadn't reported yet because I couldn't figure out a reproducible example.

**Comment by gforsyth** [comment]
Also, I think when this goes in we can do a 0.5 release

**Comment by scopatz** [comment]
Awesome!

**Comment by gforsyth** [comment]
Thanks, @scopatz. I think a small stress test by @xonsh/core-developers on master now and if nothing major arises we can go ahead and start putting the 0.5 release together!

**Comment by scopatz** [comment]
Sweet! Sounds awesome!

**Comment by scopatz** [comment]
You give the word when you think it is ready.

**Comment by laerus** [comment]
+1

**Comment by scopatz** [comment]
@gforsyth - anything you think is still holding this up?

**Comment by gforsyth** [comment]
No, I think we're good to go.

**Comment by scopatz** [comment]
Ok great! I'll do the honors after lunch.

**Comment by gforsyth** [comment]
Awesome.  Then we can try out using doctr to build release and dev documentation!

**Pull request merged**
