### PR TITLE
control overriding of foreign aliases

### PR DESCRIPTION
**Pull request by laerus**
#1698

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks @laerus!

**Comment by scopatz** [comment]
Ahh, Ok I thought that this would run the other way. Basically that the new alias would override and only print a warning message if debug is on. I am happy with this though for the moment if you just want it merged in.

**Comment by laerus** [comment]
do we ever want foreign aliases to override xonsh aliases?

**Comment by laerus** [comment]
we can always add an envvar so the user can control what happens.

**Comment by scopatz** [comment]
Yeah, a new envvar is probably best

**Comment by laerus** [comment]
any good name for the envvar? i'm thiking something like $XONSH_OVERRIDE_ALIASES but this is kind of confusing.

**Comment by scopatz** [comment]
Maybe `FOREIGN_ALIASES_OVERRIDE`?

**Comment by laerus** [comment]
so if `$FOREIGN_ALIASES_OVERRIDE` is False then xonsh will ignore foreign aliases that clash with xonsh aliases, also i think False should be the default.

**Comment by scopatz** [comment]
Yep, that is what I think too

**Comment by laerus** [comment]
uh this deosn't work if i set `FOREIGN_ALIASES_OVERRIDE=True` in my .xonshrc,
cause i just realized that `load_foreign_aliases` is being called before .xonshrc has been parsed.

**Comment by scopatz** [comment]
Yeah, if you want this apply to the config file, you'd have to set this envvar in the "env" section of the config file.

**Comment by melund** [comment]
I think this needs #1716 merged first, or integrated into this.

**Comment by melund** [comment]
Cool. I think this is good to go.

**Pull request merged**
