### PR TITLE
Require whitespace for and/or tokens in subproc mode

### PR DESCRIPTION
**Pull request by scopatz**
This is meant to address #1921

### CODE REVIEW

**Comment by OJFord** [comment]
I don't recall if I tested others when reporting #1921, but I'm surprised if this doesn't affect keywords other than `and` & `or`? I'd have assumed a more general fix was required. Thanks for working on this though! 🙂  It continues to catch me out...

**Comment by scopatz** [comment]
No problem!

**Comment by scopatz** [comment]
I am actually a little surprised that this is sufficient too, but I will take it gladly :)

**Comment by melund** [comment]
Awesome. LGTM...

**Pull request merged**
