### PR TITLE
locked issue

### LINKED ISSUE #3699: KeyError `locked` in latest build of xonsh
I recently updated to the latest version of xonsh and also installed a bespoke branch of ptk2. When I did, I started getting the error on startup:

```
~ $ Exception in thread Thread-10:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/jaraco/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/history/__amalgam__.py", line 372, in run
    files = self.files(only_unlocked=True)
  File "/Users/jaraco/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/history/__amalgam__.py", line 426, in files
    if lj["locked"] and lj["ts"][0] < boot:
  File "/Users/jaraco/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 783, in __getitem__
    rtn = self._getitem_mapping(key)
  File "/Users/jaraco/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 767, in _getitem_mapping
    offset = self.offsets[key]
KeyError: 'locked'
```

I then re-installed the latest stable version of prompt_toolkit, but the error continues.

The prompt works after the error is emitted.

I have not tried troubleshooting further.

Given that others haven't reported this issue, I suspect it's somewhat localized to my environment (and history).

## xonfig

<details>

```
~ $ xonfig
+------------------+---------------------+
| xonsh            | 0.9.19              |
| Git SHA          | 74450cb5            |
| Commit Date      | Aug 9 13:27:55 2020 |
| Python           | 3.8.5               |
| PLY              | 3.11                |
| have readline    | True                |
| prompt toolkit   | 3.0.6               |
| shell type       | prompt_toolkit      |
| pygments         | None                |
| on posix         | True                |
| on linux         | False               |
| on darwin        | True                |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

</details>

## Expected Behavior

Prompt should startup without error.

### PR DESCRIPTION
**Pull request by scopatz**
Closes #3699

### CODE REVIEW

**Comment by scopatz** [comment]
@xonsh/xore - this is ready for review

**Comment by jaraco** [comment]
Looking good, but after this change, my shell instead emits:

```
~ $ Exception in thread Thread-10:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/jaraco/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/history/__amalgam__.py", line 372, in run
    files = self.files(only_unlocked=True)
  File "/Users/jaraco/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/history/__amalgam__.py", line 440, in files
    lj["ts"][1] or lj["ts"][0],
  File "/Users/jaraco/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 783, in __getitem__
    rtn = self._getitem_mapping(key)
  File "/Users/jaraco/.local/pipx/venvs/xonsh/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 767, in _getitem_mapping
    offset = self.offsets[key]
KeyError: 'ts'
```

**Comment by scopatz** [comment]
Ok thanks @jaraco - here is another fix for that issue

**Comment by jaraco** [comment]
Yep - that did the trick. Thanks!

**Comment by scopatz** [comment]
Awesome! This is ready for review again @xonsh/xore

**Comment by laloch** [comment]
I wonder how those attributes could ever be missing. They should always be passed to the history object initializer and stored immediately in the history file.

**Comment by scopatz** [comment]
Some sort of weird partial write maybe?

**Comment by laloch** [comment]
I can imagine, that this could happen due to concurrency between several Xonsh instances running (or rather starting) in parallel. The reproducibility of this particular error does, however, suggest, that @jaraco has one or more corrupted history files. I think we should rather handle the `KeyError` exception and ignore the affected file(s) altogether.

**Comment by scopatz** [comment]
Yeah, this is a minimal fix to get things working.  Happy to take suggestions on what to do in these cases

**Comment by jaraco** [comment]
After adopting this latest version, I was prompted about a very large history (65k) being over the gc limit (8k), so I ran the gc command to clean things up. I hope that limits the issues I encounter, and might have been a factor in the conditions leading to the corrupted history. I would prefer when there's corrupted history to retain as much as can be reasonably retained.

**Comment by laloch** [comment]
> I was prompted about a very large history (65k) being over the gc limit (8k)

Yeah, that's because the history garbage collection didn't work for quite a some time, so the old history didn't get deleted.

> I would prefer when there's corrupted history to retain as much as can be reasonably retained.

The JSON history is saved to per-session files, so if one o them gets corrupted, you only lose a history from single session.

**Review by BYK — APPROVED** [review]
This LGTM until we figure out the root cause.

**Comment by laloch** [comment]
Thanks @scopatz!

**Comment by scopatz** [comment]
Thanks All!

**Pull request merged**
