### PR TITLE
Use terminal width when centering text on welcome screen

### PR DESCRIPTION
**Pull request by melund**
No news item required

### CODE REVIEW

**Comment by gforsyth** [comment]
Hey @melund -- this looks good but has conflicts with master.

**Comment by scopatz** [comment]
Oh yeah, I fixed the typo last night before the merge :)

**Comment by scopatz** [comment]
refixed

**Comment by melund** [comment]
Thanks @scopatz. Feel free to merge.

**Comment by gforsyth** [comment]
Circle passed, despite what it's reporting.

**Comment by gforsyth** [comment]
Thanks, @melund!

**Pull request merged**
