### PR TITLE
Tests usrbinenv args update

### PR DESCRIPTION
**Pull request by jb-leger**
This PR fixes a bug shown by @carmenbianca in #3082.

### CODE REVIEW

**Comment by jb-leger** [comment]
I do not understand why tests fails.

**Comment by laloch** [comment]
I guess that it's somewhat misleading complaint about your news items file being empty.

**Comment by laloch** [comment]
AppVeyor failed to fetch build dependencies because of
```
Failed to establish a new connection: [Errno 11001] getaddrinfo failed
```

**Comment by gforsyth** [comment]
Thanks for putting this in @jb-leger ! Yay fixes!

**Pull request merged**
