### PR TITLE
ptk: Wrap selection with quotes/parens with $XONSH_AUTOPAIR

### PR DESCRIPTION
**Pull request by daniel-shimon**
nice

Supports `"`, `'`, `(`, `[`, `{`

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Comment by anki-code** [comment]
Looks great! How I can enable the selection feature? I tried to press Shift-Left with no result.

**Comment by daniel-shimon** [comment]
> Looks great! How I can enable the selection feature? I tried to press Shift-Left with no result in Konsole on Arch.

Is your prompt-toolkit updated?

**Comment by anki-code** [comment]
Yes, ptk 3.0.18

**Comment by daniel-shimon** [comment]
> Yes, ptk 3.0.18 and `xonsh --no-rc`.

hmm.. maybe try a different terminal emulator?
I know this works in kitty for example

**Comment by anki-code** [comment]
Trying kitty:
```python
bash
XONSH_AUTOPAIR=1 xonsh --no-rc
$XONSH_AUTOPAIR
# True
echo qwe
```
No wrapping with quotes.

**Review by anki-code — APPROVED** [review]

**Comment by daniel-shimon** [comment]
@anki-code we can continue at gitter :)

**Comment by anki-code** [comment]
It works for me on MacOS but have no wrapping in Linux:
* Konsole - no selection, no wrapping
* kitty - has selection, no wrapping
* xterm - has selection, no wrapping

**Pull request merged**
