### PR TITLE
Escape null bytes before Popen

### PR DESCRIPTION
**Pull request by scopatz**
This prevents the error listed in #1771.

### CODE REVIEW

**Comment by gforsyth** [comment]
Thanks for putting this in, @scopatz. 
The following works now:
```console
gil@bad_cat ~ 🐚  xonsh -c "/usr/bin/printf '__RESULT\\000'"
__RESULTgil@bad_cat ~ 🐚
```
but `exec-path-from-shell`, the annoying elisp emacs package that's the root of all this is running with `-l -i -c` and that's erroring out with

```console
gil@bad_cat ~ 🐚  xonsh -l -i -c "/usr/bin/printf '__RESULT\\000'"
Traceback (most recent call last):
  File "/home/gil/miniconda3/bin/xonsh", line 3, in <module>
    main()
  File "/home/gil/miniconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 20095, in main
    _failback_to_other_shells(args, err)
  File "/home/gil/miniconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 20059, in _failback_to_other_shells
    raise err
  File "/home/gil/miniconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 20093, in main
    return main_xonsh(args)
  File "/home/gil/miniconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 20127, in main_xonsh
    run_code_with_cache(args.command.lstrip(), shell.execer, mode='single')
  File "/home/gil/miniconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 3685, in run_code_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/home/gil/miniconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 3544, in run_compiled_code
    func(code, glb, loc)
  File "2564f9e42c844b4292bd10a7e66fb82f", line 1, in <module>
  File "/home/gil/miniconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 18833, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/home/gil/miniconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 18769, in run_subproc
    command = HiddenCommandPipeline(specs)
  File "/home/gil/miniconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 13238, in __init__
    if update_fg_process_group(pipeline_group, background):
  File "/home/gil/miniconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 13174, in update_fg_process_group
    return give_terminal_to(pipeline_group)
  File "/home/gil/miniconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 9231, in give_terminal_to
    os.tcsetpgrp(FD_STDERR, pgid)
OSError: [Errno 25] Inappropriate ioctl for device
```

Also, for some reason I can't get an unamalgamated traceback despite being in debug mode...

**Comment by scopatz** [comment]
This looks like a job control issue. It is probably a matter of fixing `give_terminal_to()` to be robust when we lie to it about being in interactive mode. Should be a simple try-except.

**Comment by gforsyth** [comment]
Adding `25` to the types of `OSError` we catch in `give_terminal_to()` does fix the issue.  There are other problems after that but they are on the emacs side of things and I don't have the patience or the intelligence to fix them right now.

**Comment by gforsyth** [comment]
Ahh, ok, nevermind. We shouldn't bother tricking `give_terminal_to()` -- that's better fixed on the emacs side, I think.

**Comment by gforsyth** [comment]
Thanks, @scopatz !  I'll put in a docs update to handle the emacs config stuff to match this.

**Comment by scopatz** [comment]
Thanks @gforsyth! We can and probably should make `give_terminal_to()` more robust as well.

**Comment by scopatz** [comment]
I put in a quick fix for that in #2272

**Pull request merged**
