### PR TITLE
Fix @$() subprocess operator

### LINKED ISSUE #2328: Syntax for *just* stripping last newline
`@$` is nice, but, oftentimes, you need everything to stay together as *one* argument, in which case the only way to do it is `@($(mycommand).rstrip('\n'))`. (Or at least for me, I often want it that way!) It'd be nice if there were a syntax akin to `@$` that just strips the ending newline, something that would be like bash's `$(my-command)` syntax.

### LINKED ISSUE #2755: Captured subprocess syntax issue
I do quite often find myself in need of running something like
```
gdb --pid=$(pidof krunner)                                                                                                                                                                                                                                      
....
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/xonsh/ptk/shell.py", line 138, in _push
    locs=None)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20084, in compile
    transform=transform)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20053, in parse
    tree, input = self._parse_ctx_free(input, mode=mode, filename=filename)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20153, in _parse_ctx_free
    raise original_error from None
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 20140, in _parse_ctx_free
    debug_level=(self.debug_level > 2))
  File "/usr/lib/python3.6/site-packages/xonsh/parsers/base.py", line 351, in parse
    check_contexts(tree)
  File "/usr/lib/python3.6/site-packages/xonsh/parsers/context_check.py", line 57, in check_contexts
    raise e
  File "<string>", line None
SyntaxError: can't assign to operator
```
In the above example the captured subprocess syntax `$(<expr>)` didn't get parsed well and I can't find a way around the issue other than `gdb @('--pid=' + $(pidof krunner).rstrip())`, which is, well, inconvenient.
Also, I feel that the `$()` operator should automagically .rstrip() the resulting string like, for instance, Bash does.
There's already issue #1453 opened regarding similar behavior of the `@()` operator. Feel free to mark this as duplicate of the #1453 if they're related.
## xonfig
```
+------------------+-----------------+
| xonsh            | 0.7.2           |
| Python           | 3.6.6           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 1.0.15          |
| shell type       | prompt_toolkit1 |
| pygments         | 2.2.0           |
| on posix         | True            |
| on linux         | True            |
| distro           | arch            |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

### LINKED ISSUE #3457: Unexpected newlines in @$(...) substitution
Seems to be related to #2021, at least in part. 

Whenever I run `docker stop @$(docker ps -aq)`, I receive a Docker error (`404 page not found`), which appears to be caused by the fact that Docker is not receiving a valid container image.

Further experimentation shows this happens with basically everything that uses `@$` notation, which [appears to go against documentation](https://xon.sh/tutorial.html#command-substitution-with) as well as what was mentioned in #2021. 

Am I missing something here?

## xonfig

<details>

```
$ xonfig
+------------------+----------------------+
| xonsh            | 0.9.13.dev1          |
| Git SHA          | 9f7ccc65             |
| Commit Date      | Oct 15 17:14:50 2019 |
| Python           | 3.7.6                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 2.0.9                |
| shell type       | prompt_toolkit2      |
| pygments         | 2.4.2                |
| on posix         | True                 |
| on linux         | False                |
| on darwin        | True                 |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

</details>

## Expected Behavior

Commands should be split properly and should execute normally, like Bash's own output:

```
$ ls $(ls)
1:

2:

3:

4:

5:
```

## Current Behavior

```
$ ls @$(ls)
ls: 1
2
3
4
5: No such file or directory
$ ls
1 2 3 4 5
```

`argv` view:

```
$ python -c "import sys; print(sys.argv)" @$(ls)
['-c', '1\n2\n3\n4\n5']
$ python -c "import sys; print(sys.argv)" @([i.strip() for i in $(ls).split()])
['-c', '1', '2', '3', '4', '5']
```

## Steps to Reproduce

1. Navigate to test directory - `cd @$(mktemp -d)`
2. Create test folders - `mkdir 1 2 3 4 5`
3. Run `ls @$(ls)`, observe failure

### PR DESCRIPTION
**Pull request by laloch**
See the trail in #3156.

Closes #2328
Closes #2755
Closes #3457

### CODE REVIEW

**Comment by gforsyth** [comment]
Hey @laloch -- I set up the github actions to only trigger on `push` for a reason I can't remember, I think that's why they aren't triggering.  You can either push up an empty commit, or we can try to add PRs to the list of trigger actions

**Comment by laloch** [comment]
I can try again, I did several pushes the last time and it didn't trigger the CI anyway.

**Comment by laloch** [comment]
You see? No CI for me :disappointed:

**Comment by scopatz** [comment]
Let's just get this merged.  I wonder @gforsyth if this is related to the fact that @laloch id pushing from a fork

**Comment by gforsyth** [comment]
It shouldn't, but I'll see if we need to add anything else to the config

**Comment by laloch** [comment]
It's no problem for me to keep testing.

**Comment by scopatz** [comment]
Yeah, but I want to cut a release today, and don't want to mix these two issues

**Comment by laloch** [comment]
So, now with #3511 merged in, should I try one last time and rebase to master?

**Comment by gforsyth** [comment]
> So, now with #3511 merged in, should I try one last time and rebase to master?

I would close and open one more new PR, and if that doesn't work, we'll just merge it

**Comment by laloch** [comment]
@gforsyth, OK, let's do it.
Closing to reopen in yet another PR.

**Pull request closed without merging**
