### PR TITLE
Remove "Try xonsh" and fix doctr release deploy

### LINKED ISSUE #2614: Remove 'try xonsh' from the docs
Probably isn't the friendliest experience for new users to have the broken "try it out" front and center on the main docs landing page. 

Should we take it out until there's a working solution?

### PR DESCRIPTION
**Pull request by gforsyth**
"try xonsh" link is non-functional and is likely disappointing to new users who
try to use it.

quick other doc-related fix to re-install xonsh before second `doctr deploy` to
make sure that documentation that is uploaded reflects the last tagged release.
If this works (and it should) then we can retarget the `xon.sh` cname to point to the root of `xonsh/xonsh-docs` gh-pages and it will auto-update release docs when we push up a new release.

Closes #2614

### CODE REVIEW

**Comment by gforsyth** [comment]
I don't think this needs a news item

**Comment by scopatz** [comment]
hmm is this supposed to deploy to http://xon.sh/dev ? Because that doesn't seem like it is working.

**Comment by scopatz** [comment]
Ok this is annoying:

* http://xon.sh 

is different than 

* https://xonsh.github.io/xonsh-docs/
* https://xonsh.github.io/xonsh-docs/dev/

Which appear to be the same, and 

* https://xon.sh/xonsh-docs/
* https://xon.sh/xonsh-docs/dev/

Do not exist!

**Comment by gforsyth** [comment]
I think `xon.sh` is still pointing at scopatz/xonsh-docs ...?

https://xonsh.github.io/xonsh-docs/ now shows 0.6.1 as the release and
https://xonsh.github.io/xonsh-docs/dev shows the current dev docs, so that bit is working

**Comment by scopatz** [comment]
Ahh you are right, now they are correct.  Hmm I guess I should just transfer the CNAME over and remove the scopatz/xonsh-docs repo.

**Comment by scopatz** [comment]
Ok Docs seem to be working now!

**Comment by gforsyth** [comment]
Woohoo!

**Comment by bestlem** [comment]
I still see the try it out non working screen on http://xon.sh

    traceroute xon.sh                                    
    traceroute: Warning: xon.sh has multiple addresses; using 192.30.252.153
    traceroute to xon.sh (192.30.252.153), 64 hops max, 52 byte packets

Soi iy l;ooks like DNS is not correct

**Comment by gforsyth** [comment]
Hey @bestlem -- the docs at http://xon.sh are pinned to the latest release ("stable" docs, if you will).  The docs reflecting the latest changes to master are available at http://xon.sh/dev

**Comment by scopatz** [comment]
I was hoping to do a release this weekend, so expect the "stable" docs to be updated soon.

**Pull request merged**
