### PR TITLE
Change !() to also capture background subprocesses

### LINKED ISSUE #4392: !() doesn't capture information from subprocesses initiated in the background
## Steps to Reproduce

```
proc = !(ls &)
[1]+ running: ls & & (22822)
print(proc)
>>> None
```

## Expected behaviour
Something similar to this:
```
proc = !(ls)
proc
>>> CommandPipeline(
  stdin=<_io.BytesIO object at 0x7f333de561d0>,
  stdout=<_io.BytesIO object at 0x7f333de56180>,
  stderr=<_io.BytesIO object at 0x7f333de569f0>,
  pid=17977,
  returncode=0,
  args=['ls'],
  ...)
```

I can't see why a background process should return None. If I want to access said process' pid, then I have to do this:
```
import xonsh
xonsh.jobs.get_task(xonsh.jobs.tasks[-1])['pids']
```
Which is also a pretty slow expression (to write and to run).

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### PR DESCRIPTION
**Pull request by yaxollum**
Closes #4392 

This PR makes `!()` to also capture information for background subprocesses. Currently, `!()` returns `None` for background subprocesses.

In the final `if` structure of the `run_subproc()` function, the `captured == "object"` branch does not call `command.end()` before returning (unlike all the other branches), so it can be used for background subprocesses.

https://github.com/xonsh/xonsh/blob/f5acbe30d40322ecab40d4e46d0c5f4417e59aaa/xonsh/procs/specs.py#L898-L909

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Comment by daniel-shimon** [comment]
Hi! Can you simplify the logic to:
```
if capture == "object":
elif background:
elif capture == ...
```
This is getting a bit tangled

**Review by daniel-shimon — APPROVED** [review]
Nice @yaxollum ! Thanks!

**Comment by polvoazul** [comment]
Thanks for the fast response to my issue! I am truly impressed. :)

**Comment by polvoazul** [comment]
Just installed from github main and tested it! It works fine, but i noticed the behavior is not implemented with ![]. I don't need this now but it probably should work similarly, for consistency, right?

**Comment by daniel-shimon** [comment]
Not really because `![]` waits for the process to end, unlike `!()`

**Comment by polvoazul** [comment]
Wait, from the docs i thought the only difference between them was the captured stdout/stderr. Why would ![sleep 10 &] wait for the process to end?

**Comment by daniel-shimon** [comment]
Running commands by default uses `![]`, meaning running `sleep 10 and echo hi` actually turns into `![sleep 10] and ![echo hi]`

**Comment by polvoazul** [comment]
Fair enough, but what about ![command **&**] ? Shouldn't the ampersand be respected?

Think of this use case: I want to run a process in the background, streaming its stdout/stderr directly to the terminal.

Is there any way of doing that? (obviously i can use python's subprocess.run, but i mean using xonsh literals)

**Comment by daniel-shimon** [comment]
Yeah on second thought it makes sense.
`!()` and `![]` differ by capturing the output, but both return objects that can be queried, so both can contain a background process

**Pull request merged**
