### PR TITLE
Add a vox custom prompt section

### LINKED ISSUE #2090: Vox prompt variable
`vox` is cool and it's handy to be able to show the current venv name in the prompt like `virualenv` does.

So far I'm using this in my `$PROMPT` function:
```python
venv = __xonsh_env__.get('VIRTUAL_ENV')                                                     
venvname = '({})'.format(os.path.basename(venv)) if venv else '' 
```

Do you guys think this is worth turning into a prompt variable?

### PR DESCRIPTION
**Pull request by tgoodlet**
Aids those of use who like custom prompts but also want the same
prompt behaviour as `virtualenv`.

Resolves #2090

### CODE REVIEW

**Comment by astronouth7303** [comment]
It should probably be noted that this is included in the default prompt and does _not_ require loading the vox xontrib.

(No news is needed for web-only changes.)

**Comment by tgoodlet** [comment]
@astronouth7303 good point. So maybe just enter with "Although it's included in the default prompt, ..."?

I don't see a default prompt section in the docs I can link to however.

**Comment by tgoodlet** [comment]
@astronouth7303 made the changes I think you wanted?

If there's anything else let me know :)

**Comment by astronouth7303** [comment]
It looks fine, other than the tests being weird.

**Comment by gforsyth** [comment]
Test failures are due to incompatibilities with the mpl xontrib and matplotlib 2, which is now live in the conda repos. 

I guess we should pin matplotlib to 1.5.1 or thereabouts until we've updated the xontrib

**Comment by scopatz** [comment]
Thanks @tgoodlet! I merged since the MPL bugs were addressed by @gforsyth and this was a docs only change.

**Comment by tgoodlet** [comment]
@scopatz :+1:

**Pull request merged**
