### PR TITLE
fixed pip install && setup.py sdist to include generated files

### LINKED ISSUE #3681: pip install . doesn't install __amalgam__ and parser tables.
It seems that `__amalgam__.py` and parser tables are not installed when running `pip install .`. The old `python setup.py install` does the right thing. 

Pip does create the "`__amalgam__.py`" files in the temporary build directory. But it doesn't copy them afterwards. Probably it ignores all temporary files generated during the build

To reproduce: 
1. Ensure that xonsh repo is clean from any "`__amalgam__.py`" files. Otherwise it will appear to work. 
2. Ensure that you remove the "Lib/site-packages/xonsh" folder before trying.

### PR DESCRIPTION
**Pull request by scopatz**
Closes #3681

### CODE REVIEW

**Comment by scopatz** [comment]
@xonsh/xore - this is ready for review!

**Comment by laloch** [comment]
I can confirm, that both `pip install .` and `python setup.py install` now install all the `__amalgam__.py` and `parser_table.py` files.

**Comment by scopatz** [comment]
@laloch - feel free to merge!

**Comment by laloch** [comment]
Thanks for fixing this @scopatz!

**Comment by melund** [comment]
Just for the record. What did the trick? The `build_py`, `files.extend(TABLES)` or both?

**Comment by scopatz** [comment]
build_py was for `pip install` and the TABLES extend was for sdist

**Comment by melund** [comment]
`xinstall` install is still there. Is that for the old `python setup.py install` ?

**Comment by scopatz** [comment]
Yeah, it is, and I think it might actually be the piece that does the Jupyter hook.  The Jupyter hook can't be done in build_py.

**Pull request merged**
