### PR TITLE
Improve error message for RAISE_SUBPROC_ERROR=True

### PR DESCRIPTION
**Pull request by xmnlab**
This PR aims to Improve the error message when RAISE_SUBPROC_ERROR is set to True

This is a follow-up for PR #5066 

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Comment by xmnlab** [comment]
for the example used in #5066, this is the result:

```xonsh
$ xonsh /tmp/test.xsh 
LINE 1
cp: cannot stat 'nonexisting_file.txt': No such file or directory
File "/tmp/test.xsh", line 5, in <module>
    cp nonexisting_file.txt other_name.txt
```

**Comment by xmnlab** [comment]
> The code to make the output short may be looks good in [xonsh.tools.print_exception](https://github.com/xonsh/xonsh/blob/c63f75efd05f240c5f878a4ae778efb3fe9893b1/xonsh/tools.py#L999) and with using [`limit=1`](https://github.com/xonsh/xonsh/pull/5066#issuecomment-1447528538).

@anki-code I changed a bit the code using the parameter limit and the result is the same as mentioned here: https://github.com/xonsh/xonsh/pull/5072#issuecomment-1447083766 with a much better code. thanks!

question: do you want me to implement limit to [xonsh.tools.print_exception](https://github.com/xonsh/xonsh/blob/c63f75efd05f240c5f878a4ae778efb3fe9893b1/xonsh/tools.py#L999) ?

if yes, it would be ok if I remove the first line ("Traceback ...") and the last line ("subprocess.CalledProcessError:  ...") from the output?

also, I can work on that as a follow-up PR if that makes sense

**Comment by xmnlab** [comment]
@anki-code could you check if you like this new approach?

**Comment by xmnlab** [comment]
nice. glad to be in the right direction! I am working now  on the missing parts! thanks!

**Comment by xmnlab** [comment]
@anki-code , I made this change in order to fix the tests: https://github.com/xonsh/xonsh/pull/5072/files#diff-41d180f6f7233d175c2dfe36c45c4ea80eed4754fa7ed4eed46ccde1b2a778c7R332

but I am not sure if that test should be changed. I mean, not sure if my changes correctly changed the output for that specific test. Or if I should if it in some way in the code.

do you have any idea about that?

**Comment by xmnlab** [comment]
The output from my PR for that test is: 

```xonsh
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
File "/tmp/pytest-of-xmn/pytest-7/test_rc_with_failing_module0/rc.xsh", line 1, in <module>
    from my_failing_module import *
error running xonsh run control file '/tmp/pytest-of-xmn/pytest-7/test_rc_with_failing_module0/rc.xsh': Unexpected error

```

and for the current code is:

```xonsh
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
RuntimeError: Unexpected error
error running xonsh run control file '/tmp/pytest-of-xmn/pytest-8/test_rc_with_failing_module0/rc.xsh': Unexpected error

```

**Comment by xmnlab** [comment]
> I like the output but the implementation looks like you ignore the whole code in print_exception and just add the logic for your case at the beggining of the function. For example in the function we see show_trace, color_results variables and probably it's good to use them.

oh sorry .. I thought it was just about improving the message for the case when `RAISE_SUBPROC_ERROR=True`. For example, my implementation (the error message) would just affect the case where show_trace is False.

could you provide more details about what you have in mind? what functions it would be impacted for this PR?

thanks for the review and all the guidance.

**Comment by xmnlab** [comment]
> Can we use color_results with the short traceback?

Ok, I can give it a shot :) I will work on that later today

**Comment by xmnlab** [comment]
@anki-code 

xonsh-output

I needed to remove the "strip" method because the file path was not being colored ... and it looked better with the "Traceback" first line, so I added that back as well.

let me know if you have more suggestion.

PS: I rebased the code .. and the pre-commit hooks for black, pyupgrade, and trim trailing whitespace is failing now (+ flake8 that was already failing)

**Comment by xmnlab** [comment]
@anki-code thank you for your feedback and review!

I added your suggestions, but not sure if I managed to capture what you have in mind. let me know if I am in a wrong direction or if I could do it better in any way. 

thank you!

**Comment by xmnlab** [comment]
mm it seems I would need to update one test there. I am working on that.

**Comment by xmnlab** [comment]
btw, the `run-tests.xsh` is crashing sometimes with this error:

```
xonsh.tools.XonshError: xonsh: subprocess mode: command not found: 'xonsh'
```

for example, a test in the tests_scripts function is raising this error locally:

```
- xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
  - Traceback (most recent call last):
  -   File "/home/xmn/mambaforge/envs/xonsh/lib/python3.11/site-packages/xonsh/procs/specs.py", line 473, in _run_binary
  -     p = self.cls(cmd, bufsize=bufsize, **kwargs)
  -         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  -   File "/home/xmn/mambaforge/envs/xonsh/lib/python3.11/subprocess.py", line 1022, in __init__
  -     self._execute_child(args, executable, preexec_fn, close_fds,
  -   File "/home/xmn/mambaforge/envs/xonsh/lib/python3.11/subprocess.py", line 1899, in _execute_child
  -     raise child_exception_type(errno_num, err_msg, err_filename)
  - FileNotFoundError: [Errno 2] No such file or directory: 'xonsh'
  - 
  - During handling of the above exception, another exception occurred:
  - 
  - Traceback (most recent call last):
  -   File "/home/xmn/mambaforge/envs/xonsh/lib/python3.11/site-packages/xonsh/procs/pipelines.py", line 166, in __init__
  -     proc = spec.run(pipeline_group=pipeline_group)
  -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  -   File "/home/xmn/mambaforge/envs/xonsh/lib/python3.11/site-packages/xonsh/procs/specs.py", line 455, in run
  -     p = self._run_binary(kwargs)
  -         ^^^^^^^^^^^^^^^^^^^^^^^^
  -   File "/home/xmn/mambaforge/envs/xonsh/lib/python3.11/site-packages/xonsh/procs/specs.py", line 492, in _run_binary
  -     raise xt.XonshError(e)
  - xonsh.tools.XonshError: xonsh: subprocess mode: command not found: 'xonsh'
  - Command 'xonsh' not found, but can be installed with:
  - sudo apt install xonsh
    5
    4
```

I am using a conda environment .. not sure if that is the problem (I am saying that because on CI it is not using conda env for the test)

any tips would be very appreciated

**Comment by xmnlab** [comment]
thanks for the review and the guidance @anki-code !

**Comment by jnoortheen** [comment]
pre-commit.ci autofix

**Comment by jnoortheen** [comment]
Thanks @xmnlab !

**Pull request merged**
