### PR TITLE
parsers: fix deprecation warnings triggered on python3.13 (#5710)

### LINKED ISSUE #5710: Deprecation warnings on python3.13 on reloading .xonshrc
## Current Behavior
Whenever I modify my `.xonshrc` file and start a new shell, I get the following:

Traceback (if applicable):

<details>

```xsh
/Users/user/Library/Application Support/pipx/venvs/xonsh/lib/python3.13/site-packages/xonsh/parsers/ast.py:143: DeprecationWarning: Constant.__init__ got an unexpected keyword argument 'is_raw'. Support for arbitrary keyword arguments is deprecated and will be removed in Python 3.15.
  return Constant(value=s, kind="str", **kwargs)
/Users/user/Library/Application Support/pipx/venvs/xonsh/lib/python3.13/site-packages/xonsh/parsers/base.py:2377: DeprecationWarning: Dict.__init__ got an unexpected keyword argument 'ctx'. Support for arbitrary keyword arguments is deprecated and will be removed in Python 3.15.
  p0 = ast.Dict(
/Users/user/Library/Application Support/pipx/venvs/xonsh/lib/python3.13/site-packages/xonsh/parsers/base.py:2158: DeprecationWarning: Add.__init__ got an unexpected keyword argument 'lineno'. Support for arbitrary keyword arguments is deprecated and will be removed in Python 3.15.
  op = self._term_binops[p1.value](lineno=p1.lineno, col_offset=p1.lexpos)
/Users/user/Library/Application Support/pipx/venvs/xonsh/lib/python3.13/site-packages/xonsh/parsers/base.py:2158: DeprecationWarning: Add.__init__ got an unexpected keyword argument 'col_offset'. Support for arbitrary keyword arguments is deprecated and will be removed in Python 3.15.
  op = self._term_binops[p1.value](lineno=p1.lineno, col_offset=p1.lexpos)
/Users/user/Library/Application Support/pipx/venvs/xonsh/lib/python3.13/site-packages/xonsh/parsers/base.py:2158: DeprecationWarning: Sub.__init__ got an unexpected keyword argument 'lineno'. Support for arbitrary keyword arguments is deprecated and will be removed in Python 3.15.
  op = self._term_binops[p1.value](lineno=p1.lineno, col_offset=p1.lexpos)
/Users/user/Library/Application Support/pipx/venvs/xonsh/lib/python3.13/site-packages/xonsh/parsers/base.py:2158: DeprecationWarning: Sub.__init__ got an unexpected keyword argument 'col_offset'. Support for arbitrary keyword arguments is deprecated and will be removed in Python 3.15.
  op = self._term_binops[p1.value](lineno=p1.lineno, col_offset=p1.lexpos)
/Users/user/Library/Application Support/pipx/venvs/xonsh/lib/python3.13/site-packages/xonsh/parsers/base.py:3050: DeprecationWarning: comprehension.__init__ missing 1 required positional argument: 'is_async'. This will become an error in Python 3.15.
  comp = ast.comprehension(target=targ, iter=it, ifs=[])
/Users/user/Library/Application Support/pipx/venvs/xonsh/lib/python3.13/site-packages/xonsh/parsers/base.py:741: DeprecationWarning: Expression.__init__ got an unexpected keyword argument 'lineno'. Support for arbitrary keyword arguments is deprecated and will be removed in Python 3.15.
  p[0] = ast.Expression(body=p1, lineno=p1.lineno, col_offset=p1.col_offset)
/Users/user/Library/Application Support/pipx/venvs/xonsh/lib/python3.13/site-packages/xonsh/parsers/base.py:741: DeprecationWarning: Expression.__init__ got an unexpected keyword argument 'col_offset'. Support for arbitrary keyword arguments is deprecated and will be removed in Python 3.15.
  p[0] = ast.Expression(body=p1, lineno=p1.lineno, col_offset=p1.col_offset)
```

</details>

## Expected Behavior
Shell to start with no errors.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### PR DESCRIPTION
**Pull request by doronz88**
Close #5710

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Comment by JamesParrott** [comment]
Great work.  It looks to me like you understand where and why the extra custom kwargs have been added.  Did you also consider trivially subclassing each object in ast that Xonsh uses, to cover off any other calls with similar extra args, and preserve more of the existing code (this might not be as pretty)?

**Comment by doronz88** [comment]
I'm not familiar enough with the existing codebase in order to understand why `test_subproc_raw_str_literal` currently fails. @anki-code can you please have a look?

@JamesParrott All I did was treat the deprecation warnings I got. I don't think adding classes to there parts should be considered good, since I guess this part must be as efficient as possible for parsing the executing each line

**Review by gforsyth — COMMENTED** [review]
Thanks for tracking all of these down, @doronz88 !

As we drop older versions (and there's some work to be done there...) it's very helpful if changes to the parsers are categorized by version.  

The changes you've made to `ast.py` are good to go, but the changes to `base.py` and `v36.py` and `v310.py` should instead go in a `v313.py` file that overrides the classes that require the changes you've identified.

**Comment by doronz88** [comment]
Thanks @gforsyth ! I refactored my changes to be as self-contained as possible in `v313.py` now

**Comment by doronz88** [comment]
@anki-code @gforsyth I wasn't able to reproduce the CI errors. Can you please verify if I'm doing something wrong?

**Comment by gforsyth** [comment]
Hey @doronz88 -- you aren't doing anything wrong, CI is broken on main. I'll fix it up and you can pull in those changes

**Comment by gforsyth** [comment]
Hey @doronz88 -- sorry for the delay. If you pull in the changes from main that should unblock CI

**Review by gforsyth — APPROVED** [review]
Thanks for putting this together, @doronz88 !

I've tested it locally against Python 3.13 and tests pass and the deprecation warnings are silenced.  We should add 3.13 to the CI runs shortly, but we can get this in first.  Thanks for tracking all of the breakages/changes down!

**Comment by doronz88** [comment]
Thanks! will be waiting eagerly for the next release :)

**Pull request merged**
