### PR TITLE
Subshells

### PR DESCRIPTION
**Pull request by scopatz**
This adds the ability to run xonsh subshells in subprocess mode. I am not a huge fan of this feature, personally, but it seems that vim requires it. Thus we gaze a little harder into Unix compliance. This should address the issues that @laerus and @mitnk are seeing in #1536. Incidentally it also implements #1141.

### CODE REVIEW

**Comment by melund** [comment]
Are there any cool uses of this except compatability? 

I have few issues. I normally type a wrong command name I get: 
```
snail@sea ~\Documents\xonsh subshell
$ not_a_command hallo
xonsh: subprocess mode: command not found: not_a_command
```

If I do the same with parenteses I get a long traceback
```
snail@sea ~\Documents\xonsh subshell
$ (not_a_command hallo)
Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\built_ins.py", line 511, in _run_binary
    p = self.cls(self.cmd, bufsize=bufsize, **kwargs)
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\proc.py", line 556, in __init__
    **kwargs)
  File "C:\Users\mel\Anaconda3\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Users\mel\Anaconda3\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mel\Anaconda3\Scripts\xonsh-script.py", line 11, in <module>
    load_entry_point('xonsh==0.3.0', 'console_scripts', 'xonsh')()
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\main.py", line 339, in main
    _failback_to_other_shells(args, err)
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\main.py", line 303, in _failback_to_other_shells
    raise err
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\main.py", line 337, in main
    return main_xonsh(args)
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\main.py", line 371, in main_xonsh
    run_code_with_cache(args.command.lstrip(), shell.execer, mode='single')
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\codecache.py", line 209, in run_code_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\codecache.py", line 68, in run_compiled_code
    func(code, glb, loc)
  File "e89600bce27d97330c3dc9444e0d1a53", line 1, in <module>
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\built_ins.py", line 868, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\built_ins.py", line 804, in run_subproc
    command = HiddenCommandPipeline(specs)
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\proc.py", line 1748, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\built_ins.py", line 501, in run
    p = self._run_binary(kwargs)
  File "C:\Users\mel\Anaconda3\lib\site-packages\xonsh\built_ins.py", line 522, in _run_binary
    raise XonshError(e)
xonsh.tools.XonshError: xonsh: subprocess mode: command not found: not_a_command
snail@sea ~\Documents\xonsh subshell
$
```

**Comment by melund** [comment]
I guess this is expected right?

**Comment by melund** [comment]
Like running: `xonsh -c "not_a_command"`

Anyway I am good with merging this.

**Comment by scopatz** [comment]
> Are there any cool uses of this except compatability?

I think that the main uses are security and encapsulation from user state, since the subshell runs in its own process. Personally, I have always felt that these benefits are overstated. In other shells, encapsulation plays a bigger role because they lack namespaces. 

> If I do the same with parenteses I get a long traceback, Like running: `xonsh -c "not_a_command"`

Yes, I think this is expected since the parser generates `xonsh -c "not_a_command"`.  I am happy to have the semantics of error printing in `-c` mode change, but that is probably a separate feature request :)

In any event I just fixed up a few bugs on this branch and so I think it is probably good to go.

**Comment by mitnk** [comment]
Very nice! This fixed my issue. Thanks for the efforts on it!

**Pull request merged**
