### PR TITLE
addressed issue #2929

### PR DESCRIPTION
**Pull request by gsaga**

### CODE REVIEW

**Comment by melund** [comment]
I am no familiar with how pyenv work, but will this change also work on Windows?

**Comment by gforsyth** [comment]
Hey @gsaga -- thanks for putting this in!  
Sorry for the delay -- it's probably a good idea to ping on the PR after you push up a new commit.  I think most if not all of the maintainers have disabled the commit-notification emails so we don't get inundated with notifications.
I'm restarting AppVeyor to see if we can get that passing.

**Comment by gforsyth** [comment]
Also -- I see that you put in code to handle pyenv on windows (great!) but do we have any tests that are actually hitting that line of code?

**Comment by gforsyth** [comment]
Ah, I see that we do.  Great!  Thanks again for putting this in @gsaga !

**Pull request merged**
