### PR TITLE
new parallex command

### PR DESCRIPTION
**Pull request by jnoortheen**
## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Comment by jnoortheen** [comment]
@gforsyth any pointers here?

**Comment by jnoortheen** [comment]
@anki-code could you check this?

**Comment by anki-code** [comment]
Please add the example to the docs. May be to https://xon.sh/aliases.html

**Comment by jnoortheen** [comment]
> Please add the example to the docs. May be to https://xon.sh/aliases.html

done. The failing doc build is fixed in #4827 and related to recent sphinx release not being compatible

**Comment by jnoortheen** [comment]
since the qa checks are moved to pre-commit, parallex is not needed by Xonsh. 
Parallex is added to https://github.com/jnoortheen/xontrib-commands

**Pull request closed without merging**
