### PR TITLE
fix for eating semicolons

### PR DESCRIPTION
**Pull request by scopatz**
This should address #2511

### CODE REVIEW

**Comment by gforsyth** [comment]
Thanks, @scopatz !  This seems to fix the semicolons being eaten and should go in either way -- one little bit of inconsistent behavior is whether or not the `;` itself is `echo`ed when there are wildcards around:

```
~/tmp/foo 🐚  echo spam * ; echo eggs
spam file1 file2
eggs
~/tmp/foo 🐚  echo * spam ; echo eggs
file1 file2 spam ;
eggs
```

**Comment by scopatz** [comment]
Thanks for noticing!

**Comment by scopatz** [comment]
Ho-kay, I have put in a fix for this weird case.

**Comment by gforsyth** [comment]
Thanks, @scopatz !

**Pull request merged**
