### PR TITLE
auto quote completion paths that contain 'and', 'or'

### PR DESCRIPTION
**Pull request by laerus**
#1721

### CODE REVIEW

**Comment by gforsyth** [comment]
Ha.  I was _just_ working on this.

**Comment by gforsyth** [comment]
Yeah, this works well.  Thanks, @laerus, you beat me to it!  Just waiting on CI

**Comment by laerus** [comment]
this is a little confusing if you don't know how this works:

```
>>> mkdir -p 'test/and/or/okay'
>>> tree
.
└── test
    └── and
        └── or
            └── okay
>>> cd 'test/and/' <---cursor here
>>> cd 'test/and/'o <--- hitting tab here
>>>cd 'test/and/or/' <--- works as it should
```
one may be tempted to remove the last single quote to continue the completion
even though it doesn't have to.
(maybe we should mention this in the docs, well after we resolve #1432 imo)

**Comment by gforsyth** [comment]
I agree that it can use a mention in the docs.  The same behavior shows up for completing path names with other quoted characters

**Comment by gforsyth** [comment]
Thanks, @laerus !  Glad to have this in.

**Pull request merged**
