### PR TITLE
get_repo_url() test

### PR DESCRIPTION
**Pull request by scopatz**
Test for issue in #3875

### CODE REVIEW

**Comment by scopatz** [comment]
Just a test right now, no news item needed

**Comment by scopatz** [comment]
Ready for review @xonsh/xore

**Review by BYK — APPROVED** [review]

**Comment by laloch** [comment]
I don't think, that this actually tests for the bug/regression reported in #3875. @jaraco reports a failure even with this function definition removed.

**Comment by scopatz** [comment]
Hmm yeah.  It might not.  Seems like it is a good test to have though anyway

**Comment by laloch** [comment]
OK, let's have it then :wink:
Thanks.

**Pull request merged**
