### PR TITLE
More ANSI color fun

### LINKED ISSUE #3034: Xonsh 0.8.11 fails on startup
```
⚡~$ pip3 install --force xonsh
Collecting xonsh
Installing collected packages: xonsh
  Found existing installation: xonsh 0.8.11
    Uninstalling xonsh-0.8.11:
      Successfully uninstalled xonsh-0.8.11
Successfully installed xonsh-0.8.11
⚡~$ xonsh --version
xonsh/0.8.11
⚡~$ xonsh
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 24004, in main
    args = premain(argv)
  File "/usr/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 23955, in premain
    env = start_services(shell_kwargs, args)
  File "/usr/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 23890, in start_services
    cacheall=shell_kwargs.get("cacheall", False),
  File "/usr/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 23021, in __init__
    load_builtins(execer=self, ctx=xonsh_ctx)
  File "/usr/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 22592, in load_builtins
    builtins.__xonsh__.load(execer=execer, ctx=ctx)
  File "/usr/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 22668, in load
    self.env = Env(default_env())
  File "/usr/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 19110, in __init__
    self[key] = val
  File "/usr/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 19272, in __setitem__
    val = ensurer.convert(val)
  File "/usr/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 18218, in convert
    return cls.fromstring(x)
  File "/usr/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 18181, in fromstring
    esc, "default", reversed_style=reversed_default
  File "/usr/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 6986, in ansi_color_escape_code_to_name
    ec = ANSI_ESCAPE_CODE_RE.match(escape_code).group(2)
AttributeError: 'NoneType' object has no attribute 'group'
Xonsh encountered an issue during launch
Failback to /bin/bash
bash: shopt: globstar: invalid shell option name
bash: shopt: autocd: invalid shell option name
[
a few more failures because my bashrc depends on current
bash at /usr/local/bin/bash, not the old system bash
]
bash-3.2$ exit
```

I previously had 0.8.6 IIRC (which worked) and just installed 0.8.11. Was gonna use some low-energy time to configure my Xonsh config to get parity with Zsh to see if I could switch to Xonsh and then this happened :) Running on Mac Mojave. Lemme know if I can do anything else to help debug.

### LINKED ISSUE #3037: Xonsh 0.8.11 dies while starting
Requirement already up-to-date: xonsh in /usr/lib/python3.6/site-packages (0.8.11)

### Traceback (if applicable)

<details>

```

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 24004, in main
    args = premain(argv)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 23955, in premain
    env = start_services(shell_kwargs, args)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 23890, in start_services
    cacheall=shell_kwargs.get("cacheall", False),
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 23021, in __init__
    load_builtins(execer=self, ctx=xonsh_ctx)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 22592, in load_builtins
    builtins.__xonsh__.load(execer=execer, ctx=ctx)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 22668, in load
    self.env = Env(default_env())
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 19110, in __init__
    self[key] = val
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 19272, in __setitem__
    val = ensurer.convert(val)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 18218, in convert
    return cls.fromstring(x)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 18181, in fromstring
    esc, "default", reversed_style=reversed_default
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 7022, in ansi_color_escape_code_to_name
    short_to_ints(short), background=(fore_back == "BACK"), prefix=pre
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 1268, in short_to_ints
    return rgb_to_ints(short2rgb(short))
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 1199, in short2rgb
    return SHORT_TO_RGB[short]
KeyError: '5'
Xonsh encountered an issue during launch
Failback to /bin/sh

```
</details>

Thanks

### LINKED ISSUE #3039: xonsh 0.8.11 fails to sart up with "ValueError: Could not translate ANSI color code"
After installing xonsh 0.8.11 freshly into its own venv I got on start-up teh following trace back:

```
Traceback (most recent call last):
  File "/home/halloleo/share/pipx/xonsh/lib/python3.6/site-packages/xonsh/main.py", line 401, in main
    args = premain(argv)
  File "/home/halloleo/share/pipx/xonsh/lib/python3.6/site-packages/xonsh/main.py", line 352, in premain
    env = start_services(shell_kwargs, args)
  File "/home/halloleo/share/pipx/xonsh/lib/python3.6/site-packages/xonsh/main.py", line 287, in start_services
    cacheall=shell_kwargs.get("cacheall", False),
  File "/home/halloleo/share/pipx/xonsh/lib/python3.6/site-packages/xonsh/execer.py", line 62, in __init__
    load_builtins(execer=self, ctx=xonsh_ctx)
  File "/home/halloleo/share/pipx/xonsh/lib/python3.6/site-packages/xonsh/built_ins.py", line 1272, in load_builtins
    builtins.__xonsh__.load(execer=execer, ctx=ctx)
  File "/home/halloleo/share/pipx/xonsh/lib/python3.6/site-packages/xonsh/built_ins.py", line 1348, in load
    self.env = Env(default_env())
  File "/home/halloleo/share/pipx/xonsh/lib/python3.6/site-packages/xonsh/environ.py", line 1337, in __init__
    self[key] = val
  File "/home/halloleo/share/pipx/xonsh/lib/python3.6/site-packages/xonsh/environ.py", line 1499, in __setitem__
    val = ensurer.convert(val)
  File "/home/halloleo/share/pipx/xonsh/lib/python3.6/site-packages/xonsh/environ.py", line 445, in convert
    return cls.fromstring(x)
  File "/home/halloleo/share/pipx/xonsh/lib/python3.6/site-packages/xonsh/environ.py", line 408, in fromstring
    esc, "default", reversed_style=reversed_default
  File "/home/halloleo/share/pipx/xonsh/lib/python3.6/site-packages/xonsh/ansi_colors.py", line 268, in ansi_color_escape_code_to_name
    msg.format(escape_code=escape_code, names=names, name=name, n=n)
ValueError: Could not translate ANSI color code '01;05;37;41' into a known color in the palette. Specifically, the 'BOLD_SLOWBLINK_WHITE' portion of 'WHITE' in ['BOLD_', 'SLOWBLINK_', 'WHITE', 'BACKGROUND_RED'] seems to missing.
Xonsh encountered an issue during launch
```

This happens under Python3.6.4 on Centos 6 in a proper XTerm (`TERM=xterm`). Obviously I cannot provide a `xonfig` output... %-\

### LINKED ISSUE #3046: Recently installed xonsh 0.8.11 fails back to sh with KeyError: '9'
I have just installed xonsh from source (0.8.11) in a fresh Deepin 15.9 installation, because the OS's apt repository is pointing to xonsh 0.6.3 yet.

I have tried to install through pip, using python 3.6 and 3.7 `-m pip install .` as well as directly calling the `setup.py` executable for these two python versions.

I also tried to install it through `virtualenv` and I still get the same error.

### Traceback (if applicable)

<details>

```
Traceback (most recent call last):
  File "/home/bertolino/Downloads/venv/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 24004, in main
    args = premain(argv)
  File "/home/bertolino/Downloads/venv/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 23955, in premain
    env = start_services(shell_kwargs, args)
  File "/home/bertolino/Downloads/venv/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 23890, in start_services
    cacheall=shell_kwargs.get("cacheall", False),
  File "/home/bertolino/Downloads/venv/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 23021, in __init__
    load_builtins(execer=self, ctx=xonsh_ctx)
  File "/home/bertolino/Downloads/venv/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 22592, in load_builtins
    builtins.__xonsh__.load(execer=execer, ctx=ctx)
  File "/home/bertolino/Downloads/venv/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 22668, in load
    self.env = Env(default_env())
  File "/home/bertolino/Downloads/venv/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 19110, in __init__
    self[key] = val
  File "/home/bertolino/Downloads/venv/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 19272, in __setitem__
    val = ensurer.convert(val)
  File "/home/bertolino/Downloads/venv/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 18218, in convert
    return cls.fromstring(x)
  File "/home/bertolino/Downloads/venv/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 18181, in fromstring
    esc, "default", reversed_style=reversed_default
  File "/home/bertolino/Downloads/venv/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 7022, in ansi_color_escape_code_to_name
    short_to_ints(short), background=(fore_back == "BACK"), prefix=pre
  File "/home/bertolino/Downloads/venv/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 1268, in short_to_ints
    return rgb_to_ints(short2rgb(short))
  File "/home/bertolino/Downloads/venv/local/lib/python3.7/site-packages/xonsh/__amalgam__.py", line 1199, in short2rgb
    return SHORT_TO_RGB[short]
KeyError: '9'
Xonsh encountered an issue during launch
Failback to /bin/sh
(venv) \[\e]0;\u@\h: \w\a\]\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$ 
```

</details>

## Steps to Reproduce
```sh
# inside xonsh source relase 0.8.11
# I also tried these commands below with `sudo`
# as well as inside `virtualenv` pointing to both python versions without `sudo`
python3.6 -m pip install .
python3.7 -m pip install .
pip3 install .
```
```sh
# finally, I tried installing directly from pypi repository and still not working
python3.6 -m pip install xonsh
python3.7 -m pip install xonsh
pip3 install xonsh
```
And then, just trying to execute:
```sh
xonsh
```

### PR DESCRIPTION
**Pull request by scopatz**
This PR implements a much greater portion of the ANSI color spec in order to fix some of the issues with `$LS_COLORS`. As far as I can tell it is also a little faster because styles are no longer expanded when they are first used.  Rather, only the color names that are actually used (aside from the base colors) are computed. The computed colors are added to the color map/style for future use.

* fixes #3034
* fixes #3037
* fixes #3039
* fixes #3046

### CODE REVIEW

**Comment by scopatz** [comment]
@xonsh/xore - this is ready for review!

**Comment by scopatz** [comment]
pinging this :wink:

**Comment by melund** [comment]
I have been wanting to look at it all weekend. Just too busy. 

Do you have any thoughts on how the new extended syntax (`STRIKETHROUGH_RED`)  play prompt_toolkit for example?

**Comment by melund** [comment]
I guess they are simply not understood if used with PTK.

**Comment by scopatz** [comment]
Oh yeah, good point.  This probably needs to be implemented for PTK

**Comment by melund** [comment]
Or at least add to the docs, that the PTK backend only supports a subset of the colour specifications.

**Comment by melund** [comment]
I think this should be merged as soon as possible.

**Comment by scopatz** [comment]
OK! I've pushed up a minor doc note with the goal of getting this merge. Once it is, I'll make a new issue and then work on getting full PTK supporrt

**Pull request merged**
