### PR TITLE
Nested subprocess macro fix

### PR DESCRIPTION
**Pull request by scopatz**
Should address #1676

### CODE REVIEW

**Comment by laerus** [comment]
thanks for this @scopatz!
i'm getting some debugging info on hitting return
```
3
4
5
3
4
5
clearing ded jobs
3
4
5
```

**Comment by scopatz** [comment]
That looks like you have installed a test version of the rs branch, which is unrelated to this PR

**Comment by scopatz** [comment]
Also, it looks like the failures on nightly are due to some AST changes.  It is probably worth having a v3.6 parser

**Comment by gforsyth** [comment]
Thanks, @scopatz !

**Pull request merged**
