### PR TITLE
Add ansi-color codes to the default style

### PR DESCRIPTION
**Pull request by melund**
This PR updates the PTK styles. So now we don't use pygments when the style is set to 'default'. Instead,  we use the `XONSH_BASE_STYLE` dict, which has been updated to match the default pygments style. 

This has the advantage that we can make a version with ansi color code names. 
See this issue: https://github.com/xonsh/xonsh/issues/1821

At the moment, this is a WIP because I think there is a bug in prompt-toolkit which swap the dark and light ansi color names on Windows. https://github.com/jonathanslenders/python-prompt-toolkit/pull/408 

So I think we should wait until that is fixed.

### CODE REVIEW

**Comment by gforsyth** [comment]
Hey @melund -- overall looks good, just a couple of linting errors

**Comment by melund** [comment]
Thanks. I will fix those lint errors..

**Comment by scopatz** [comment]
Thanks for putting this in @melund! I guess we should wait until the next PTK release it sounds like...

**Comment by melund** [comment]
@OJFord The fix have been merged into prompt_toolkit master. So I think this is ready to go. 

Do you mind trying it? Let me know if you think any of the styles here https://github.com/xonsh/xonsh/pull/1894/files#diff-2316634a699f0d18ebe4a69e7d69ea9cR497 should have different colors...

**Comment by scopatz** [comment]
Happy to merge this whenever @melund

**Comment by OJFord** [comment]
Happy to try it later - but what am I trying?

I don't have a Windows machine at the moment, so I can't test that issue, do I still need to run it with PTK master?

**Comment by melund** [comment]
No need for Windows. The color-names was also swapped for VT100 in PTK. So it wasn't a windows only problem. That is fixed in PTK now.

You should just test that the colors follow your terminal colors when you use the 'default' style in xonsh. You need to use PTK master and pygments master for it to work.

Also, if you think that any of the colors choices does not work well in your terminal I would like some suggestions. 

@scopatz. I believe we can merge this now. Then everyone can help test it if they use pygments and PTK master.

**Comment by laerus** [comment]
ty @melund !!

**Pull request merged**
