### PR TITLE
refactor(amalgamate): remove amalgamation

### PR DESCRIPTION
**Pull request by gforsyth**
I think the time for this has probably come.  
I am interested if folks can try out this branch using `xonsh --no-rc --timings` and compare it to `main` and see if there's a noticeable performance difference.  

I suspect most of the startup time penalty will be a wash, with more benefits coming from the lazy evaluation of our compiled regexes, but I want to make sure we aren't completely borking startup time.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Comment by jnoortheen** [comment]
There is not much difference on my machine (M1 Air), 


<details>
  <summary>On this branch - 0.160s</summary>

|Event name               | Time (s)  | Delta (s) |
|-------------------------|-----------|-----------|
|start                    |   0.000   |   0.000   |
|pre_execer_init          |   0.004   |   0.004   |
|post_execer_init         |   0.031   |   0.027   |
|pre_xontribs_autoload    |   0.031   |   0.000   |
|post_xontribs_autoload   |   0.055   |   0.024   |
|on_pre_rc                |   0.055   |   0.000   |
|on_post_rc               |   0.055   |   0.000   |
|on_ptk_create            |   0.113   |   0.058   |
|on_post_init             |   0.113   |   0.000   |
|on_pre_cmdloop           |   0.113   |   0.000   |
|on_pre_prompt_format     |   0.113   |   0.000   |
|on_pre_prompt_tokenize   |   0.133   |   0.020   |
|on_post_prompt_tokenize  |   0.140   |   0.007   |
|on_pre_prompt_style      |   0.159   |   0.019   |
|on_post_prompt_style     |   0.160   |   0.001   |
|on_pre_prompt            |   0.160   |   0.000   |
</details>

<details>
  <summary>On main - 0.166s</summary>
  
|Event name               | Time (s)  | Delta (s) |
|-------------------------|-----------|-----------|
|start                    |   0.000   |   0.000   |
|pre_execer_init          |   0.007   |   0.007   |
|post_execer_init         |   0.034   |   0.027   |
|pre_xontribs_autoload    |   0.034   |   0.000   |
|post_xontribs_autoload   |   0.058   |   0.024   |
|on_pre_rc                |   0.058   |   0.000   |
|on_post_rc               |   0.058   |   0.000   |
|on_ptk_create            |   0.124   |   0.066   |
|on_post_init             |   0.124   |   0.000   |
|on_pre_cmdloop           |   0.124   |   0.000   |
|on_pre_prompt_format     |   0.124   |   0.000   |
|on_pre_prompt_tokenize   |   0.141   |   0.017   |
|on_post_prompt_tokenize  |   0.147   |   0.005   |
|on_pre_prompt_style      |   0.165   |   0.018   |
|on_post_prompt_style     |   0.166   |   0.001   |
|on_pre_prompt            |   0.166   |   0.000   |
</details>

**Review by jnoortheen — APPROVED** [review]

**Comment by Techcable** [comment]
#### 2017 ArchLinux Lenovo Laptop (4 cores, 8GB RAM)

<details>
<summary>On this branch - 0.075s</summary>

0.556s for first run

````
 Debug level: Off
|-------------------------|-----------|-----------|
|Event name               | Time (s)  | Delta (s) |
|-------------------------|-----------|-----------|
|start                    |   0.000   |   0.000   |
|pre_execer_init          |   0.008   |   0.008   |
|post_execer_init         |   0.084   |   0.077   |
|pre_xontribs_autoload    |   0.085   |   0.000   |
|post_xontribs_autoload   |   0.112   |   0.027   |
|on_pre_rc                |   0.112   |   0.000   |
|on_post_rc               |   0.112   |   0.000   |
|on_ptk_create            |   0.208   |   0.096   |
|on_post_init             |   0.208   |   0.000   |
|on_pre_cmdloop           |   0.208   |   0.000   |
|on_pre_prompt_format     |   0.208   |   0.000   |
|on_pre_prompt_tokenize   |   0.237   |   0.029   |
|on_post_prompt_tokenize  |   0.246   |   0.009   |
|on_pre_prompt_style      |   0.285   |   0.039   |
|on_post_prompt_style     |   0.287   |   0.002   |
|on_pre_prompt            |   0.287   |   0.000   |
|-------------------------|-----------|-----------|
````
</details>

<details>
<summary>On main - 0.284s</summary>

0.606s for first run

````

 Debug level: Off
|-------------------------|-----------|-----------|
|Event name               | Time (s)  | Delta (s) |
|-------------------------|-----------|-----------|
|start                    |   0.000   |   0.000   |
|pre_execer_init          |   0.008   |   0.008   |
|post_execer_init         |   0.084   |   0.076   |
|pre_xontribs_autoload    |   0.084   |   0.000   |
|post_xontribs_autoload   |   0.111   |   0.027   |
|on_pre_rc                |   0.111   |   0.000   |
|on_post_rc               |   0.111   |   0.000   |
|on_ptk_create            |   0.206   |   0.095   |
|on_post_init             |   0.206   |   0.000   |
|on_pre_cmdloop           |   0.207   |   0.000   |
|on_pre_prompt_format     |   0.207   |   0.000   |
|on_pre_prompt_tokenize   |   0.237   |   0.031   |
|on_post_prompt_tokenize  |   0.244   |   0.007   |
|on_pre_prompt_style      |   0.282   |   0.038   |
|on_post_prompt_style     |   0.284   |   0.002   |
|on_pre_prompt            |   0.284   |   0.000   |
|-------------------------|-----------|-----------|
````
</details>

#### On my 2021 M1 Max Macbook Pro

<details>
<summary>On this branch - 0.075s</summary>

0.273s for first run

````
 Debug level: Off
|------------------------|-----------|-----------|
|Event name              | Time (s)  | Delta (s) |
|------------------------|-----------|-----------|
|start                   |   0.000   |   0.000   |
|pre_execer_init         |   0.004   |   0.004   |
|post_execer_init        |   0.049   |   0.045   |
|pre_xontribs_autoload   |   0.049   |   0.000   |
|post_xontribs_autoload  |   0.055   |   0.006   |
|on_pre_rc               |   0.055   |   0.000   |
|on_post_rc              |   0.055   |   0.000   |
|on_post_init            |   0.060   |   0.004   |
|on_pre_cmdloop          |   0.060   |   0.000   |
|on_pre_prompt_format    |   0.060   |   0.000   |
|on_pre_prompt           |   0.075   |   0.015   |
|------------------------|-----------|-----------|
````
</details>
<details>
    <summary>On main - 0.077s</summary>

0.246 for first run

````
Debug level: Off
|------------------------|-----------|-----------|
|Event name              | Time (s)  | Delta (s) |
|------------------------|-----------|-----------|
|start                   |   0.000   |   0.000   |
|pre_execer_init         |   0.004   |   0.004   |
|post_execer_init        |   0.049   |   0.044   |
|pre_xontribs_autoload   |   0.049   |   0.000   |
|post_xontribs_autoload  |   0.055   |   0.006   |
|on_pre_rc               |   0.055   |   0.000   |
|on_post_rc              |   0.055   |   0.000   |
|on_post_init            |   0.059   |   0.004   |
|on_pre_cmdloop          |   0.059   |   0.000   |
|on_pre_prompt_format    |   0.059   |   0.000   |
|on_pre_prompt           |   0.077   |   0.018   |
|------------------------|-----------|-----------|
````

</details>

#### Conclusions
Both tests ran on Python 3.10, both laptops were plugged in and had no other apps running (besides a few browser tabs).

I did one warmup run and took the second result.

My old 2017 laptop has much slower results (as expected), but on both laptops it appears the difference between branches is not statistically significant. One laptop points one way and one points the other (and further runs only give more inconclusive results).

**Comment by jnoortheen** [comment]
I have resolved the conflicts.

**Comment by jnoortheen** [comment]
@anki-code could you test this and report ?

**Comment by jnoortheen** [comment]
well 3 is the magik number!

**Pull request merged**
