### PR TITLE
Improve first set of "Developer's Guide" instructions [updated]

### PR DESCRIPTION
**Pull request by santagada**
updated another pull request to speed the improvement of documentation

### CODE REVIEW

**Comment by gforsyth** [comment]
Hey @santagada, thanks for putting this in!  I think it might be good to add a reference to installing with `setup.py develop` so that people can make edits to the git repo and not within their `site-packages`.  Or so they don't make changes in the repo directory and expect them to propagate out to `site-packages`.  Does that make sense?

**Comment by laerus** [comment]
++ @gforsyth we should also change the developer mode to not amalgamate. i will try PR this soon, if noone else want to mess with that.

**Comment by santagada** [comment]
@gforsyth and @laerus I think both make sense, but should be done after merging this in right?

**Comment by gforsyth** [comment]
@santagada -- yes, I'll merge this now.  
@laerus -- it's all yours, or I'll try to tackle it later today.

**Comment by gforsyth** [comment]
Thanks @santagada and @stockninja !

**Pull request merged**
