### PR TITLE
Build docs on travis

### PR DESCRIPTION
**Pull request by Carreau**
The first commit test should fail see cause of #1695.
If it fails with the same cause I'll push a second commit that fix the build.

### CODE REVIEW

**Comment by Carreau** [comment]
Travis is failing for the god reason. Pushing a commit that should fix the doc build.

**Comment by scopatz** [comment]
I am not sure what is going on with the failures here @Carreau, but thanks for putting this in!

**Comment by Carreau** [comment]
> I am not sure what is going on with the failures here @Carreau, but thanks for putting this in!

Failure look (to me) like a spurious one. I'll restart this specific build.

**Comment by Carreau** [comment]
> I am not sure what is going on with the failures here @Carreau, but thanks for putting this in!

Actually I wouldn't be astonished if this is due to the recent merge of compact dicts that have been merged yesterday in CPython, as it looks like a C-level error triggered by py-test

**Comment by laerus** [comment]
compact dicts woohooo!, did they already merge it in python3.5 wow..

**Comment by gforsyth** [comment]
maybe we should temporarily switch `nightly` to `3.5` then?

**Comment by scopatz** [comment]
I would be fine merging things for the next couple of days if they exhibit only this failure. This pop issue is clearly not coming from us.

**Comment by scopatz** [comment]
Maybe @gforsyth should be the one to make the call on this PR since it is more in his bailiwick

**Comment by Carreau** [comment]
We can mark nightly as "allow_failure". 

There already a patch pending upstream, so it should be fixed soon.

http://bugs.python.org/issue28040

**Comment by gforsyth** [comment]
> We can mark nightly as "allow_failure".

That seems like a better temporary fix to me.  

On another note, is it time to call the `doctr`?

**Comment by Carreau** [comment]
> On another note, is it time to call the doctr?

Yes, yes, but I want to get the url scheme right for multiple versions of the docs.

**Comment by Carreau** [comment]
> That seems like a better temporary fix to me.

I'm leaving in 2 h and need to prepare my stuff , I might offline until tuesday. You should have the right ito push on this branch ("Allow edits from maintainers") if needed.

**Comment by gforsyth** [comment]
Ok, I'll take care of it.  Thanks, @Carreau!

**Comment by gforsyth** [comment]
Hey @scopatz -- if you're ok with this as it is, I say we merge it.  The docs are building correctly and this will also get the updated `travis.yml` into master which should stop a bunch of the spurious error messages based on the new 3.6 generator comprehensions

**Comment by scopatz** [comment]
If you think it is ready, I am happy with it :)

**Comment by laerus** [comment]
allright i'm merging this to stop the nightly failure madness, thanks @Carreau & @gforsyth !!

**Pull request merged**
