### PR TITLE
fixed environment swapping issue

### PR DESCRIPTION
**Pull request by scopatz**
fixes and tests #2772

### CODE REVIEW

**Comment by CJ-Wright** [comment]
btw, would it be possible to get a release after this?

**Comment by scopatz** [comment]
Yeah, I am waiting on this to do a release

**Comment by gforsyth** [comment]
Thanks, @scopatz !

Side note -- should we bite the bullet and just run black on (nearly) everything?

**Comment by melund** [comment]
Looks good.

**Comment by scopatz** [comment]
Haha OK! I'll put in a PR that blacks everything :)

**Pull request merged**
