### PR TITLE
more lazy object data models

### LINKED ISSUE #1421: TypeError: unorderable types: set() <= LazyObject()
Whereas prior builds were working, currently when I execute just-built xonsh from master I'm getting an error.

```
$ xonsh
Traceback (most recent call last):
  File "/home/pbr/xonsh/venv/bin/xonsh", line 3, in <module>
    main()
  File "/home/pbr/xonsh/venv/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 16710, in main
    args = premain(argv)
  File "/home/pbr/xonsh/venv/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 16695, in premain
    shell = builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "/home/pbr/xonsh/venv/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 16439, in __init__
    kwargs.get('cacheall', False))
  File "/home/pbr/xonsh/venv/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 16483, in _init_environ
    debug_level=debug)
  File "/home/pbr/xonsh/venv/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 16125, in __init__
    load_builtins(execer=self, config=config, login=login, ctx=xonsh_ctx)
  File "/home/pbr/xonsh/venv/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 15965, in load_builtins
    builtins.__xonsh_env__ = env = Env(default_env(config=config, login=login))
  File "/home/pbr/xonsh/venv/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 12368, in default_env
    issue_warning=False)
  File "/home/pbr/xonsh/venv/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 8855, in load_foreign_envs
    shell = ensure_shell(shell)
  File "/home/pbr/xonsh/venv/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 8770, in ensure_shell
    if not (shell_keys <= VALID_SHELL_PARAMS):
TypeError: unorderable types: set() <= LazyObject()
```

### PR DESCRIPTION
**Pull request by scopatz**
This should fix #1421. If @PaulReiber @ned2 or @laerus could test this out that would be great! Thanks

### CODE REVIEW

**Comment by laerus** [comment]
this fixes the issue!

AppVayor complains with:

```
____________________________ test_partial_string _____________________________
    def test_partial_string():
        # single string at start
>       assert check_for_partial_string('no strings here') == (None, None, None)
tests\test_tools.py:999: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
c:\python35\lib\site-packages\xonsh\__amalgam__.py:6603: in check_for_partial_string
    match = re.search(RE_BEGIN_STRING, x)
c:\python35\lib\re.py:173: in search
    return _compile(pattern, flags).search(string)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pattern = <xonsh.__amalgam__.LazyObject object at 0x03B14490>, flags = 0
    def _compile(pattern, flags):
        # internal: compile pattern
        try:
>           p, loc = _cache[type(pattern), pattern, flags]
E           TypeError: unhashable type: 'LazyObject'
c:\python35\lib\re.py:281: TypeError
============== 1 failed, 1090 passed, 13 skipped in 8.97 seconds ==============
Command exited with code 1
```

**Comment by scopatz** [comment]
Whoops!  Now the tests have been fixed locally.

**Comment by laerus** [comment]
kudos for the LazyObject btw, and i keep wondering how come there is nothing like this builtin in python.

**Comment by scopatz** [comment]
> kudos for the LazyObject btw, and 

Thanks!

> i keep wondering how come there is nothing like this builtin in python.

Me too!

**Comment by ned2** [comment]
Yep, works for me!

**Comment by laerus** [comment]
great! will merge when tests finish

**Comment by PaulReiber** [comment]
Not sure if there's still a problem or maybe I'm doing something sideways?
I just built from latest master, still seeing a problem:

`(venv)pbr@mongo:~/xonsh$ xonsh
Traceback (most recent call last):
  File "/home/pbr/xonsh/venv/bin/xonsh", line 3, in <module>
    main()
  File "/home/pbr/xonsh/venv/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 16710, in main
    args = premain(argv)
  File "/home/pbr/xonsh/venv/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 16695, in premain
    shell = builtins.__xonsh_shell__ = Shell(**shell_kwargs)
  File "/home/pbr/xonsh/venv/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 16439, in __init__
    kwargs.get('cacheall', False))
  File "/home/pbr/xonsh/venv/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 16483, in _init_environ
    debug_level=debug)
  File "/home/pbr/xonsh/venv/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 16125, in __init__
    load_builtins(execer=self, config=config, login=login, ctx=xonsh_ctx)
  File "/home/pbr/xonsh/venv/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 15965, in load_builtins
    builtins.__xonsh_env__ = env = Env(default_env(config=config, login=login))
  File "/home/pbr/xonsh/venv/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 12368, in default_env
    issue_warning=False)
  File "/home/pbr/xonsh/venv/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 8855, in load_foreign_envs
    shell = ensure_shell(shell)
  File "/home/pbr/xonsh/venv/lib/python3.4/site-packages/xonsh/__amalgam__.py", line 8770, in ensure_shell
    if not (shell_keys <= VALID_SHELL_PARAMS):
TypeError: unorderable types: set() <= LazyObject()`

**Comment by scopatz** [comment]
Did amalgamate re-run successfully when you reinstalled?

**Comment by PaulReiber** [comment]
Arrgh... PEBCAK. I was doing "build" thinking that was sufficient for local testing.  Re-amalgamating happens in the install, not the build.  OK, now I know. 👍  

 Once I ran install again, it all started working.
THANK YOU

**Comment by scopatz** [comment]
great, glad it works

**Pull request merged**
