### PR TITLE
New parameters "no_rc" and "norccmd" for foreign_shell_data

### PR DESCRIPTION
**Pull request by rautyrauty**
- fix source-foreign bug: avoid sources a personal initialization file

## About bug

When trying to run source-bash with some file, it also sources ~/.bashrc

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Comment by rautyrauty** [comment]
Should I change something?

**Comment by gforsyth** [comment]
Thanks for putting this in @rautyrauty -- I don't think we need an additional keyword argument for what you are looking for -- if a foreign shell isn't started in `interactive` mode, then the default RC files won't be loaded.  I"m not sure if there's a use-case for starting a foreign shell in interactive mode _without_ the RC file.

That said, this will be a change from how things currently work and there are previous issues detailing why we err on the side of interactive mode.  We'll have to look over those again and make sure this won't break a bunch of existing users.

**Comment by gforsyth** [comment]
Yeah, on thinking about it, I'm good with setting `interactive=False` to disable loading rc files in `source-foreign` if you'd like to put in that change.

**Comment by rautyrauty** [comment]
Yes, please do it.

**Comment by jnoortheen** [comment]
superseded by #5339 which will make non-interactive mode the default . Also, even now it is possible use `source-bash --non-interactive` to not load rc files.

**Pull request closed without merging**
