### PR TITLE
tutorial quoting section

### PR DESCRIPTION
**Pull request by laerus**
*the quoting saga*

#413 #1084

### CODE REVIEW

**Comment by laerus** [comment]
oh oops, rebased..

**Comment by scopatz** [comment]
Hi @laerus, would you mind merging, rather than rebasing please?  Otherwise this looks good. Thanks!

**Comment by laerus** [comment]
this is ready, it isn't much of an explanation but it's a start, i still believe there are some rough corners we need to go over.

**Comment by scopatz** [comment]
Thanks @laerus!

**Pull request merged**
