### PR TITLE
fix: skip xonsh.built_ins from amalgam

### LINKED ISSUE #4289: XSH singleton doesn't work with amalgamated (==production) xonsh
@jnoortheen 

```sh
# Ensure amalgamate.py is installed
which amalgamate.py
# Install xonsh in production mode (without '-e')
pip install '.[full]'
# Try running xonsh
xonsh
```

I'm getting:
```
AttributeError: 'XonshSession' object has no attribute 'completers'
Failed to load xontrib jedi.
Traceback (most recent call last):
  File "/home/daniel/testxonsh/venv/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 22082, in main
    args = premain(argv)
  File "/home/daniel/testxonsh/venv/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 22022, in premain
    env = start_services(shell_kwargs, args, pre_env=pre_env)
  File "/home/daniel/testxonsh/venv/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 21970, in start_services
    XSH.shell = Shell(execer=execer, **shell_kwargs)
  File "/home/daniel/testxonsh/venv/lib/python3.8/site-packages/xonsh/__amalgam__.py", line 16365, in __init__
    XSH.history = hist = xhm.construct_history(
  File "/home/daniel/testxonsh/venv/lib/python3.8/site-packages/xonsh/history/__amalgam__.py", line 1241, in construct_history
    backend = env.get("XONSH_HISTORY_BACKEND")
AttributeError: 'NoneType' object has no attribute 'get'
Xonsh encountered an issue during launch
```

### PR DESCRIPTION
**Pull request by jnoortheen**
fixes #4289

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Comment by jnoortheen** [comment]
even if I remove xonsh.built_ins entry, it is getting added back when running amalgamate.

**Comment by daniel-shimon** [comment]
You need to add it to the exclude list at the top

**Comment by jnoortheen** [comment]
Can this failing tests be restarted?

**Comment by daniel-shimon** [comment]
Thanks @jnoortheen :)

**Pull request merged**
