### PR TITLE
Pipe fixes(?)

### LINKED ISSUE #1885: Pipes hang on windows.
I get a hanging process if I pipe stuff on windows. Here are two examples:

``` bash
snail@sea ~\Documents\xonsh master $ echo @('hello') | clip
       [hangs here... Presssing ctrl-c gives this]
ValueError: Unsupported signal: 2
snail@sea ~\Documents\xonsh master $ cat CHANGELOG.rst | grep regression
       [hangs here... Pressing ctrl-c gives this]
ValueError: Unsupported signal: 2
snail@sea ~\Documents\xonsh master $ jobs
[1]+ running: cat CHANGELOG.rst | grep regression (19004)
```

### PR DESCRIPTION
**Pull request by scopatz**
This is in an effort to fix #1885. I am not super pleased with the algorithm I wrote here, but I can't think of a better way (after hours of staring at it tonight) and it does seem to work.

### CODE REVIEW

**Comment by melund** [comment]
Do you want to wait until the mac issue are also resolved? I think this is good to be merged.

**Comment by gforsyth** [comment]
This fixes piping for me and I just tested it on a mac in the office and it works there, too, so I'm calling this good to go.

**Comment by gforsyth** [comment]
Ahh damn -- looks like more than one pipe and it hangs again...

`ps ax | grep kworker | wc -l`

**Comment by mitnk** [comment]
@gforsyth yes, found that too.

**Comment by scopatz** [comment]
I have a fix for multiple pipes in #1900

**Pull request merged**
