### PR TITLE
figuring out why travis cries with pytest

### PR DESCRIPTION
**Pull request by laerus**
i need to see travis run, couldn't make it run on my branch/repo

### CODE REVIEW

**Comment by laerus** [comment]
this actually now passes py3.5 and nightly builds. 
py3.4 complains with: 
```
_______________ test_call_list_many_star_and_starstar_args[0] _________________

inp = 'x(*[("a", 2)], *[("v", 3)], **{"c": 5})', run = False, mode = 'eval'

    def check_ast(inp, run=True, mode='eval'):

        # expect a Python AST

>       exp = ast.parse(inp, mode=mode)

tests/test_parser.py:64: 

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

source = 'x(*[("a", 2)], *[("v", 3)], **{"c": 5})', filename = '<unknown>'

mode = 'eval'

    def parse(source, filename='<unknown>', mode='exec'):

        """

        Parse the source into an AST node.

        Equivalent to compile(source, filename, mode, PyCF_ONLY_AST).

        """

>       return compile(source, filename, mode, PyCF_ONLY_AST)

E         File "<unknown>", line 1

E           x(*[("a", 2)], *[("v", 3)], **{"c": 5})

E                          ^

E       SyntaxError: invalid syntax

/opt/python/3.4.2/lib/python3.4/ast.py:35: SyntaxError

1 failed, 930 passed, 22 skipped in 26.22 seconds
```

**Comment by laerus** [comment]
duh i'm blind, this just doesn't skip test meant for py35

**Comment by laerus** [comment]
yipi passing! after skipping 4 tests in total and i wonder how can these escape nose, also a bug in xonsh.tool at `decode_bytes`

this branch is for reference not sure if its wise to merge to master before we actually fix the bugs that pytest complains about.

**Comment by melund** [comment]
Awesome. Let us fix the bugs so we can get this in :)

**Comment by gforsyth** [comment]
Looks good, @laerus.  I agree we should figure out the EnvPath bug before this goes into master, but I don't think I have a problem with merging it into the pytest branch (unless you have concerns).  

Does anyone know why pytest's skip feature doesn't seem to actually work?  That's super annoying.

**Comment by melund** [comment]
Yes. Let us just merge it into xonsh:pytest_port.

**Pull request merged**
