### PR TITLE
Fix swapped background colors on PTK completions.

### PR DESCRIPTION
**Pull request by melund**
I realized that I swapped the background colors for PTK completions. 

This doesn't need a news item as it is just a fix to a previous PR.

### CODE REVIEW

**Comment by scopatz** [comment]
LGTM @melund, thanks!

**Comment by scopatz** [comment]
@laerus - wasn't travis still building?

**Comment by laerus** [comment]
yep but this was a minor change and travis.. is very slow  :(

**Comment by scopatz** [comment]
True, travis is very slow :(

**Pull request merged**
