### PR TITLE
potential fix for interactive answering

### PR DESCRIPTION
**Pull request by scopatz**
@gforsyth and @prabhuramachandran if you could test this out, that would be awesome!

### CODE REVIEW

**Comment by gforsyth** [comment]
No luck, @scopatz.  Sorry.  I'm going to try to dig deeper into this tomorrow at the sprints.  Does this fix it on your end?

**Comment by scopatz** [comment]
I have trouble always triggering the issue. my nezt thought is to move the title printing to beforr the prompt, rather than after

**Comment by scopatz** [comment]
Oooooor it might be this: https://github.com/xonsh/xonsh/blob/master/xonsh/built_ins.py#L531

**Comment by scopatz** [comment]
Ok, please try it now.

**Comment by gforsyth** [comment]
@scopatz -- that fixed it!  but tests failing everywhere...

**Comment by scopatz** [comment]
Yay(?) My tests are failing locally too (even on master) with some flake8 stuff:

```console
scopatz@localhost ~/xonsh/tests wt $ py.test
usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: --flake8
  inifile: /home/scopatz/xonsh/setup.cfg
  rootdir: /home/scopatz/xonsh
scopatz@localhost ~/xonsh/tests master $ py.test
usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: --flake8
  inifile: /home/scopatz/xonsh/setup.cfg
  rootdir: /home/scopatz/xonsh
```

**Comment by scopatz** [comment]
After a bisect, the offending commit is 74de1591c55fbb53dafae9c8feef9b0cb2dc152f

**Comment by scopatz** [comment]
Tests are now passing, finally :)

**Comment by gforsyth** [comment]
Awesome!  I can start using `rm -rf /` with impunity again!  Merging this now.

**Comment by scopatz** [comment]
Woohoo!

**Pull request merged**
