### PR TITLE
Knight vs Snail should work on both Sphinx docs and CONTRIBUTING.rst

### PR DESCRIPTION
**Pull request by dannysepler**
It feels a tad hacky, but getting the image to render in and out of the symlink is tricky to do! Totally fine to prefer this pull request not be merged 👍

### CODE REVIEW

**Comment by scopatz** [comment]
Huh, will that actually copy the file into the sphinx `build/html/_static` directory?

**Comment by dannysepler** [comment]
it becomes an external image reference in both cases (pointing to knight-vs-snail on the master branch)

Screen Shot 2020-08-15 at 11 06 03 AM

That's why it feels a tad hacky and totally fine if not desired!

**Comment by scopatz** [comment]
Yeah, that would break locally hosted versions of the docs then.  Maybe it would be better, to have a third file which both include? Or have conf.py do rewrite this part of the file?

**Comment by dannysepler** [comment]
Are locally hosted docs what "cd docs/; make html" does? If so that's what my screenshot came from. Happy to look into the conf.py option as well!

**Comment by scopatz** [comment]
Right, yeah that is what `make html` does. And yeah, if you are online the image will still show up. My concern is more about having all of the assets available and displayed when offline

**Comment by dannysepler** [comment]
eh, i'll reopen if i can figure somethin out

**Pull request closed without merging**
