### PR TITLE
Jupyter printing with cat

### PR DESCRIPTION
**Pull request by scopatz**
This addresses some of the further issues brought up in #2712

### CODE REVIEW

**Comment by melund** [comment]
Wow. That was a big fix... I read through the code and look good I think. 

It also fixes the echo command in the jupyter notebook, while output of other subprocesses is still not working. 

image

**Comment by melund** [comment]
It doesn't fix the pager when I run commands like `git log`. The output is displayed in the console intead of the notebook.. 

image

**Comment by melund** [comment]
I don't mind merging this thus, but I will wait until other has also tried it.

**Comment by scopatz** [comment]
I have merged in your fix from #2763!  That is weird that it is displaying the terminal.  That is what this PR fixed for me on Linux ;)

**Comment by scopatz** [comment]
@eggcaker, would you be able to try this out on mac, please?

**Comment by gforsyth** [comment]
Hey @scopatz -- this works on my work mac.  `git log` blocks and takes a while to print everything out, but I think that's similar behavior to what happens with the ipykernel and `!git log`

**Comment by eggcaker** [comment]
still not working with exceptions: 
```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/xonsh/base_shell.py", line 330, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/usr/local/lib/python3.6/site-packages/xonsh/codecache.py", line 68, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/ipykernel/displayhook.py", line 34, in __call__
    sys.stdout.flush()
  File "/usr/local/lib/python3.6/site-packages/xonsh/base_shell.py", line 177, in flush
    self.std.flush()
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tempfile.py", line 709, in flush
    self._file.flush()
ValueError: I/O operation on closed file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.6/site-packages/metakernel/_metakernel.py", line 357, in do_execute
    retval = self.do_execute_direct(code)
  File "/usr/local/lib/python3.6/site-packages/xonsh_kernel/kernel.py", line 45, in do_execute_direct
    out, err, interrupted = self._do_execute_direct(code)
  File "/usr/local/lib/python3.6/site-packages/xonsh_kernel/kernel.py", line 74, in _do_execute_direct
    shell.default(code)
  File "/usr/local/lib/python3.6/site-packages/xonsh/base_shell.py", line 339, in default
    print_exception()
  File "/usr/local/lib/python3.6/site-packages/xonsh/tools.py", line 876, in print_exception
    display_error_message()
  File "/usr/local/lib/python3.6/site-packages/xonsh/tools.py", line 890, in display_error_message
    sys.stderr.write(''.join(exception_only))
  File "/usr/local/lib/python3.6/site-packages/xonsh/base_shell.py", line 173, in write
    self.std.write(std_s)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tempfile.py", line 766, in write
    rv = file.write(s)
ValueError: I/O operation on closed file.
```

xonfig : 
```
+------------------+----------------------+
| xonsh            | 0.7.3.dev12          |
| Git SHA          | 55d69ee6             |
| Commit Date      | Aug 11 22:22:24 2018 |
| Python           | 3.6.5                |
| PLY              | 3.9                  |
| have readline    | True                 |
| prompt toolkit   | 1.0.15               |
| shell type       | prompt_toolkit1      |
| pygments         | 2.2.0                |
| on posix         | True                 |
| on linux         | False                |
| on darwin        | True                 |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
+------------------+----------------------+
```

did I missing some thing, I replace prompt_tookit 2.0.4(before using)  with 1.0.15 got above erros when type `echo hello world`, if i type `ls ~/` I got output from console same as @melund

**Pull request merged**
