### PR TITLE
Unify History APIs - inps, rtns, etc.

### PR DESCRIPTION
**Pull request by mitnk**
Since sqlite history backend was just added, it's time to unify the history APIs a bit I think. In this PR I want to make behaviors of `inps`, `tss`, `outs`, and especially `rtns` consistent between history backends.

<del>Haven't dig deep, but it seems that we can remove class `JsonCommandField` and put the ``__getitem__`` logics in `JsonHistory` and only make `inps` searchable.</del>

Ideas on this?

### CODE REVIEW

**Comment by mitnk** [comment]
Currently, json backend has this issue - we are using `__xonsh_history__.rtns[-1]` as the counterpart of $? in Bash. Currently for json based history, if we set `ignoredups`, we will have an issue with it:
```
last-rtn[<not-set>]$ ls foo  # foo not exist, rtn is 1

# in another xonsh session, we create the file `foo` out.

last-rtn[1]$ ls foo  # foo now exists, rtn 0, but __xonsh_history__.rtns[-1] not got updated.
last-rtn[1]$ 
```
The first commit of this PR fixes this issue.

**Comment by mitnk** [comment]
Made `JsonHistory.buffer` contains all history items input by user, only filter out `ignoredups,ignoreerr` when flush to file. Still fixes the issue mentioned above.

Tests should pass when #1993 got merged.

**Comment by scopatz** [comment]
This seems good to me @mitnk! Any idea why didn't run on Circle?  I can test it locally if you think it is good to go.

**Comment by scopatz** [comment]
Also, super sorry for the delay reviewing this!

**Comment by mitnk** [comment]
No idea why it did not triggered the Circle ... I don't know the trigger rules for CIs.

**Comment by scopatz** [comment]
I think Circle recently "fixed" a bug. Now forks have to enable CI builds manually.  You have to go to circle and, click the add a repo button, find mitnk/xonsh, and then enable it.

**Comment by scopatz** [comment]
Also, I am seeing these errors when I test locally on linux:

```
scopatz@andromache ~/xonsh mitnk-unify-history $ pytest 
==================================================================== test session starts =====================================================================
platform linux -- Python 3.5.2, pytest-3.0.5, py-1.4.31, pluggy-0.4.0
rootdir: /home/scopatz/xonsh, inifile: setup.cfg
plugins: xonsh-0.4.7
collected 2810 items / 3 errors 

=========================================================================== ERRORS ===========================================================================
___________________________________________________________ ERROR collecting tests/test_history.py ___________________________________________________________
ImportError while importing test module '/home/scopatz/xonsh/tests/test_history.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_history.py:10: in <module>
    from xonsh.history.json import JsonHistory
../.local/lib/python3.5/site-packages/xonsh/history.py:20: in <module>
    from xonsh.diff_history import _dh_create_parser, _dh_main_action
E   ImportError: cannot import name '_dh_create_parser'
_______________________________________________________ ERROR collecting tests/test_history_sqlite.py ________________________________________________________
ImportError while importing test module '/home/scopatz/xonsh/tests/test_history_sqlite.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_history_sqlite.py:7: in <module>
    from xonsh.history.sqlite import SqliteHistory
../.local/lib/python3.5/site-packages/xonsh/history.py:20: in <module>
    from xonsh.diff_history import _dh_create_parser, _dh_main_action
E   ImportError: cannot import name '_dh_create_parser'
___________________________________________________________ ERROR collecting tests/test_xonsh.xsh ____________________________________________________________
../.local/lib/python3.5/site-packages/xonsh/pytest_plugin.py:39: in collect
    mod = importlib.import_module(self.fspath.purebasename)
../miniconda/lib/python3.5/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:986: in _gcd_import
    ???
<frozen importlib._bootstrap>:969: in _find_and_load
    ???
<frozen importlib._bootstrap>:958: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:673: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:661: in exec_module
    ???
../.local/lib/python3.5/site-packages/xonsh/__amalgam__.py:16791: in get_code
    execer = self.execer
../.local/lib/python3.5/site-packages/xonsh/__amalgam__.py:16734: in execer
    self._execer = execer = Execer(unload=False)
../.local/lib/python3.5/site-packages/xonsh/__amalgam__.py:16508: in __init__
    load_builtins(execer=self, config=config, login=login, ctx=xonsh_ctx)
../.local/lib/python3.5/site-packages/xonsh/__amalgam__.py:16384: in load_builtins
    builtins.default_aliases = builtins.aliases = Aliases(make_default_aliases())
../.local/lib/python3.5/site-packages/xonsh/__amalgam__.py:15151: in make_default_aliases
    'history': xhm.history_main,
../.local/lib/python3.5/site-packages/xonsh/__amalgam__.py:75: in __getattribute__
    m = _import_module(mod)
../miniconda/lib/python3.5/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:986: in _gcd_import
    ???
<frozen importlib._bootstrap>:969: in _find_and_load
    ???
<frozen importlib._bootstrap>:944: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:222: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:986: in _gcd_import
    ???
<frozen importlib._bootstrap>:969: in _find_and_load
    ???
<frozen importlib._bootstrap>:958: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:664: in _load_unlocked
    ???
<frozen importlib._bootstrap>:634: in _load_backward_compatible
    ???
../miniconda/lib/python3.5/site-packages/_pytest/assertion/rewrite.py:216: in load_module
    py.builtin.exec_(co, mod.__dict__)
../.local/lib/python3.5/site-packages/xonsh/history.py:20: in <module>
    from xonsh.diff_history import _dh_create_parser, _dh_main_action
E   ImportError: cannot import name '_dh_create_parser'
=================================================================== pytest-warning summary ===================================================================
WC1 None [pytest] section in setup.cfg files is deprecated, use [tool:pytest] instead.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================= 1 pytest-warnings, 3 error in 4.50 seconds =========================================================
```

**Comment by scopatz** [comment]
Although, oddly I am seeing those errors on master too.

**Comment by scopatz** [comment]
Nm this was a local configuration error. Sorry for the noise.

**Comment by scopatz** [comment]
Thanks!

**Comment by mitnk** [comment]
Thanks. Great that it's not an issue :)

**Pull request merged**
