### PR TITLE
Fix @$ subprocess operator

### LINKED ISSUE #2328: Syntax for *just* stripping last newline
`@$` is nice, but, oftentimes, you need everything to stay together as *one* argument, in which case the only way to do it is `@($(mycommand).rstrip('\n'))`. (Or at least for me, I often want it that way!) It'd be nice if there were a syntax akin to `@$` that just strips the ending newline, something that would be like bash's `$(my-command)` syntax.

### PR DESCRIPTION
**Pull request by laloch**
`@$(cmd)` operator now returns a list of tokens created by splitting the command's output at the newline character.

Closes #2328

### CODE REVIEW

**Comment by laloch** [comment]
The implementation is currently wrong. It breaks the `@$(which ls)` example from the tutorial and it is not consistent with the bash's behavior either.

**Comment by scopatz** [comment]
Thanks for pushing on this

**Comment by laloch** [comment]
OK, the `@$(cmd)` operator's behavior is now consistent with `$(cmd)` in bash.
It still can't do basic `ls /lib/modules/@$(uname -r)/kernel` though. Parser adjustment required...

**Comment by laloch** [comment]
The @$ operator does not require the leading white space character any more. Now I can do
```
$ echo %%%%@$(which ls)
%%%% ls --color=auto -v --group-directories-first
```
There is, however still an extra space between the literal argument and the output of the subprocess. @scopatz, do you have a clue about where this extra space comes from?

**Comment by scopatz** [comment]
Maybe it is coming from https://github.com/xonsh/xonsh/blob/master/xonsh/built_ins.py#L975?

**Comment by laloch** [comment]
@scopatz, thanks for the suggestion, but no, the `toks` list does not contain the spaces.

**Comment by laloch** [comment]
There is something that's ensuring the `subproc_arg` tokens to get space-separated.
```
$ echo a@$(which cp)@$(which cp)
a /usr/bin/cp /usr/bin/cp
```

**Comment by scopatz** [comment]
Yeah, I wonder if the lexer itself is adding this token (WS)?

**Comment by scopatz** [comment]
Yeah, maybe it is this line: https://github.com/xonsh/xonsh/blob/master/xonsh/lexer.py#L349

**Comment by laloch** [comment]
So, I'm back to this PR after several months.
I still can't understand where the surrounding space characters come from. The `@$` operator is translated internally by the parser to a call to `__xonsh__.subproc_captured_inject` which by itself does not return any extra spaces with this patchset applied. Yet, as can be seen below, the `@$` operator yields both extra leading and trailing space.
```
$ echo _@(1)_
_1_
$ echo _@($(pidof init).rstrip())_
_1_
$ echo _@$(pidof init)_
_ 1 _
$ __xonsh__.subproc_captured_inject(["pidof", "init"])
['1']
$ echo _@(__xonsh__.subproc_captured_inject(["pidof", "init"]))_
_1_
```

**Comment by laloch** [comment]
Never mind. I know what the problem is - it's that I'm parsing the `@$` operator without leading whitespace as a separate subprocess argument, which is obviously wrong. I need to concatenate the resulting expression with the previous argument instead.

**Comment by laloch** [comment]
This is now ready to land.
The `@$()` operator now behaves accordingly to the [tutorial](https://xon.sh/tutorial.html#command-substitution-with) and consistently with Bash `$()` operator. It doesn't require leading and trailing whitespace anymore, so `cd /lib/modules/@$(uname -r)/kernel` and similar are now possible.

**Comment by laloch** [comment]
Closes #2755 
Closes #3457

**Comment by melund** [comment]
@laloch Any idea some test fail. Are they related to this?

**Comment by laloch** [comment]
> @laloch Any idea some test fail. Are they related to this?

Yeah, I would like to know too, but I don't think they might be related.

**Comment by laloch** [comment]
Please do not merge. This is wrong once again. It breaks `@()` outer product expansion.

**Comment by laloch** [comment]
Now the `@$()` operator behaves like `@()` including the outer product expansion, so now `_@$(ls)_` yields
```
$ cd @$(mktemp -d) and touch a b c d
$ echo _@$(ls)_
_a_ _b_ _c_ _d_
```
, which is not desirable, since I aim for consistency with `$()` operator in Bash.

**Comment by scopatz** [comment]
Thanks so much for this @laloch! Can you add a couple of cases to `test_parser.py`?

**Comment by laloch** [comment]
I guess I can. The question is what is the desired behavior :wink:

**Comment by scopatz** [comment]
Well, it looks like you are having `@$(ls)` return a list of stripped strings now, rather than a string. Is that the fundemental question?

**Comment by laloch** [comment]
Nope, the question now is whether we want it to behave like `@()`:
```
$ showargs a:@$(echo a b)
['a:a', 'a:b']
```
or rather like `$()` in Bash:
```
$ showargs a:@$(echo a b)
['a:a', 'b']
```
The first case is the current state and is consistent with how `@()` behaves. The second case is consistent with how `$()` in Bash behave and with what a user would most probably expect.
The more I think about it, the more I prefer the first.

**Comment by scopatz** [comment]
Oh yeah, thanks for the clear example.  Xonsh is all about dumping terrible Bash behavior.  I think consistency with `@()` is more important, and so we should go with the first options

**Comment by laloch** [comment]
I'm pretty sure this is now ready to land - this time for real.

**Comment by scopatz** [comment]
Windows on Python 3.8 keeps failing. Can you look into it please?

**Comment by laloch** [comment]
The failures seem all to be of similar nature - either `builtins` or `__xonsh__` attribute doesn't exist without any previous error. That happens quite often and I don't have the slightest clue about how that can be possible.

**Comment by scopatz** [comment]
Hey @laloch - maybe we can get these tests to pass by merging from master.  Not sure if you did that just now?

**Comment by laloch** [comment]
Yeah, I just did a rebase on master, that was supposed to trigger the GitHub CI. It didn't.

**Comment by scopatz** [comment]
Yeah. Weird.  Maybe push an empty commit to try to trigger it?

**Comment by laloch** [comment]
I did some interactive rebasing, rewording and squashing - still the same. Let's try a dummy commit now...

**Comment by laloch** [comment]
Nope. Still the same :(

**Comment by scopatz** [comment]
OK, I am going to try to close and reopen

**Comment by scopatz** [comment]
Yeah, didn't work. I'll just merge once this passes

**Comment by laloch** [comment]
I can try to open a new PR for the same branch...

**Comment by scopatz** [comment]
Yeah, if you want that would be nice

**Comment by laloch** [comment]
No problem. Let's try it.
Closing to open a new one with the same contents.

**Pull request closed without merging**
