### PR TITLE
try latest version of doctr master

### PR DESCRIPTION
**Pull request by gforsyth**
hoping this fixes the test failures on master re: doc deployment

Unless folks have objections to use being used as a guinea-pig and then we can wait and push out a new doctr release first.

### CODE REVIEW

**Comment by gforsyth** [comment]
ack, wait, missing something

**Comment by gforsyth** [comment]
ok - cruft removed

**Comment by scopatz** [comment]
Thanks @gforsyth!

**Comment by scopatz** [comment]
Woohoo! That looks like it fixed it.

**Pull request merged**
