### PR TITLE
Non-blocking Function Aliases

### PR DESCRIPTION
**Pull request by scopatz**
This is a hopeful fix for #1819.

### CODE REVIEW

**Comment by blahgeek** [comment]
Oh wait... it seems that this PR breaks some things...:

https://asciinema.org/a/0qp48x0fku5hwh636uqsmtmwt

**Comment by blahgeek** [comment]
the asciinema is not displaying properly orz......

screen shot 2016-10-19 at 14 23 05

**Comment by scopatz** [comment]
Thanks for finding that! Can you try it now, please?

**Comment by blahgeek** [comment]
looks great to me, thanks!

**Comment by scopatz** [comment]
Ok, this *finally works* on windows.  I think that this is ready to be reviewed and/or merged.  It seems like this might help some of the other reported issues, too.

**Comment by gforsyth** [comment]
LGTM.  Thanks, @scopatz!

**Pull request merged**
