### PR TITLE
fixed code quality issues

### PR DESCRIPTION
**Pull request by withshubh**
### Description
Hi :wave: I work at [DeepSource](https://deepsource.io), I ran DeepSource analysis on the forked copy of this repo and found some interesting [code quality issues](https://deepsource.io/gh/withshubh/xonsh/issues/?category=recommended) in the codebase, opening this PR so you can assess if our platform is right and helpful for you.

### Summary of changes
- Removed length check in favour of truthiness of the object
- Removed unnecessary comprehension
- Set `check` flag to `True`
- Removed unnecessary lambda expression
- Simplified the `if` statement
- Used `is` to compare type of objects
- Added .deepsource.toml to continuously analyze the repo for code quality issues

### CODE REVIEW

**Comment by withshubh** [comment]
Hi @gforsyth please review the PR

**Comment by anki-code** [comment]
Hi @withshubh! Thank you for this! We're waiting the fixes around tests in #4217 to continue the reviewing the PRs.

**Comment by gforsyth** [comment]
Hi @withshubh -- I'm happy to review a PR with some code fix changes, but I'm not interested in enabling deepsource at this point.

**Comment by withshubh** [comment]
No worries @gforsyth just review the fixes :)

**Comment by daniel-shimon** [comment]
Hi @withshubh ! Could you rebase on `main` and remove the deepsource file and news item?
We'll be happy to merge these changes afterwards!

**Comment by daniel-shimon** [comment]
Closing this due to inactivity, feel free to reopen it and due the necessary changes!

**Pull request closed without merging**
