### PR TITLE
Fix xonfig_main bugs

### PR DESCRIPTION
**Pull request by youtux**
* main.py ignored `--config-file` command line option
* main.py called the old `xonfig.main` function, which doesn't exists anymore
* the `wiz` variable in xonfig.py was conflicting with the global `wiz`
* `_MAIN_ACTIONS` was renamed to `_XONFIG_MAIN_ACTIONS`
* `make_xonfig_wizard` returned an instance of the `wizard` module instead of an initialized Wizard.

### CODE REVIEW

**Comment by youtux** [comment]
Maybe the latest commit (24b657a) should go on its own PR. Let me know if I should do that.

**Comment by gforsyth** [comment]
Thanks @youtux -- this looks good to me.  

Could you add an entry in the `news` folder?  Instructions are available here: https://github.com/xonsh/xonsh/blob/master/CONTRIBUTING.rst#changelog

**Comment by youtux** [comment]
I didn't create a `news` entry since these changes are not present i v0.3.4, but they have been added just in the master branch. Should I add it anyway?

**Comment by gforsyth** [comment]
I guess it can go either way.  Okeydoke, merging now!

**Pull request merged**
