### PR TITLE
feat: update command completions to show description as well

### LINKED ISSUE #3823: autocompletion - show description of flags
## xonfig

<details>

```
+------------------+----------------------+
| xonsh            | 0.9.22               |
| Git SHA          | 00a42e01             |
| Commit Date      | Sep 18 19:57:59 2020 |
| Python           | 3.8.5                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.3                |
| shell type       | prompt_toolkit       |
| pygments         | 2.7.1                |
| on posix         | True                 |
| on linux         | True                 |
| distro           | manjaro              |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
+------------------+----------------------+

```

</details>

## Current Behavior

as of now the autocompletion menu looks like this
image

## Expected Behavior

it is hardly usable. we can benefit from the suggestions only if we know what each option do. For that we need to check the manual or help page. Is it possible to show the description along with the flags ? like here
1527157317-cli-autocomplete-launch-blog

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### PR DESCRIPTION
**Pull request by jnoortheen**
closes #3823

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Comment by gforsyth** [comment]
Hey @jnoortheen -- this has a few failures on the Windows side that don't look spurious

**Comment by jnoortheen** [comment]
> Hey @jnoortheen -- this has a few failures on the Windows side that don't look spurious

It has something to do with how the executable names are capitalized. I haven't checked how it works usually. I will fix it later. 

For now, can you take a look at https://github.com/xonsh/xonsh/pull/4486 I have some other PRs waiting for this.

**Comment by jnoortheen** [comment]
@gforsyth the PR is ready for review now.

**Comment by gforsyth** [comment]
Hey @jnoortheen -- do you have any screenshots of what's supposed to happen here?  I have `$CMD_COMPLETIONS_SHOW_DESC=True` but it doesn't seem to have changed anything

```
> xonfig
+------------------+----------------------+
| xonsh            | 0.11.0.dev17         |
| Git SHA          | e1a64bc2             |
| Commit Date      | Nov 30 09:48:22 2021 |
| Python           | 3.9.7                |
| PLY              | 3.11                 |
| have readline    | True                 |
| prompt toolkit   | 3.0.22               |
| shell type       | prompt_toolkit       |
| history backend  | sqlite               |
| pygments         | 2.10.0               |
| on posix         | True                 |
| on linux         | True                 |
| distro           | unknown              |
| on wsl           | False                |
| on darwin        | False                |
| on windows       | False                |
| on cygwin        | False                |
| on msys2         | False                |
| is superuser     | False                |
| default encoding | utf-8                |
| xonsh encoding   | utf-8                |
| encoding errors  | surrogateescape      |
| on jupyter       | False                |
| jupyter kernel   | None                 |
| xontrib          | []                   |
| RC file          | []                   |
+------------------+----------------------+
```

**Comment by jnoortheen** [comment]
@gforsyth perhaps you need to spawn new window with the variable set. It will be showing the full path to the executable. We can be sure what is getting executed and whether it is an alias or not ... will save `which X` time 

image

**Comment by gforsyth** [comment]
I might be misunderstanding, but shouldn't this show that `ga` is an alias for `git add`?

2021-12-07-094812_685x681_scrot

**Review by gforsyth — APPROVED** [review]
Thanks for putting this together @jnoortheen !

**Pull request merged**
