### PR TITLE
removes validation on getting environment variables. 

### PR DESCRIPTION
**Pull request by scopatz**
Should only be used for setting

No news item needed, because no release has happened. 

CC @xonsh/xore

### CODE REVIEW

**Comment by scopatz** [comment]
This is ready for review!

**Comment by anki-code** [comment]
After this PR the great case will not work:
```
$MY_DIR = '/tmp'
 ${...}.register('MY_DIR', type='path')
    if $MY_DIR.exists(): # here will be string variable instead of path and there will be an exception
        pass
```
I suggest to add at least this code to this PR 

https://github.com/xonsh/xonsh/blob/5363f4ffe06dd8d831fea6a28967f41feab7cd82/xonsh/environ.py#L2161-L2174

**Comment by scopatz** [comment]
@anki-code - I think we should have that discussion in a separate issue / PR. As I have said elsewhere I think what you are proposing should be its own API and not be hidden or happen automatically in other operations. This is because it is likely to have unforeseen consequences by users.

**Comment by anki-code** [comment]
Okay

**Comment by scopatz** [comment]
CC @xonsh/xore - this is ready for review and is blocking the next release

**Comment by gforsyth** [comment]
Thanks, @scopatz !

**Pull request merged**
