### PR TITLE
Add pypy3 to travis testcases

### PR DESCRIPTION
**Pull request by traverseda**

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks for this @traverseda - I don't think that this needs a news entry.

**Comment by traverseda** [comment]
*and* it shows the valueError I've been getting! https://travis-ci.org/xonsh/xonsh/jobs/311370159#L781

**Comment by scopatz** [comment]
Very interesting :)

**Comment by scopatz** [comment]
It seems to be failing on just one of the integration tests.  This can almost certainly be made safer since all of that is xonsh code.

**Comment by scopatz** [comment]
Interesting, it is almost as if the command is finished executing and the file handle closed before we can even set up the command pipeline.

**Comment by traverseda** [comment]
I imagine it has something to do with pypy not using refcounting for garbage collection: http://doc.pypy.org/en/latest/cpython_differences.html#differences-related-to-garbage-collection-strategies

That is, delayed file cleanup. I suspect that closing files explicitly in the hottest code-paths will mitigate this, and some other issues. If that's not already happening.

This might have something to do with #2222 and the like. It's just more visible on pypy because of the deferred cleanup.

**Comment by scopatz** [comment]
Something about that strikes me as incorrect though. The problem here is that the file is being closed too soon.

**Comment by scopatz** [comment]
I wish I had a way to test this locally...

**Comment by traverseda** [comment]
Is pypy3 unavailable on your platform? I suppose I could extend the xonsh-in-docker script with pypy support sometime tomorrow.

**Comment by scopatz** [comment]
> Is pypy3 unavailable on your platform?

It doesn't seem to be available on Ubuntu 17.04 or from conda...

> I suppose I could extend the xonsh-in-docker script with pypy support sometime tomorrow

That would be awesome! I'd really appreciate it.

**Comment by traverseda** [comment]
Well, this branch is now using pypy with docker. Recomended usage is `./xonsh-in-docker.py --pypy "3-5.8"`.

I also merged in the 6.0 tag, since my local master was a bit behind and I wanted to run the test cases locally.

**Comment by scopatz** [comment]
Thanks @traverseda This has led me down the rabbit hole of weird bugs, see #2222 and #2259

**Comment by scopatz** [comment]
Actually, #2559 may address this ValueError that you were seeing.

**Comment by gforsyth** [comment]
Hey @traverseda -- this is great to have.  Since we are currently expecting pypy to fail, do we want to allow failures until things get sorted?  Or should we hold off on having these tests until they're resolved?

**Comment by traverseda** [comment]
*Probably* better to allow failures, just in case there's changes to the test cases.

**Comment by gforsyth** [comment]
Hi @traverseda -- sorry for the long delay in getting back to this.

It looks like Travis is erroring out because `pip` can't find a compatible version of `ply` -- not sure how to handle that from the pypy side of things.

Also, for some reason the changes to the `setup.cfg` have made Circle ignore all of our flake8 skip rules, causing _thousands_ of errors.

**Comment by traverseda** [comment]
Ouch. I am unlikely to have time to dig into that for a few weeks, but this definitely isn't urgent.

**Comment by gforsyth** [comment]
> Ouch. I am unlikely to have time to dig into that for a few weeks, but this definitely isn't urgent.

No worries, I just wanted to make sure this didn't get left behind.  Thanks!

**Comment by gforsyth** [comment]
Hey @traverseda -- is there anything we can help with to move this along?  It'd be great to have pypy testing in CI

**Comment by scopatz** [comment]
merged #2792, closing

**Pull request closed without merging**
