### PR TITLE
The order of sections in docs changed and "Try it" section removed

### PR DESCRIPTION
**Pull request by anki-code**
Hello!

1. The order of sections in docs changed.

2. "Try it" section removed.

3. Added text to readme.

Why removed? Because:

<details>

Screenshot_20200917_212832

Screenshot_20200917_215823

Screenshot_20200917_212854

</details>

### CODE REVIEW

**Comment by scopatz** [comment]
I am OK with this.  What does the rest of @xonsh/xore think?

**Comment by melund** [comment]
I think this change is fine. I haven't been able to use the "run this" button anyway. 

image

**Comment by scopatz** [comment]
I think this OK to merge then... Not sure why it is failing on win

**Comment by anki-code** [comment]
Maybe just merge?

**Comment by scopatz** [comment]
Can you try merging from master?

**Comment by anki-code** [comment]
From master - #3791

**Pull request closed without merging**
