### PR TITLE
Macro contexts refactor

### PR DESCRIPTION
**Pull request by scopatz**
This includes #2073, which I hope will fix the appveyor issues.

### CODE REVIEW

**Comment by astronouth7303** [comment]
The `distributed` xontrib uses these, right? Does it need to be rewritten?

**Comment by scopatz** [comment]
I looked at the distributed xontrib last night when I was writing this and I couldn't find anything that needed changing. Usage of the distributed xontrib will need to change, but this raises an exception to that effect.

**Comment by astronouth7303** [comment]
Do we want to make note of that in the news item?

**Comment by scopatz** [comment]
done

**Pull request merged**
