### PR TITLE
readme twitter

### PR DESCRIPTION
**Pull request by anki-code**

### CODE REVIEW

**Comment by scopatz** [comment]
Hmm It is pretty strange to have a tweet with pre-filled in text. Maybe this could just be a link to the `#xonsh` search?

**Comment by scopatz** [comment]
Weird, that link still opens a prompt for me write a new tweet

**Comment by anki-code** [comment]
>that link still opens a prompt for me write a new tweet

Right behaviour. The button name is "tweet now" - create a tweet.

Screenshot_20201022_192726

**Comment by scopatz** [comment]
Oh I see. I guess I liked the original text better then. Sorry @anki-code!

**Comment by laloch** [comment]
I don't think Twitter fits between the rest of the buttons - certainly not at the first place.

**Comment by anki-code** [comment]
Added as text.

**Comment by scopatz** [comment]
LGTM! Thanks @anki-code!

**Pull request merged**
