### PR TITLE
Add Python 3.8 assignment expressions ("walrus"/PEP 572)

### PR DESCRIPTION
**Pull request by laloch**
~~WIP; missing lexer/parser tests.~~

Suggestions welcome...

Relates to #3101

### CODE REVIEW

**Comment by daniel-shimon** [comment]
Nice!

I wanted to do this myself but didn't really have the time

How about making the changes to xonsh/parsers/base.py in xonsh/parsers/v38.py instead?
For instance:

```python

def p_test_or_star_expr(self, p):
        """test_or_star_expr : test
        """test_or_star_expr : namedexpr_test
                             | star_expr
        """
        super().p_test_or_star_expr(p)

```

For all the functions you're changing

**Comment by laloch** [comment]
Hi @daniel-shimon, the version you have commented on is now gone. But in general, I wanted to put as much as possible into the common base and only override in v38.py what's really specific for v3.8. For instance `namedexpr_test` can simply be `namedexpr_test : test` in older grammars and only becomes `namedexpr_test : test [COLONEQUAL test]` in v3.8. This reduces the amount of code that needs to be overriden.

**Comment by laloch** [comment]
But yes, what you say @daniel-shimon, probably applies to `p_testlist_comp_*`. OK, let's change it once again...

**Comment by scopatz** [comment]
This is awesome! Thanks @laloch!

**Pull request merged**
