### PR TITLE
Paren Completions in Readline

### PR DESCRIPTION
**Pull request by scopatz**
This addresses #2126 for me.  @laerus, maybe you want to take a look?

### CODE REVIEW

**Comment by scopatz** [comment]
And again, the travis failures aren't real.

**Comment by scopatz** [comment]
updated this from master

**Comment by scopatz** [comment]
Updated from master again. This should be good to go now that #2126 has been merged.

**Comment by gforsyth** [comment]
This fixes the issue for me, merging in.

**Comment by gforsyth** [comment]
Thanks, @scopatz !

**Comment by scopatz** [comment]
Thanks @gforsyth!

**Pull request merged**
