### PR TITLE
LS_COLORS

### LINKED ISSUE #2767: How does changing $LS_COLORS work?
I wanted to change the way that directory colors look on my system when typing `ls`. A manual to do so using the `$LS_COLORS` environment variable is here:

http://www.bigsoft.co.uk/blog/2008/04/11/configuring-ls_colors

I notice that in bash, `$LS_COLORS` is set somewhere by default. xonsh also seems to use these colors, however in xonsh, `$LS_COLORS` is not set at all.

If I set $LS_COLORS, for instance by using `$LS_COLORS="ow=01;33"` to just change other-writable directories, xonsh seems to use this while also using the rest of the default `$LS_COLORS` for everything else.

Is this behavior documented somewhere? How do people recommend that I change $LS_COLORS?

My xonfig

```
+------------------+---------------------+
| xonsh            | 0.7.3               |
| Git SHA          | 9bbbf07b            |
| Commit Date      | Aug 2 18:08:44 2018 |
| Python           | 3.5.2               |
| PLY              | 3.9                 |
| have readline    | True                |
| prompt toolkit   | 2.0.4               |
| shell type       | prompt_toolkit2     |
| pygments         | None                |
| on posix         | True                |
| on linux         | True                |
| distro           | neon                |
| on darwin        | False               |
| on windows       | False               |
| on cygwin        | False               |
| on msys2         | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

### PR DESCRIPTION
**Pull request by scopatz**
The basic gist of this PR is that it sets the  `$LS_COLORS` env var in such a way that respects `$XONSH_COLOR_STYLE`. There were a bunch of parts of the color conversion that were missing, and then getting this to be suitably lazy so that it didn't increase start up time too much required some updates to event handling. 

Again, this was waaaaay trickier than expected, but it is pretty cool that it works.

This closes #2767

### CODE REVIEW

**Comment by scopatz** [comment]
@xonsh/xore - The tests pass and I think it is ready for review! It would be great if you could try it out locally first, too.  I have put it through the ringer on my side, but ANSI escape codes are many and varied :wink:

**Comment by melund** [comment]
Sure, I read through some of the code earlier today. Looking forward to testing it :)

**Comment by scopatz** [comment]
Awesome! Thanks @melund!

**Comment by melund** [comment]
It seems to work well. I will continue to use it tomorrow.
Maybe repr of the $LS_COLORS could also print what the different types mean:
```
$ $LS_COLORS
xonsh.__amalgam__.LsColors(
{'bd': ('BACKGROUND_BLACK', 'YELLOW'),  # Block (buffered) special file
 'ca': ('BLACK', 'BACKGROUND_RED'),  # file with capability
 'cd': ('BACKGROUND_BLACK', 'YELLOW'),  # Character (unbuffered) special file
 'di': ('BOLD_CYAN',),  # Directory
 'do': ('BOLD_PURPLE',), # Door
```

**Comment by melund** [comment]
I haven't had any issues with this. So let us just all test it in master :)

**Pull request merged**
