### PR TITLE
fixed callable alias e>o redirection

### PR DESCRIPTION
**Pull request by scopatz**
This should address #2222

### CODE REVIEW

**Comment by scopatz** [comment]
OK, I think this is ready for review.

**Comment by mitnk** [comment]
Seems still has this issue:

```
$ f o>e
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/base_shell.py", line 328, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/codecache.py", line 68, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/built_ins.py", line 881, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/built_ins.py", line 844, in run_subproc
    command.end()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/proc.py", line 2010, in end
    self._end(tee_output=tee_output)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/proc.py", line 2018, in _end
    for _ in self.tee_stdout():
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/proc.py", line 1934, in tee_stdout
    for line in self.iterraw():
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh/proc.py", line 1816, in iterraw
    stdout = NonBlockingFDReader(stdout.fileno(), timeout=timeout)
ValueError: I/O operation on closed file
```

xonfig:

```
+------------------+---------------------+
| xonsh            | 0.6.0.dev3984       |
| Git SHA          | 7af4ca53            |
| Commit Date      | Dec 8 14:36:33 2017 |
| Python           | 3.6.2               |
| PLY              | 3.9                 |
| have readline    | True                |
| prompt toolkit   | 1.0.13              |
| shell type       | prompt_toolkit      |
| pygments         | 2.2.0               |
| on posix         | True                |
| on linux         | False               |
| on darwin        | True                |
| on windows       | False               |
| on cygwin        | False               |
| is superuser     | False               |
| default encoding | utf-8               |
| xonsh encoding   | utf-8               |
| encoding errors  | surrogateescape     |
+------------------+---------------------+
```

**Comment by scopatz** [comment]
Hi @mitnk - are you using the following `f()`?

```
def _f(args, stdout):
    print('Wow Mom!', file=stdout)
```

One of the problems with this alias is that the `stdout` arg is actually `stdin`.  We only match on argument position, not argument name (though that is a nice idea!).  So to properly set stdout, we'd have to use:

```
def _f(args, stdin, stdout):
    print('Wow Mom!', file=stdout)
```

I am not suprised that there are weird closed file errors when writing stdin and redirecting stdout to stderr.  Perhaps the error message here could be better too...

**Comment by mitnk** [comment]
Oh, I didn't notice that :)

However same error raises with `def _f(args, stdin, stdout):`.

**Comment by scopatz** [comment]
Hi @mitnk - that is very strange.  What error is it giving? The same one?  The test suite has a fix for o>e that works on my machine.

**Comment by mitnk** [comment]
Yes, the same error on Mac. Just tested on a Linux box, the issue indeed was fixed. So I think we can merge this PR.

**Comment by gforsyth** [comment]
Tests are all passing and it works locally on a mac over here, so I'm going to go ahead and merge this.  @mitnk, if problems persist for you on OSX please let us know.

**Comment by gforsyth** [comment]
Thanks, @scopatz!  And sorry for the delay!

**Comment by scopatz** [comment]
No worries! Happy to have it in!

**Pull request merged**
