### PR TITLE
completer turn off warning

### PR DESCRIPTION
**Pull request by 6syun9**
fix: https://github.com/xonsh/xonsh/issues/3165

We can use `warnings.catch_warnings`. But It was useless if I tried.

> Once the context manager exits, the warnings filter is restored to its state when the context was entered. This prevents tests from changing the warnings filter in unexpected ways between tests and leading to indeterminate test results. The showwarning() function in the module is also restored to its original value. Note: this can only be guaranteed in a single-threaded application. If two or more threads use the catch_warnings context manager at the same time, the behavior is undefined.

ref: https://docs.python.org/3/library/warnings.html#testing-warnings

So I added `Decorator to turn off warning temporarily` .

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks @6syun9! Can you please merge from master to get the correct CI configuration.

**Comment by 6syun9** [comment]
@scopatz um...CI test passed.
But I'm warnings have become visible after completer.

For example, after completion...
```
 $ cd tmp/
/Users/6syun9/.pyenv/versions/3.6.8/lib/python3.6/threading.py:916: ResourceWarning: unclosed file <_io.TextIOWrapper name=7 encoding='utf-8'>
  self.run()
```
I need to review the warning settings. WIP.

**Comment by 6syun9** [comment]
@scopatz Sorry, It was caused by the fact that I did not have the latest version.
The behavior was fixed!

**Comment by melund** [comment]
Thanks a lot @6syun9.

**Pull request merged**
