### PR TITLE
Use `__all__` in the included xontribs

### PR DESCRIPTION
**Pull request by astronouth7303**
While this isn't strictly necessary, it helps keep the code tidy and keeps the stock xontribs as examples of best practices.

### CODE REVIEW

**Comment by laerus** [comment]
Cool! just flake8 tears.. on not enough blank lines.

**Comment by astronouth7303** [comment]
Need an image from wrath of kahn: "FLAKE8!!!!!"

Is there a reliable way to run flake8 locally with the same settings as travis?

**Comment by laerus** [comment]
I just run flake8 on the file and ignore the 'line too long' errors etc. `setup.cfg` contains the errors tha flake ignores, not sure how to include them on a flake run though.

**Comment by astronouth7303** [comment]
Yeah, there's a `setup.py flake8` but it seems to ignore those settings.

**Comment by astronouth7303** [comment]
`py.test --flake8 -q` would be my suggested.

**Comment by gforsyth** [comment]
Thanks, @astronouth7303!  Sorry for the delay in getting to this!

**Comment by scopatz** [comment]
Great to have this!

**Pull request merged**
