### PR TITLE
Add environment variable for hg binary name

### PR DESCRIPTION
**Pull request by MatthewTurk**
This adds an environment variable for specifying the hg binary name to use; this can, for instance, allow specification of the `chg` binary for (considerably) faster queries of the status.

### CODE REVIEW

**Comment by gforsyth** [comment]
Hey @MatthewTurk , thanks for putting this in!  There are a few test failures and you'll also need to add a news entry. 

Also, if we move forward with this we'll also need a `VarDocs` entry for the new envvar. 

Question, though: is this something that can be done by using an alias instead? e.g. `aliases['hg'] = 'chg'`

**Comment by MatthewTurk** [comment]
Thanks, @gforsyth !  I will try out with `aliases`, which would be much nicer.  If that works (and I bet it will, based on you suggesting it :)), I'll rescind the PR, and if it doesn't, I'll update with your comments.

**Comment by gforsyth** [comment]
Cool! If it _does_ work and there's an improvement in prompt time, this would be a great tip to put on the customizations page in the docs!

**Comment by scopatz** [comment]
Thanks for putting this in @MatthewTurk! It looks like this was branched from an incomplete topical branch I was working on last night. That might explain some of the CI issues.

**Comment by MatthewTurk** [comment]
Whoops!  My mistake.  I wasn't able to get aliases to work, which I'll
investigate further before rebasing/updating/blahblah.  Thanks folks!

**Comment by scopatz** [comment]
Hey @MatthewTurk, any luck with this? Happy to help however I can. I do want to make sure that the hg support is top-notch

**Comment by scopatz** [comment]
Hi All, should we close this given #2233?

**Comment by MatthewTurk** [comment]
Fine with me!

**Comment by scopatz** [comment]
Cool thanks!

**Pull request closed without merging**
