### PR TITLE
skip foreign

### LINKED ISSUE #2810: How to disable 'skipping application of alias' message and let xonsh aliases take precedence
## xonfig

```
+------------------+-----------------+
| xonsh            | 0.7.7           |
| Python           | 3.6.5           |
| PLY              | 3.9             |
| have readline    | True            |
| prompt toolkit   | 2.0.4           |
| shell type       | prompt_toolkit2 |
| pygments         | None            |
| on posix         | True            |
| on linux         | True            |
| distro           | Ubuntu          |
| on darwin        | False           |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

## Expected Behavior

I have just started using xonsh and would like to make it my main shell, but still be able to use bash aliases in both places. Ideally, xonsh should ignore any bash aliases that have the same name. If an alias has been defined in xonsh, I would like it to take precedence over any foreign aliases.

I don't want to see this error message every time I open the shell, and the `--overwrite-alias` option seems to do the opposite of what I want. Perhaps the ideal solution is to only print this message when `XONSH_DEBUG` is set.

## Current Behavior

I get this message every time I open xonsh:
```
Skipping application of 'ls' alias from 'bash' since it shares a name 
with an existing xonsh alias. Use "--overwrite-alias" option to 
apply it anyway.
```

## Steps to Reproduce

Open xonsh with bash sourced as a foreign shell, since bash usually has `alias ls='ls --color=auto'` defined by default.

### PR DESCRIPTION
**Pull request by scopatz**
Closes #2810

### CODE REVIEW

**Comment by gforsyth** [comment]
Looks good to me.  The Appveyor failure is a spurious timeout thing and isn't worth waiting on Appveyor to run again.

Time to get us some of those Azure pipelines running.

Thanks, @scopatz!

**Comment by scopatz** [comment]
> Time to get us some of those Azure pipelines running.

Definitely!

**Comment by comfortablynick** [comment]
Thank you for adding this option, @scopatz!

**Comment by jeremyepling** [comment]
@scopatz / @gforsyth , I'm a product manager on Azure Pipelines. Let me know if you have any questions or suggestions when you set it up.

**Comment by scopatz** [comment]
Thanks @jeremyepling! Will do.

**Comment by scopatz** [comment]
When trying to register the xonsh org, I got:

> VS850012: The specified name is reserved: xonsh

Any ideas?

**Pull request merged**
