### PR TITLE
Add man-page completion for bash and zsh

### PR DESCRIPTION
**Pull request by NilsIrl**
Not CHANGELOG worthy

### CODE REVIEW

**Comment by laloch** [comment]
Does bash (bash-completion) really support the feature? I don't think so.

**Comment by NilsIrl** [comment]
> Does bash (bash-completion) really support the feature? I don't think so.

image

**Comment by laloch** [comment]
Yes, but I think that the feature is about **options** completion, based on the contents of the corresponding man page.

**Comment by gforsyth** [comment]
Thanks for putting this in @NilsIrl !  
Bash completion definitely offers the completion of the names of individual man-pages -- the feature mentioned on the website refers to completing `-args` options by parsing the man pages which (I believe) is offered only by `xonsh` and `fish`.

Maybe we can figure out a language tweak to clarify that point?

**Comment by NilsIrl** [comment]
Maybe "command completion from man-pages".

**Pull request closed without merging**
