### PR TITLE
Robustness fixes to tee

### PR DESCRIPTION
**Pull request by scopatz**
This should address #1838.  @derekbrokeit would you mind trying this out, please? Thanks!

### CODE REVIEW

**Comment by derekbrokeit** [comment]
That seems to have fixed it! Thanks @scopatz

**Comment by melund** [comment]
This didn't make any difference to me. 

With `win_unicode_console` installed I get another error: 

```
$ cls
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "C:\Users\mel\Documents\xonsh\xonsh\base_shell.py", line 288, in default
    run_compiled_code(code, self.ctx, None, 'single')
  File "C:\Users\mel\Documents\xonsh\xonsh\codecache.py", line 65, in run_compiled_code
    func(code, glb, loc)
  File "<xonsh-code>", line 1, in <module>
  File "C:\Users\mel\Documents\xonsh\xonsh\built_ins.py", line 825, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "C:\Users\mel\Documents\xonsh\xonsh\built_ins.py", line 793, in run_subproc
    command.end()
  File "C:\Users\mel\Documents\xonsh\xonsh\proc.py", line 1572, in end
    for _ in self.tee_stdout():
  File "C:\Users\mel\Documents\xonsh\xonsh\proc.py", line 1512, in tee_stdout
    sys.stdout.buffer.write(line)
AttributeError: 'TextTranscodingWrapper' object has no attribute 'buffer'
```
The only way I can solve that is by adding:

```
win_unicode_console.streams.stdout_text_transcoded.buffer = win_unicode_console.streams.stdout_text_str
```
in my xonshrc file. Does it tell you anything @scopatz? 

Should add this when activating `win_unicode_console`, or maybe drop `win_unicode_console` support?

**Comment by scopatz** [comment]
Hi @melund - yes, that for that traceback.  fix incoming.

**Comment by scopatz** [comment]
Fix is in #1844

**Comment by melund** [comment]
Yes. That works for me. Thanks.

**Pull request merged**
