### PR TITLE
[WIP] Events Documentation

### PR DESCRIPTION
**Pull request by astronouth7303**
{Future site of a documentation-related pull request.}

Note: This contains the news item for events, so it should be at least partially merged before the next release.

### CODE REVIEW

**Comment by scopatz** [comment]
Why don't we just merge this and then you can open up a new PR when this branch is updated?

**Comment by astronouth7303** [comment]
Give me a few days to try to get the tutorial out :P We're a few weeks out from the next release, right?

**Comment by scopatz** [comment]
Well, we'll probably do a micro release in the next couple of days.  But I would expect we are a couple of weeks from the 0.5.

**Comment by scopatz** [comment]
No worries about not merging this

**Comment by astronouth7303** [comment]
Ok, I'll try to see if I can get a primitive tutorial in. Otherwise, I'll do some git sorcery and submit a news-only PR.

**Comment by astronouth7303** [comment]
Ok, got a first draft done. I would call this mergable in the sense that it's not a total embarrassment if it goes live, and users should have some sense of how to use it.

**Comment by scopatz** [comment]
Great! I am happy with this, thanks.

**Pull request merged**
