### PR TITLE
add MSYS2 support and fix Cygwin support

### PR DESCRIPTION
**Pull request by koehlma**
Hey there,

while running xonsh within an MSYS2 environment on Windows 10 I encountered issues similar to #2370 and in addition short-running processes seemed to randomly suspend themselves to the jobs list. When processes freezed, they did however not consume any resources, but instead seemed to have just stopped. Since this happens nondeterministically (and after some debugging) I believe there is some race condition within MSYS2 (Cygwin) with calling `Popen.send_signal` in ` pause_call_resume` in `proc.py` which unexpectedly suspends processes.

Anyway, this pull request adds support for MSYS2 and fixes those issues (at least for me :D).

Thank you all very much for this great piece of software. Windows became finally somewhat usable with xonsh. ;)

Best regards,
Maximilian

### CODE REVIEW

**Comment by astronouth7303** [comment]
Can MSYS2 and Cygwin please be added to the appveyor testing matrix?

**Comment by koehlma** [comment]
Here you go. However, I do not know how to automate the process of installing Python and pip within the Cygwin environment provided by AppVeyor, so for now, I only added MSYS2 to the testing matrix. Furthermore, I allowed the MSYS2 tests to fail. I think this is a good idea until someone fixed the remaining issues with MSYS2.

**Comment by scopatz** [comment]
Hey! This looks great! Sorry for taking so long to review.

**Comment by scopatz** [comment]
Thanks a million for putting this in @koehlma!

**Pull request merged**
