### PR TITLE
Import Events and Matplotlib Interactive Fixes

### PR DESCRIPTION
**Pull request by scopatz**
This PR adds six new events for hooking into Python's import mechanism.  Now you can register a handler for before/after a module is search for, created, or exec'd. There are probably some pretty crazy abuses of this. 

The initial application of this is to help fix some of the interactivity issues with matplotlib. This should close out #1043. Some of the problems mentioned in that issue seemed to related to mpl v1.x and have since been fixed in mpl v2.x.  This PR tries to address the remaining problems.

### CODE REVIEW

**Comment by astronouth7303** [comment]
This seems absurdly dangerous. Are there other ways to accomplish this without new events? Or with events that are not so broad in scope and power?

**Comment by scopatz** [comment]
I don't know that this is any more or less dangerous than what Python's import system already provides. Anyone could write an import finder and stick it at the start of the `sys.meta_path` that would totally disrupt the import mechanism, if they wanted.  All this really provides is a translation layer between the two powerful systems. It doesn't stop bad behaviour but it does make good behaviour easier.

**Comment by melund** [comment]
@scopatz : I can't get this working: 

image

It just shows a blank figure. If I then run `plt.show()` the figure renders but then the prompt it blocked. Closing the figure returns the prompt. But if I press `ctrl-c` instead I get the following error. 
```
snail@sea ~\Documents\xonsh ie
$ plt.show() (CTRL-C)
QObject::killTimers: timers cannot be stopped from another thread
PS C:\Users\mel\Documents\xonsh>
```

**Comment by scopatz** [comment]
Thanks for trying it out @melund. I think this is almost certainly a matplotlib & windows issue. I know that they have had issues like this open in the past (https://github.com/matplotlib/matplotlib/issues/3052).  Perhaps it is best to report this there?  

This PR does fix some of the issues I was seeing on Linux, though.

Having dived into the matplotlib code to write this PR, I am not convinced that their interactive mode is really well thought out. They special case a lot of stuff to work for just IPython. It would be much better to have a real API to work with.

**Comment by melund** [comment]
Then I am OK with merging.

**Comment by scopatz** [comment]
Thanks @melund! I *do* think this is worth reporting over at matplotlib. They seem to be trying to move towards something better. Bringing it up again couldn't hurt.

**Comment by melund** [comment]
I agree. Also maybe a new issue for xonsh so we don't forget. I don't have time to do it right now thus.

**Comment by scopatz** [comment]
Sure, but let's close out the old bug and label the new one as a feature.

**Comment by melund** [comment]
Agreed

Den tir. 21. feb. 2017 05.47 skrev Anthony Scopatz <notifications@github.com

**Pull request merged**
