### PR TITLE
More which and improvements

### PR DESCRIPTION
**Pull request by scopatz**
This expands the callable alias API a bit and makes it so that ``$(which cmd)`` does the right thing.

### CODE REVIEW

**Comment by scopatz** [comment]
Would anyone mind taking a look at this, please? Thanks!

**Comment by melund** [comment]
I did. Didn't I? LGTM, except for my single comments which may of course not be valid.

**Comment by scopatz** [comment]
Hi @melund - I am not seeing any of your comments on this PR, except for the one I am responding to :)  Maybe they are held up in "review changes"

**Comment by melund** [comment]
Oh.. you are right. I just haven't understood Github's new review system.

**Comment by melund** [comment]
Well. It does improve which and it also fixes the root problem in #1826. The general issue with aliases is still there ( #1828 ) and I don't think I know how to fix it.

**Pull request merged**
