### PR TITLE
it's time then

### PR DESCRIPTION
**Pull request by laerus**
was staring at `run_subproc` for so long.
here are some tests, wanted to write a lot more and i can still can if you want me to @scopatz 
and these probably would be better with `tmpdir` fixture.

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks @laerus! I have started on a `run_subproc()` refactor, and so these will be super helpful.

**Comment by laerus** [comment]
i will give more time on this later today or tomorrow, will try and write some more tests to include piping and such.

**Comment by laerus** [comment]
note that i'm pushing this into your `rs` branch not in master

**Comment by scopatz** [comment]
Ahh good point. Then I would expect this to fail right now, because that branch is currently totally broken :)

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
