### PR TITLE
feat: auto-completion support for source-foreign

### PR DESCRIPTION
**Pull request by jnoortheen**
## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Comment by jnoortheen** [comment]
@omjadas I haven't used foreign functions. Could you check I am not missing anything? also the todo item. I am not sure how `sourcer` is set as None and used to set prevcmd

**Comment by omjadas** [comment]
> @omjadas I haven't used foreign functions. Could you check I am not missing anything? also the todo item. I am not sure how `sourcer` is set as None and used to set prevcmd

`sourcer` should either be made required, or `DEFAULT_SOURCERS` should be used to determine a default (potentially with `source` as a fallback)

**Comment by jnoortheen** [comment]
> 
> `sourcer` should either be made required, or `DEFAULT_SOURCERS` should be used to determine a default (potentially with `source` as a fallback)

@omjadas I have set it to return error if sourcer not specified. 

Can you please check the working of these commands ? I have added auto-completion support to these commands.

**Comment by omjadas** [comment]
> > `sourcer` should either be made required, or `DEFAULT_SOURCERS` should be used to determine a default (potentially with `source` as a fallback)
> 
> @omjadas I have set it to return error if sourcer not specified.
> 
> Can you please check the working of these commands ? I have added auto-completion support to these commands.

I have tested `source-foreign`, `source-zsh`, and `source-bash`. The actual foreign shell functionality is working as I would expect. One thing that might be a bit confusing with this change though is how the `interactive` and `safe` command line flags now work. Since they both default to `True` when I specify them from the CLI it actually sets them to False. I would probably recommend inverting the flags to be `--no-interactive` (or maybe `--non-interactive`) and `--no-safe` (or maybe `--unsafe`) and defaulting them to `False`, just so it makes a bit more sense when they are specified.

**Comment by jnoortheen** [comment]
> One thing that might be a bit confusing with this change though is how the `interactive` and `safe` command line flags now work. Since they both default to `True` when I specify them from the CLI it actually sets them to `False` (previously you had to do `--flag false`). I would probably recommend inverting the flags to be `--no-interactive`/`--non-interactive` and `--no-safe`/`--unsafe` and defaulting them to `False`, just so it makes a bit more sense when they are specified.

Thanks for the check. I have changed the flag names.

**Pull request merged**
