### PR TITLE
test main to run seprately

### PR DESCRIPTION
**Pull request by scopatz**
no news needed

### CODE REVIEW

**Comment by scopatz** [comment]
@xonsh/xore - it looks like this works!

**Comment by jb-leger** [comment]
It seems in `xonsh.xonsh` on azure that only separately tests are run, not the others. Or I can find where there are run.

**Comment by scopatz** [comment]
Ahh excellent point @jb-leger! Can't believe that I missed that

**Comment by scopatz** [comment]
Alright, this is fixed now

**Comment by melund** [comment]
Great that is fixed. Well spotted @jb-leger

**Pull request merged**
