### PR TITLE
Enabled virtual terminal processing for the prompt toolkit shell

### PR DESCRIPTION
**Pull request by scopatz**
This should address #2234

### CODE REVIEW

**Comment by melund** [comment]
Lgtm. But let wait a little to hear from @kirbyfan64 before merging.

**Comment by kirbyfan64** [comment]
Works perfectly now! :+1:

**Comment by melund** [comment]
Great. I think we can spare Travis the work this time. The mac backlog seems to be enormous at the moment.

**Comment by melund** [comment]
Poor Travis. The OSX stuff takes it toll

**Pull request merged**
