### PR TITLE
remember windows when checking for abs paths

### PR DESCRIPTION
**Pull request by gforsyth**
potential fix for #1691 

@astronouth7303 -- not sure if path completion will *work* but I think this will stop the infinite recursion

### CODE REVIEW

**Comment by scopatz** [comment]
Should we wait for @astronouth7303? Or is this good to merge now?

**Comment by gforsyth** [comment]
I'd like for someone who had the error to confirm that it's fixed -- I think this will do it but there could be other things I haven't accounted for

**Comment by scopatz** [comment]
Makes sense @gforsyth!

**Comment by bobhy** [comment]
The fix works for me, FWIW.  I was able to repro by:
```
dir ./abc<tab>    # no files abc* in this directory
```
Before the fix, I got the recursion.  After the fix, cursor just stayed put at end of line, as expected.

Fix doesn't break: 
``` 
dir abc<tab>
```
Cursor stays put here, too.

**Comment by melund** [comment]
Great. I will merge then

**Comment by astronouth7303** [comment]
After pulling from `master`, I'm still getting infinite recursions if `$SUBSEQUENCE_PATH_COMPLETION` is `True`.

**Pull request merged**
