### PR TITLE
Fix DeprecationWarning while initializing `Expression`

### PR DESCRIPTION
**Pull request by 0xba1a**
Fixes the issue #5738 

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Comment by 0xba1a** [comment]
> **Warning!** No news item is found for this PR. If this is an user facing change/feature/fix, please add a news item by copying the format from `news/TEMPLATE.rst`.

Fixed

**Comment by tacaswell** [comment]
I suspect that this only a partial fix as I am also seeing:

```
/usr/lib/python3.13/site-packages/xonsh/parsers/ast.py:143: DeprecationWarning: Constant.__init__ got an unexpected keyword argument 'is_raw'. Support for arbitrary keyword arguments is deprecated and will be removed in Python 3.15.
  return Constant(value=s, kind="str", **kwargs)
/usr/lib/python3.13/site-packages/xonsh/parsers/base.py:2199: DeprecationWarning: Div.__init__ got an unexpected keyword argument 'lineno'. Support for arbitrary keyword arguments is deprecated and will be removed in Python 3.15.
  p[0] = [op(lineno=p1.lineno, col_offset=p1.lexpos), p[2]]
/usr/lib/python3.13/site-packages/xonsh/parsers/base.py:2199: DeprecationWarning: Div.__init__ got an unexpected keyword argument 'col_offset'. Support for arbitrary keyword arguments is deprecated and will be removed in Python 3.15.
  p[0] = [op(lineno=p1.lineno, col_offset=p1.lexpos), p[2]]
/usr/lib/python3.13/site-packages/xonsh/parsers/base.py:3052: DeprecationWarning: comprehension.__init__ missing 1 required positional argument: 'is_async'. This will become an error in Python 3.15.
  comp = ast.comprehension(target=targ, iter=it, ifs=[])
/usr/lib/python3.13/site-packages/xonsh/parsers/base.py:2160: DeprecationWarning: Add.__init__ got an unexpected keyword argument 'lineno'. Support for arbitrary keyword arguments is deprecated and will be removed in Python 3.15.
  op = self._term_binops[p1.value](lineno=p1.lineno, col_offset=p1.lexpos)
/usr/lib/python3.13/site-packages/xonsh/parsers/base.py:2160: DeprecationWarning: Add.__init__ got an unexpected keyword argument 'col_offset'. Support for arbitrary keyword arguments is deprecated and will be removed in Python 3.15.
  op = self._term_binops[p1.value](lineno=p1.lineno, col_offset=p1.lexpos)
/usr/lib/python3.13/site-packages/xonsh/parsers/base.py:2160: DeprecationWarning: Sub.__init__ got an unexpected keyword argument 'lineno'. Support for arbitrary keyword arguments is deprecated and will be removed in Python 3.15.
  op = self._term_binops[p1.value](lineno=p1.lineno, col_offset=p1.lexpos)
/usr/lib/python3.13/site-packages/xonsh/parsers/base.py:2160: DeprecationWarning: Sub.__init__ got an unexpected keyword argument 'col_offset'. Support for arbitrary keyword arguments is deprecated and will be removed in Python 3.15.
  op = self._term_binops[p1.value](lineno=p1.lineno, col_offset=p1.lexpos)

```

**Comment by 0xba1a** [comment]
@tacaswell The `ast.py +143` warning has been fixed by the PR - https://github.com/xonsh/xonsh/pull/5711
So, not sure why it got showed up in your testing.

I've fixed other warnings you mentioned in the previous comments.

**Comment by 0xba1a** [comment]
bump

**Review by jnoortheen — APPROVED** [review]

**Comment by jnoortheen** [comment]
Thanks @0xba1a !

**Pull request merged**
