### PR TITLE
Black

### PR DESCRIPTION
**Pull request by scopatz**
Sort of a ridiculous changeset

### CODE REVIEW

**Comment by gforsyth** [comment]
Wow.  So I guess we actually can't build our docs right now since to do so requires having both prompt_toolkit1 and prompt_toolkit2.  Although I'm confused as to why this hasn't been an issue yet

**Comment by gforsyth** [comment]
Should we globally ignore the flake E204?  It seems to really not like whitespace before a colon.

**Comment by scopatz** [comment]
I have fixed up the doc issues themselves, but there is some doctr issue I don't understand:

```
The Travis build that generated this commit is at
https://travis-ci.org/xonsh/xonsh/jobs/423014493.
The doctr command that was run is
    /home/travis/virtualenv/python3.6.3/bin/doctr deploy --deploy-repo xonsh/xonsh-docs dev
'
[__doctr_working_branch 77ff05f94] Update docs after building Travis build 7441 of xonsh/xonsh
 215 files changed, 8688 insertions(+), 7795 deletions(-)
 rewrite dev/_modules/xonsh/color_tools.html (69%)
 delete mode 100644 dev/_modules/xonsh/ptk/completer.html
 delete mode 100644 dev/_modules/xonsh/ptk/history.html
 rewrite dev/api/ptk/history.html (66%)
 rewrite dev/objects.inv (99%)
 rewrite dev/searchindex.js (79%)
Don't have permission to push. Not trying.
git checkout 6a8ae04dfecaa7dcd3e157a38d15b817c6118253
Note: checking out '6a8ae04dfecaa7dcd3e157a38d15b817c6118253'.
```

**Comment by scopatz** [comment]
Here is the link to the line: https://travis-ci.org/xonsh/xonsh/jobs/423014493#L1866

**Comment by asmeurer** [comment]
doctr doesn't push on pull request builds https://travis-ci.org/xonsh/xonsh/jobs/423014493#L1928

**Comment by scopatz** [comment]
@asmeurer - yeah but doctr is clearly failing here for some reason.  Any ideas?

**Comment by asmeurer** [comment]
I see. I'm not sure what happened there. What is the file `xonsh/hi`?

**Comment by scopatz** [comment]
Hmm I don't know, let me look!

**Comment by scopatz** [comment]
Ok! I have got doctr working with some git clean / reset

**Comment by scopatz** [comment]
It would be nice to get this in before we do too much more work on it :)

**Comment by asmeurer** [comment]
OK, I understand if you want to get this through. I opened https://github.com/drdoctr/doctr/issues/322 for the doctr issue though. It shouldn't be happening. If you can let me know where the xonsh/hi file came from it would help.

**Comment by gforsyth** [comment]
Ok, the Appveyor failure is spurious (it failed after a change made to `.travis.yml` so I'm calling bull).

This is an unreviewable changeset, but I'm reasonably trusting of `black` and I think the changes made to CI and the deprecation notices about ptk1 look good.

So... here goes...

**Comment by gforsyth** [comment]
Thanks, @scopatz !

Until we have a lambda check or something to run `black` on all incoming PRs we'll need to be vigilant about testing them locally.

**Comment by scopatz** [comment]
Thanks @gforsyth!

@asmeurer - I looked around for like an hour last night, and I couldn't find it.  I thought it was being generated by the tests, but it must be getting generated by the docs. Thanks for opening that issue.

**Comment by gforsyth** [comment]
@scopatz -- something in the amalgamation is also part of this, I think.  After a local install, a bunch of files in the repo are dirty:

```diff
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   xonsh/__init__.py
	modified:   xonsh/completers/__init__.py
	modified:   xonsh/history/__init__.py
	modified:   xonsh/prompt/__init__.py
```

and it looks like it's all `'` vs `"`

```diff
diff --git a/xonsh/__init__.py b/xonsh/__init__.py
index 48a87052..eb5b5b59 100644
--- a/xonsh/__init__.py
+++ b/xonsh/__init__.py
@@ -5,95 +5,92 @@ __version__ = "0.7.7"
 # amalgamate exclude winutils wizard pytest_plugin fs macutils pygments_cache
 # amalgamate exclude jupyter_shell
 import os as _os
-
-if _os.getenv("XONSH_DEBUG", ""):
+if _os.getenv('XONSH_DEBUG', ''):
     pass
 else:
     import sys as _sys
-
     try:
         from xonsh import __amalgam__
-
         completer = __amalgam__
-        _sys.modules["xonsh.completer"] = __amalgam__
+        _sys.modules['xonsh.completer'] = __amalgam__
         contexts = __amalgam__
-        _sys.modules["xonsh.contexts"] = __amalgam__
+        _sys.modules['xonsh.contexts'] = __amalgam__
         lazyasd = __amalgam__
-        _sys.modules["xonsh.lazyasd"] = __amalgam__
+        _sys.modules['xonsh.lazyasd'] = __amalgam__
         lazyjson = __amalgam__
-        _sys.modules["xonsh.lazyjson"] = __amalgam__
+        _sys.modules['xonsh.lazyjson'] = __amalgam__
         platform = __amalgam__
-        _sys.modules["xonsh.platform"] = __amalgam__
+        _sys.modules['xonsh.platform'] = __amalgam__
         pretty = __amalgam__
-        _sys.modules["xonsh.pretty"] = __amalgam__
+        _sys.modules['xonsh.pretty'] = __amalgam__
         codecache = __amalgam__
-        _sys.modules["xonsh.codecache"] = __amalgam__
+        _sys.modules['xonsh.codecache'] = __amalgam__
         lazyimps = __amalgam__
-        _sys.modules["xonsh.lazyimps"] = __amalgam__
+        _sys.modules['xonsh.lazyimps'] = __amalgam__
<snip>
```

**Pull request merged**
