### PR TITLE
fixed completer issue

### LINKED ISSUE #2380: cmd && othercmd throws an exception
```
➤ ls &&Exception in thread Thread-35:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 860, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/usr/lib/python3.6/site-packages/xonsh/ptk/completer.py", line 49, in get_completions
    self.ctx)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 124, in complete
    out = func(prefix, line, begidx, endidx, ctx)
  File "/usr/lib/python3.6/site-packages/xonsh/completers/__amalgam__.py", line 831, in complete_skipper
    ctx)
  File "/usr/lib/python3.6/site-packages/xonsh/__amalgam__.py", line 124, in complete
    out = func(prefix, line, begidx, endidx, ctx)
  File "/usr/lib/python3.6/site-packages/xonsh/completers/__amalgam__.py", line 1427, in complete_base
    complete_command(prefix, line, start, end, ctx))
TypeError: unsupported operand type(s) for |: 'tuple' and 'set'
```

```
➤ y -Q | egrep 'toolkit|xon'
community/python-prompt_toolkit 1.0.14-1
local/xonsh 0.5.9-1
```

Let me know if you need anything else.

### PR DESCRIPTION
**Pull request by scopatz**
This closes #2380

### CODE REVIEW

**Comment by laloch** [comment]
I can confirm that the shell does not crash any more, but hitting the <kbd>TAB</kbd> key now immediately overwrites the `||` or `&&` operator with the first completer suggestion. `$UPDATE_COMPLETIONS_ON_KEYPRESS=True`, however, works just fine, so I'd say problem solved. Thanks.

**Comment by scopatz** [comment]
Excellent! Thanks @laloch!

**Comment by scopatz** [comment]
pinging this!

**Comment by gforsyth** [comment]
Overwriting the `&&` seems like a separate problem with the completers -- still better than a traceback, so I'm merging this in.

**Pull request merged**
