### PR TITLE
Argument completion

### PR DESCRIPTION
**Pull request by scopatz**
This adds the ability for Python function argument names to be completed. This is instead of having jedi completions. See #2127 for more discussion.

### CODE REVIEW

**Comment by scopatz** [comment]
Again, I think the travis failures are not correct

**Comment by scopatz** [comment]
Updated this from master

**Comment by scopatz** [comment]
pinging this one!

**Comment by melund** [comment]
What am I doing wrong: 
image

**Comment by scopatz** [comment]
You should see `x=` and `y=` in that completions list.  If you start typing an argument name and then press tab, you should only get the arguments with the prefix you have already typed

**Comment by melund** [comment]
So it does work, but it seem to mix in other completions as well. 
image

**Comment by melund** [comment]
I guess that is intended right. The big completion list after an opening bracket is not that useful though...

**Comment by astronouth7303** [comment]
Do completions have any concept of priority?

**Comment by scopatz** [comment]
> I guess that is intended right. The big completion list after an opening bracket is not that useful though...

I agree, but it is correct since you pass in any value to a function.

> Do completions have any concept of priority?

Not yet. That is a separate issue because it would involve some change to the model, most likely.

**Comment by melund** [comment]
Ok. This all looks good to me. Nice indeed.

**Comment by scopatz** [comment]
Thanks @melund!

**Pull request merged**
