### PR TITLE
parser table fix

### LINKED ISSUE #1406: starting xonsh creates `parse_table.py` file on cwd
```
> ls
cli_test  pyte
> python3 -m xonsh
(xonsh starts)
$ ls
cli_test  parser_table.py  pyte
```
anyone can reproduce?

### PR DESCRIPTION
**Pull request by scopatz**
@laerus could you try this out to fix #1406 please?

### CODE REVIEW

**Comment by laerus** [comment]
this seems to fix the issue on this machine, unfortunately i can't get on my main machine atm. i will try and investigate more.

**Comment by laerus** [comment]
we must also debug this stalled testing on py3.4 although AppVeyor throws a `SyntaxError`

**Comment by laerus** [comment]
running tests locally through bash:

```
$ py -m coverage run --source xonsh -m py.test -q

Exception ignored in: <bound method Execer.__del__ of <xonsh.__amalgam__.Execer object at 0xb57b58ec>>
Traceback (most recent call last):
  File "/home/laerus/projects/xonsh/xonsh/__amalgam__.py", line 16144, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <generator object get_tokens at 0xb37832ac>
Traceback (most recent call last):
  File "/home/laerus/projects/xonsh/xonsh/__amalgam__.py", line 9970, in get_tokens
TypeError: catching classes that do not inherit from BaseException is not allowed


$ XONSH_DEBUG=1 py -m coverage run --source xonsh -m py.test -q

Exception ignored in: <bound method Execer.__del__ of <xonsh.execer.Execer object at 0xb568918c>>
Traceback (most recent call last):
  File "/home/laerus/projects/xonsh/xonsh/execer.py", line 47, in __del__
TypeError: 'NoneType' object is not callable

```

**Comment by scopatz** [comment]
@laerus - I have played around with this a bit locally @laerus, and I am seeing the same random issues on both master and this branch with both debug and amalgamtions.  Therefore I don't think these issue are related to the PR.  I think we should open another issue for those.  I believe it is issues with not deconstructing objects in the test suite correctly.

**Comment by laerus** [comment]
you have opened #1335 related to the test issue, i have pasted the outputs there aswell

**Comment by scopatz** [comment]
> you have opened #1335 related to the test issue, i have pasted the outputs there aswell

Great!

**Comment by scopatz** [comment]
OK! The tests pass.

**Comment by laerus** [comment]
the issue is solved in this branch, merging it!

**Pull request merged**
