### PR TITLE
New prompt end character

### LINKED ISSUE #4152: Reinventing the prompt end character for xonsh
Hi folks! 

Prerequisites:
1. While I'm watching [@scopatz streams](https://www.youtube.com/watch?v=dGTkiGvrYHg) I noticed that [xonsh looks like bash](https://youtu.be/EbX2fhfwOWc?t=832) and if we don't know that it's the xonsh we will never understand that it is xonsh. 
2. When I alternately use Bash and Xonsh I caught myself thinking that I am making an effort to figure out which shell I am currently using.
3. When I'm reading the bug reports in the issues or another code quotations the `$` character means bash as well as xonsh and I need to special effort to understand the meaning.
4. The bash-like prompt looks cozy but after a few rakes with the syntax users feel misled. The conch character will remind them that here is Python mindset.
5. We have double dollar in case of using env: `user@home ~ $ $VAR=1`. The conch character will dilute the repetition.
6. The conch character (`@`) in the prompt will complete the xonsh identity. We can remove or replace this character between user and host to more significant effect.
7. The `@` character looks both like conch and python (snake).
8. Using `$` limit the spreading the word about xonsh and growing the community because people think that it's bash.
9. By using `@` we can separate `$` for bash and `@` for xonsh.
10. The `@` character with `~` looks like "snail (snake, python) going to conch (shell)" - very very very metaphoric - `host@user ~ @`.

Overview:
```bash
# xonsh default 
user@host /path $

# bash default
user@host:/path$

# zsh has percent by default
user@host /path %  

# fish wants to look like fish
user@host /path>

# Starship cross-shell prompt (bold angle bracket)
❯

# proposed for xonsh
user@host /path @
```

**What if we replace `$` to `@` and make/replace a space between user and host in xonsh?** 

image

image

This looks like snail and conch:

image

[xontrib-prompt-bar](https://github.com/anki-code/xontrib-prompt-bar) appearance:

image

### 📄 [XEP-like description](https://github.com/xonsh/xonsh/issues/4152#issuecomment-794875983)

# 📗 VOTE HERE - https://github.com/xonsh/xonsh/issues/4152#issuecomment-794178842

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### PR DESCRIPTION
**Pull request by anki-code**
Closes #4152

Vote result - https://github.com/xonsh/xonsh/issues/4152#issuecomment-794178842

Key comments:
* https://github.com/xonsh/xonsh/issues/4152#issuecomment-794875983 - XEP-like description
* https://github.com/xonsh/xonsh/issues/4152#issue-823993141 - Prerequisites

Xonsh looks like bash and it's confusing:
* https://youtu.be/EbX2fhfwOWc?t=832
* https://github.com/xonsh/xonsh/issues/4152#issuecomment-1183368071
* https://github.com/xonsh/xonsh/issues/4152#issuecomment-1435521549

TODO:

- [x] Update prompt end character
- [x] Update index.html
- [x] Update docs

Next steps after merge:

* Update images
* Update xonsh docker container on dockerhub

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Comment by jnoortheen** [comment]
@anki-code I think it is good to have a consensus before moving with this.

**Comment by jnoortheen** [comment]
Consensus within the maintainers is atleast needed. IMHO, there are some important changes needed by Xonsh 
- less memory usage (it needs lighter but full fledged shell like nushell)
- faster startup and runtime (needs a native parser atleast cythonized/mypycified libraries)
- less flakey internals (good handling of threads/subprocesses) 
 to compete with other shells (like fish/nushell). 

As of now I don't consider it to be ready for production use (replacement for bash). Hence I don't mind it not having a separate prompt. Also I voted @ to be confusing and it can be set easily.

**Comment by jnoortheen** [comment]
@anki-code I no longer have much time to work on Xonsh things, I was working on this https://github.com/xonsh/xonsh/pull/4634 to fix the flakiness with subprocess handling. If I get enough free time, I will resume them. But feel free to start from there and the discussion https://github.com/xonsh/xonsh/discussions/4710 . 

As I mentioned tuning the parser's memory usage and ptk's memory usage, is needed to reduce the overall resource usage by Xonsh.

**Review by gforsyth — APPROVED** [review]
Thanks for putting this together @anki-code !

**Pull request merged**
