### PR TITLE
more intuitive blocking loop

### PR DESCRIPTION
**Pull request by scopatz**
CC @janschulz, This is just to keep updated with xonsh/lazyasd#3

### CODE REVIEW

**Comment by janschulz** [comment]
Isn't it easier to simply take a complete release?

**Comment by scopatz** [comment]
Yeah, I'd rather copy things over sooner than later for exactly that reason.

**Comment by melund** [comment]
@janschulz Nice simplification. When I first looked at the code it also took me a little while to grasp what this simple part of the code did.

**Comment by gforsyth** [comment]
Looks good!  Thanks, @scopatz !

**Pull request merged**
