### PR TITLE
Target color

### LINKED ISSUE #3243: "Invalid ANSI color sequence" warning on startup
`xonfig` output:
```
$ xonfig
+------------------+-----------------+
| xonsh            | 0.9.9           |
| Python           | 3.7.4           |
| PLY              | 3.11            |
| have readline    | True            |
| prompt toolkit   | 2.0.9           |
| shell type       | prompt_toolkit2 |
| pygments         | 2.4.2           |
| on posix         | True            |
| on linux         | False           |
| on darwin        | True            |
| on windows       | False           |
| on cygwin        | False           |
| on msys2         | False           |
| is superuser     | False           |
| default encoding | utf-8           |
| xonsh encoding   | utf-8           |
| encoding errors  | surrogateescape |
+------------------+-----------------+
```

Giving xonsh another try, looks like there are still `LS_COLORS` issues. Here's what I get on startup:

```
$ xonsh
/usr/local/Cellar/xonsh/0.9.9/libexec/lib/python3.7/site-packages/xonsh/__amalgam__.py:7117: RuntimeWarning: Invalid ANSI color sequence "target", using "NO_COLOR" instead.
  warnings.warn(msg, RuntimeWarning)
```

I gave my LS_COLORS values [last time this came up](https://github.com/xonsh/xonsh/issues/3034). Please let me know if I can do anything to help diagnose. Thanks.

### PR DESCRIPTION
**Pull request by scopatz**
closes #3243

### CODE REVIEW

**Comment by scopatz** [comment]
@xonsh/xore - ready for review!

**Comment by scopatz** [comment]
pinging this!

**Comment by melund** [comment]
I am not sure I understand the "target" syntax... But otherwise I think it looks good.

**Comment by scopatz** [comment]
Yeah, it is pretty silly.  `dircolors` adds a special fake color for links that highlights them as the target file would be highlighted instead of the link color.

**Pull request merged**
