### PR TITLE
Lab/py control file

### PR DESCRIPTION
**Pull request by jnoortheen**
## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Comment by gforsyth** [comment]
Thanks for putting this in @jnoortheen -- I'd like to see a test for this.
Also, in re: your news item, is it only 3.8+ syntax supported?  This seems misleading -- I can't imagine it would work if the underlying environment is 3.7

**Comment by jnoortheen** [comment]
>  is it only 3.8+ syntax supported?

xonsh parser is 3.8 only. some 3.9/3.10 syntaxes (match statement ...) will fail. I wanted to mention that.

**Comment by gforsyth** [comment]
Ahh, so to me, 3.8+ implies support for 3.9 and (soon) 3.10

**Comment by jnoortheen** [comment]
> Ahh, so to me, 3.8+ implies support for 3.9 and (soon) 3.10

I will update that part to mention just the python part. Also we can mention that it will get parsed faster than xonsh control files.

**Comment by gforsyth** [comment]
This looks good @jnoortheen -- could you also add a short note to https://github.com/xonsh/xonsh/blob/main/docs/xonshrc.rst about the new option?

**Review by gforsyth — APPROVED** [review]
Great, thanks for putting this together @jnoortheen !

**Pull request merged**
