### PR TITLE
xontribs fix

### PR DESCRIPTION
**Pull request by scopatz**
Potential fix for #1287

### CODE REVIEW

**Comment by laerus** [comment]
xontrib issue seems fixed but i'm getting this:

```
> XONSH_DEBUG=5 python3 -m xonsh
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/laerus/.local/lib/python3.5/site-packages/xonsh/__main__.py", line 2, in <module>
    main()
  File "/home/laerus/.local/lib/python3.5/site-packages/xonsh/main.py", line 245, in main
    shell.cmdloop()
  File "/home/laerus/.local/lib/python3.5/site-packages/xonsh/shell.py", line 81, in __getattr__
    return getattr(self.shell, attr)
AttributeError: 'BaseShell' object has no attribute 'cmdloop'
```

**Comment by scopatz** [comment]
Ok @laerus Thanks! Can you try it again, please?

**Comment by laerus** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/laerus/.local/lib/python3.5/site-packages/xonsh/__main__.py", line 2, in <module>
    main()
  File "/home/laerus/.local/lib/python3.5/site-packages/xonsh/main.py", line 246, in main
    shell.shell.cmdloop()
AttributeError: 'BaseShell' object has no attribute 'cmdloop'
```

**Comment by scopatz** [comment]
@laerus have you set your `$SHELL_TYPE='none'`?

**Comment by scopatz** [comment]
Or are you merging this branch with some other non-master branch? And if so, which one?

**Comment by laerus** [comment]
i just did a checkout on this branch and installed. Yes SHELL_TYPE is none but i'm not setting it myself

**Comment by laerus** [comment]
SHELL_TYPE='readline' python3 -m xonsh
with this i can get passed the error

**Comment by laerus** [comment]
uuuh this was prolly a leftover to bash but i didnt set SHELL_TYPE manually
atm xonsh is starting up fine

**Comment by scopatz** [comment]
Ahh great! @gforsyth @melund @adqm I think that this is ready for a review

**Comment by gforsyth** [comment]
Works fine on my end and startup times etc. are unchanged.  Do we want to wait until windows tests are fixed or just go with this?

**Comment by scopatz** [comment]
Well we are waiting on @VHarisop for the windows fixes, and considering we spent the last few months without windows CI I think it is OK to merge.  This is especially true since this fixes breaks on master for some people.

**Comment by gforsyth** [comment]
I'm sold.  Thanks, @scopatz !

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
