### PR TITLE
feat: add on_command_not_found event

### PR DESCRIPTION
**Pull request by bcr**
#2455 requests the addition of an `on_command_not_found` event which is in this PR.
## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Comment by bcr** [comment]
I have some issues I'm working through:

[ ] The help for the event doesn't show up until `specs` is loaded
[ ] I can't find my event in the HTML docs if I do a `make html` from the docs directory. I think I don't have something hooked up right.
[ ] A testing strategy to check that the hook fires

**Comment by jnoortheen** [comment]
@bcr you can check the `xontribs/autovox.py` or any other built-in events for implementation/testing example. The events tutorial will also be helpful.

**Comment by bcr** [comment]
In this particular case I need to have an instantiated `SubprocSpec` so I can try and `run` to make sure the event fires. I did track down a lot of other event handlers, I just didn't find a `test_specs` yet or a framework to get into the guts of `SubprocSpec`. The events model in general seems pretty straightforward.

**Comment by bcr** [comment]
To fix my first problem (help for the event), I need to move:

```python
XSH.builtins.events.doc(
    "on_command_not_found",
    """
on_command_not_found(command: list[str]) -> None

Fired if a command is not found
""",
)
```
outside of specs.py somewhere so that it's available before specs gets loaded. Not sure where the least offensive place for that is.

**Comment by gforsyth** [comment]
> Not sure where the least offensive place for that is.

Hey @bcr -- thanks for the work here!  I would suggest sticking it in either `xonsh/shell.py` or `xonsh/main.py` -- both have pre- and post- execution events so I think either is a reasonable choice.

**Comment by jnoortheen** [comment]
Also this should be available only during interactive sessions.

**Comment by bcr** [comment]
I think I've addressed the open concerns. For some reason the CI Test for Python 3.10 macOS-latest is jammed. @gforsyth @jnoortheen

**Review by gforsyth — APPROVED** [review]
Looks good!  Thanks @bcr !

**Comment by crazyminecuber** [comment]
I have not managed to get this event working correctly. Could you provide a minimal example that just prints something when you type a command that does not exist?

**Comment by bcr** [comment]
When you tried the examples in the unit tests did they work? I am afk right now, but I can provide a .xonshrc example later.

**Comment by gforsyth** [comment]
@crazyminecuber -- are you running off of `main`?  

A short example:
```
(base) gil@stravaig ~ 🐚  @events.on_command_not_found
......................... def ruhroh(cmd):
.........................     print(f"There isn't a command named {cmd}")
.........................
(base) gil@stravaig ~ 🐚 
(base) gil@stravaig ~ 🐚  notacommand
There isn't a command named ['notacommand']
xonsh: subprocess mode: command not found: notacommand
```

**Comment by crazyminecuber** [comment]
No I am on 13.3 but I now see that this was merged after that release. I just thought I had it because when I ran ``help(events.on_command_not_found)`` it did not return anything obvious indicating that the event does not exist. Thanks for the quick answer and everything is good then.

**Comment by bcr** [comment]
> I just thought I had it because when I ran `help(events.on_command_not_found)` it did not return anything obvious indicating that the event does not exist.

This is an interesting point. You can do `help(events.xyzzy)` or whatever you want, and I think you'll see the same thing. This may be a deeper philosophical discussion about the dynamic nature of events...

**Pull request merged**
