### PR TITLE
add xonda to xontribs

### PR DESCRIPTION
**Pull request by gforsyth**
I wrote `xonda` as a thin wrapper around `conda`.  Instead of the (imo) messy activate and deactivate scripts, this just uses `xonsh` `PATH` magic to change environments.  And it has tab completion!  I have no idea if it works on Windows.  @melund -- do you want to try it out?

### CODE REVIEW

**Comment by scopatz** [comment]
xool!  Should I wait on merging this in?  This is just the xontrib docs, so I think it could go in now...

**Comment by gforsyth** [comment]
I think it can go in now.  The inevitable issues can be opened up on the `xonda` repo

**Comment by scopatz** [comment]
Thanks @gforsyth!

**Comment by melund** [comment]
@gforsyth.  Cool. I will try once I can bring my laptop home again. I have to leave at work because the hinges are broken and locked in an open position :(

I think it sounds cool. I don't  have a big problem with the current activation scripts on Windows though. But the tab completion is nice. Does it also work if I use standard conda?

**Comment by gforsyth** [comment]
@melund 

> the hinges are broken and locked in an open position :(
best wishes for a speedy recovery

> Does it also work if I use standard conda?
it does now!

**Comment by scopatz** [comment]
ironically there is no conda package, double ironically pip is a conda package :)

**Comment by scopatz** [comment]
best wishes for your computer @melund!

**Pull request merged**
