### PR TITLE
The change that allows Nuitka build the xonsh binary

### LINKED ISSUE #2895: Build xonsh shell binary using Nuitka
Just wondering... did anyone ever try to build Xonsh using Nuitka?
I noticed that for some CLI applications, building it with Nuitka gives a statically linked binary with an improved start-up time as well.

I tried it as follows:
```sh
python -O -m nuitka --follow-imports ./scripts/xonsh 
```
This creates a "xonsh.bin" executable of about 28M.
I works mostly here, but doesn't give me the prompt_toolkit shell. I tried it for pyvim, where it works great.

@scopatz ?

You can close this issue. I only wanted to share the idea.

### PR DESCRIPTION
**Pull request by anki-code**
Hi!

Please read the detailed report before the PR review - https://github.com/xonsh/xonsh/issues/2895#issuecomment-743382262

Closes #2895

### CODE REVIEW

**Comment by jnoortheen** [comment]
looks cool !
I am curious to know the memory and startup time benefits. Have you run any such tests ?

**Comment by anki-code** [comment]
Hi @jnoortheen!

My main goal was to fix the error with Nuitka. I also expected the decreasing of startup time but the startup time is much longer. This is the one thing I tested. I think there is an opportunity to optimisation of the building process and increasing the speed.

You can repeat the experiment pretty simple on Ubuntu with docker:
```bash
mkdir -p /tmp/xonsh && cd /tmp/xonsh
git clone -b nuitka_fix https://github.com/anki-code/xonsh
cd xonsh
nuitka3 --python-flag=no_site --python-flag=no_warnings --standalone --follow-imports xonsh
docker run -it --rm -v $PWD/xonsh.dist:/xsh ubuntu
cd /xsh
./xonsh --timings
```

**Comment by jnoortheen** [comment]
> Hi @jnoortheen!
> 
> My main goal was to fix the error with Nuitka. I also expected the decreasing of startup time but the startup time is much longer. This is the one thing I tested. I think there is an opportunity to optimisation of the building process and increasing the speed.
> 
> You can repeat the experiment pretty simple on Ubuntu, docker and this branch:
> 
> ```shell
> # Ubuntu 20.10
> mkdir -p /tmp/xonsh && cd /tmp/xonsh
> git clone -b nuitka_fix https://github.com/anki-code/xonsh
> cd xonsh
> nuitka3 --python-flag=no_site --python-flag=no_warnings --standalone --follow-imports xonsh
> 
> cd xonsh.dist
> ./xonsh --timings
> 
> # OR to test in clean environment:
> docker run -it --rm -v $PWD/xonsh.dist:/xsh ubuntu
> cd /xsh
> ./xonsh --timings
> ```

Thanks for posting. I also wanted to try compiling this with nuitka and cython/mypyc

Sometimes it happens with the startup time. We would just need to compile few modules that are critical and need to be fast.

**Comment by gforsyth** [comment]
Hey @anki-code -- thanks for putting this in.  Have you tested whether this has any impact on startup time?

**Comment by anki-code** [comment]
I see no impact. 

The way to test is simple:
```python
# bash
pip install -U git+https://github.com/anki-code/xonsh@nuitka_fix
xonsh --timings  # repeat more than 3 times
```

**Review by gforsyth — APPROVED** [review]

**Pull request merged**
