### PR TITLE
feat: Added expanding callable environment variables in subprocess mode.

### LINKED ISSUE #4167: Expand callable environment variable in subprocess mode
Hi! Think that's nice:

```python
$DATE = lambda: $(date --iso).strip()
echo The date is $DATE
```
Current output:
```
The date is <function <lambda> at 0x7f807ecda940>
```
Suggested output:
```
The date is 2021-03-11
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### PR DESCRIPTION
**Pull request by anki-code**
Closed #4167

### CODE REVIEW

**Comment by anki-code** [comment]
The meaningful changes here - https://github.com/xonsh/xonsh/pull/4168/files#diff-dc6388ab2415b7a836976e59822abb75c28f9c81b9a0308fef6d9eef51249c13R2338-R2355
Other changes is tests + black. Sorry.

**Comment by anki-code** [comment]
I want to do this optional. Please give me some time.

**Comment by anki-code** [comment]
@gforsyth I've made this feature optional and by default add the raising the exception to avoid getting `<function lambda>` string as an argument. This is more stable logic I suppose.

Example:
```python
$ENV = lambda: 123
echo $ENV
# Exception: The ENV variable is callable. If you want to use callables set $XONSH_ENV_ALLOW_CALLABLE = True

$XONSH_ENV_ALLOW_CALLABLE = True
echo $ENV
# 123
```

**Comment by jnoortheen** [comment]
any reason for raising exception if callable is assigned to a $variable?

**Comment by anki-code** [comment]
> any reason for raising exception if callable is assigned to a $variable?

The reason is to avoid unexpected getting `<function __main__.<lambda>>` string argument.

For example you have
```python
echo "$key=123"
# $key=123
```
after time you're doing import:
```python
from somelib import *  # this has `key` function
```
As result you'll have unexpected result without any error:
```python
echo "$key=123"
# <function <lambda> at 0x7f72713500d0>=123
```
In case of exception you will go and replace it to `@("$key=123")` explicitly and make your code more stable.

I suppose that there is many places in xonsh where callables converts to the text without appropriate logic and you can catch unexpected result. This case is one of this.

**Comment by anki-code** [comment]
Once again:

> any reason for raising exception if callable is assigned to a $variable?

The reason is to avoid unexpected getting `<function __main__.<lambda>>` string argument.

I suppose that there is many places in xonsh (essentially around environment) where callables were converted to the text without appropriate logic and you can catch unexpected result. This case is one of this.

If you do
```python
$VAR = 'Review'
echo "$VAR is good"
# Review is good
```
Then $VAR becomes callable you'll get without any error:
```python
echo "$VAR is good"
# <function __main__.<lambda>> is good
```
In case of exception you will go and fix the error.

**Comment by jnoortheen** [comment]
but what If I expected callable ? in cases like $PROMPT,$RIGHT_PROMPT I expect to see a callable. Then one manipulates it right ?

**Comment by anki-code** [comment]
The PROMPT variable traditionally has the string. When you replace it to the callable and then use it to ASYNC_PROMPT it's a question of design of achievething the goal. Probably the better way is to put `{async_prompt}` string into the PROMPT and call `async_prompt` from PROMPT_FIELDS on other place.

Back to this PR. I think you have no `echo $PROMPT` cases to catch the exception.

**Comment by anki-code** [comment]
I lost motivation while thinking about this logic. Sorry.

It's not good to have callables that can uncontrolled be converted to strings. This is another one question that should be redisigned, reinvented, rethought. Some day...

**Comment by anki-code** [comment]
Basically I see three different approaches:
1. **Transparent way**. If any object is callable and we expect another type (str, list, class) we should call it to get the actual value.
    * Pros: transparent, expected, extensible
    * Cons: The moment of executing the callable may be uncontrolled and for example if the callable depends on time we can get unexpected result when callable was executed in the past but we expect that it executes now. 
2. **The wall way**. If any object is callable and we expect another type (str, list, class) we should raise an exception to force explicit implementing the call from the developer i.e. replace `echo $VAR` to `echo @($VAR())`.
    * Pros: explicit calling
    * Cons: we should do the check in every plase where we could have callable (everywhere)
3. **Deprecation**. If someone try to set callable to env var raise an exception.
    * Pros: clean logic that told that variable can have only static value
    * Cons: no callable variables in the env, someone go to cry

**Comment by jnoortheen** [comment]
IMO 1 is the way to go. Python zen has proved to be better than Ruby philosophy (of lots of magik).

**Pull request closed without merging**
