### PR TITLE
#1233 using readline if prompt-toolkit is outdated

### PR DESCRIPTION
**Pull request by lucasicf**

### CODE REVIEW

**Comment by scopatz** [comment]
This looks good to me @lucasicf! Can you please add a news entry about this.  See the docs here: https://github.com/xonsh/xonsh/blob/master/CONTRIBUTING.rst#changelog

**Comment by lucasicf** [comment]
@scopatz done! check it out please. I also rebased the branch and fixed very minor conflicts.

**Comment by melund** [comment]
@lucasicf Did you forget to push? I can't see the new commits.

**Comment by melund** [comment]
If it was just a ping for a review of the old files, then do you mind to rebase and push again. That should trigger AppVeyor CI tests on Windows.

**Comment by lucasicf** [comment]
@melund let me try to open a new pull request

**Pull request closed without merging**
