### PR TITLE
[Do NOT Merge] make unthreadable as default

### PR DESCRIPTION
**Pull request by mitnk**
see #2361 cc @scopatz

### CODE REVIEW

**Comment by laerus** [comment]
maybe we need this as a temporary solution

**Comment by gforsyth** [comment]
I'm strongly against merging this in. It would break several existing bits
of functionality in exchange for warding off occasional times when we have
to intercede and add things to threadable predictors.

**Comment by adqm** [comment]
I would argue that the threadable predictors is not a real solution to begin with.

Beginners (or people who just want a simple shell they can do list comprehensions in) don't have a shell that works as they expect with xonsh.  That's a problem.  Basic functionality is broken.

I would rather have something that requires the folks who want the fancy feature at the expense of some basic functionality to have to set an option to turn it on, rather than the opposite (currently, beginners who just want a functioning shell potentially have to turn something off (_potentially for each program!_) to make it work).  And there's no error message or warning that suggests that this is the case; xonsh just feels broken to them (hence the bug reports).

To me, it totally makes sense to have the defaults be something that doesn't break job control, and to have the the threaded stuff be something that can be switched on selectively by those who want it.

Then again, this is, in many ways, the same old disagreement...

**Comment by mitnk** [comment]
At least `!()` syntax is broken by making unthreadable as default, so this PR won't be merged.

**Comment by gforsyth** [comment]
@adqm -- if it doesn't also break `!()` and the only 'breakage' is the loss of stdout storing then I don't have a problem with this sort of change. 

And I agree that continuously adding things to `threadable_predictors` is untenable -- although there is some merged code somewhere that helps predict which programs need it.

**Comment by gforsyth** [comment]
Ha, that "merged code", of course, being the code being removed in this pull request... always good to check those things first...

**Pull request closed without merging**
