### PR TITLE
Use github3.py to do github release in release.xsh

### PR DESCRIPTION
**Pull request by gforsyth**
Should close out #1793 

No unit tests (:tada:) but I have tried it out on a test repo and it seems to work. We'll know if it's borked when we do the next release.

### CODE REVIEW

**Comment by astronouth7303** [comment]
There appears to be a lot of random other changes? Some of which I thought I saw already.

**Comment by gforsyth** [comment]
Urgh. Bad rebase. I'll fix it

**Comment by gforsyth** [comment]
Ok. Rebased. Test failures are due to the sphinx bug that should be handled by #2391

**Comment by laerus** [comment]
hey @gforsyth can you merge master?

**Comment by gforsyth** [comment]
Hey @laerus -- rebased against master and tests seem to pass now.

**Pull request merged**
