### PR TITLE
Always load rc files except --no-rc is passed

### PR DESCRIPTION
**Pull request by cosineFish**
This change fixes issue #4855.

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Comment by bestlem** [comment]
As a check how does this change the tests ankicode showed in this comment

**Comment by cosineFish** [comment]
> As a check how does this change the tests ankicode showed in this comment [#4096 (comment)](https://github.com/xonsh/xonsh/issues/4096#issuecomment-791991841)
> 
> I don't know enough to set up xonsh from github in docker

Hi @bestlem ,
I run the tests ankicode showed without using docker. And changing the files under /etc needs root permission so let's ignore it for now.
```
# Prepare env: get xonsh built from this change by this command:
#    pip install -e .
# Prepare testing
$ cat prepare.sh
echo 'print("Hello from ~/.xonshrc")' > ~/.xonshrc

mkdir -p ~/.config/xonsh
export XDG_CONFIG_HOME='~/.config'
echo 'print("Hello from ~/.config/xonsh/rc.xsh")' > ~/.config/xonsh/rc.xsh

echo 'print("Hello from ~/custom_rc")' > ~/custom_rc
echo 'print("Hello from script.xsh")' > ~/script.xsh
$ bash prepare.sh
# Run tests. The outputs can be found in the comments after the xonsh command.
$ cat test_change.sh
xonsh ~/script.xsh
# Hello from ~/.config/xonsh/rc.xsh
# Hello from ~/.xonshrc
# Hello from script.xsh

xonsh -i ~/script.xsh
# Hello from ~/.config/xonsh/rc.xsh
# Hello from ~/.xonshrc
# Hello from script.xsh

xonsh --no-rc ~/script.xsh
# Hello from script.xsh

xonsh --no-rc -i ~/script.xsh
# Hello from script.xsh

xonsh --rc ~/custom_rc -- ~/script.xsh
# Hello from ~/custom_rc
# Hello from script.xsh

xonsh -i --rc ~/custom_rc -- ~/script.xsh
# Hello from ~/custom_rc
# Hello from script.xsh

xonsh -i --rc ~/custom_rc --no-rc -- ~/script.xsh
# Hello from script.xsh

$ bash -x test_change.sh
```

**Comment by cosineFish** [comment]
Run the commands that this [comment](https://github.com/xonsh/xonsh/issues/4855#issue-1286226341) in #4855 showed with this change:
```
unset XDG_CONFIG_HOME
echo  aliases[\'hw\'] = \'echo \"Hello, World\"\' > ~/.xonshrc

xonsh -c "hw"
# Hello, World

xonsh -c "xonfig"
# | RC file 1        | /home/username/.xonshrc |

xonsh --rc ~/.xonshrc -c "xonfig"
# | RC file 1        | /home/username/.xonshrc |
```

**Comment by bestlem** [comment]
Those test look good to be 
except should xonsh be reading both  ~/.config/xonsh/rc.xsh and  ~/.xonshrc - The usual app behaviour I think is to only read the one in home (~/.xonshrc) if the xdg path is not there.

Other issue is to note that the xonsh ~/script.xsh is a breaking change - I think it is the correct outcome but it does chnage the current behaviour.

**Comment by cosineFish** [comment]
pre commit is failed in flake but these files are not related with this change:
image

**Comment by bestlem** [comment]
Now #5118 has been merged and things like tools.py got patched does this now pass all the tests.

Can it be pushed again?

**Comment by bestlem** [comment]
Is there a way of providing a test suite for this rather than manual tests?

**Comment by CYuxian** [comment]
> Is there a way of providing a test suite for this rather than manual tests?

Tests are added. Please help to check again, thanks!

**Comment by cosineFish** [comment]
> Is there a way of providing a test suite for this rather than manual tests?

@bestlem The tests have been added. Please help to review, thanks!

**Review by gforsyth — APPROVED** [review]
This looks good to me, @cosineFish !  Thanks for your patience and thanks @bestlem for helping to shepherd this!

**Pull request merged**
