### PR TITLE
Fix admonitions in docs

### PR DESCRIPTION
**Pull request by melund**
No news file necessary. 

This fixes a docs problem rendering admonitions with sphinx 2. 

image

It adds the following setting: 

        "inline_admonitions": True,

No idea why this wasn't a problem with sphinx 1

### CODE REVIEW

**Comment by gforsyth** [comment]
Hey @melund -- thanks for putting this in!  These CI failures are wacky -- I'm not sure exactly what's going on...

**Comment by melund** [comment]
Yes. They are weird. One of them is a "black" error on file I didn't touch. But I will try to fix it anyway.

**Comment by melund** [comment]
@gforsyth I merged from master and now it is much better :)

**Comment by scopatz** [comment]
Thanks @melund!

**Pull request merged**
