### PR TITLE
Allow unthreadable subprocs to be captured.

### PR DESCRIPTION
**Pull request by scopatz**
This should address #2165. I would appreciate it if folks could bang on this for a bit. I don't think it breaks anything else, but I have only done preliminary tests. I am not sure if it will work when the output is larger than the buffer size.

### CODE REVIEW

**Comment by scopatz** [comment]
Also, I should mention that the basic idea here is that just because something is unthreadable (and can't be teed to Python), doesn't mean that we can't capture the output if we are willing to wait. Since this is exactly what `$(cmd)` is supposed to do (ie wait and capture all output), the threadability shouldn't matter. Mea culpa.

**Comment by mitnk** [comment]
@scopatz 
OT here - I'm currently struggling with job control stuff. Could you provide some (short is ok) information why `threadable/unthreadable/ThreadPopen` was introduced (instead use Popen directly)? Thanks :)

**Comment by scopatz** [comment]
@mitnk - Basically, it is because Popen will block the thread it is on if you read from the pipes that you send to it. In certain situations, such as `![]` and `!()`,  we want to be able to tee stdout and stderr into an in-memory buffer and print it out and remain fully interactive. You basically can't get all of that on a single thread normally.  You either need to use multiple threads (what we do) or use an event loop, like asyncio provides.

**Comment by scopatz** [comment]
Ok the circle tests seems to pass now, but don't merge yet because I have noticed some bugs locally.

**Comment by scopatz** [comment]
Alright I took care of the local bug. If this passes CI, it is ready for review.

**Comment by melund** [comment]
The test fails. It seems it is because 'echo' on windows return a '\r\n' to the when it is captured. 

```
   def test_import():
        import sample
>       assert ('hello mom jawaka\n' == sample.x)
E       assert 'hello mom jawaka\n' == 'hello mom jawaka\r\n'
E           hello mom jawaka
```

It is weird because on don't see the same behaviour on my computer. 
```
snail@sea ~\Documents\xonsh capunthread $ x = $(echo hello)
snail@sea ~\Documents\xonsh capunthread $ x
'hello\n'
```

**Comment by melund** [comment]
Ahh.. Echo is aliased to a print statement in the test files: 
https://github.com/xonsh/xonsh/blob/master/tests/xpack/sample.xsh#L2
```
aliases['echo'] = lambda args, stdin=None: print(' '.join(args))
```

**Comment by melund** [comment]
There seem to be a universal newline issue here. 

If I capture a normal echo command it get a universal newline:
snail@sea ~\Documents\xonsh capunthread $ x = $(echo hello)
snail@sea ~\Documents\xonsh capunthread $ x
'hello\n'
```
But if I capture the ouptut of a aliased print statement then I don't get universal newlines:
```
snail@sea ~\Documents\xonsh capunthread $ aliases['echo'] = lambda args, stdin=
......................................... None: print(' '.join(args))
snail@sea ~\Documents\xonsh capunthread $ x = $(echo hello)
snail@sea ~\Documents\xonsh capunthread $ x
'hello\r\n'
```

**Comment by scopatz** [comment]
Added `universal_newlines` fix. Let's hope it works!

**Comment by scopatz** [comment]
Ok, that seemed to fix the windows issues.

**Comment by melund** [comment]
Great.

**Comment by scopatz** [comment]
Thanks @melund!

**Pull request merged**
