### PR TITLE
safe flush

### PR DESCRIPTION
**Pull request by scopatz**
Should address #1965

### CODE REVIEW

**Comment by scopatz** [comment]
Also, I don't think this needs a news entry

**Comment by mitnk** [comment]
I think this change is not enough - the error will move to h.write(s) :)

**Comment by scopatz** [comment]
Can you post the new traceback please?

**Comment by mitnk** [comment]
```
$ history show all | head
...
$ Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/proc.py", line 1286, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/proc.py", line 1126, in proxy_two
    return f(args, stdin)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/history.py", line 767, in history_main
    _HIST_MAIN_ACTIONS[ns.action](ns, hist)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/history.py", line 463, in _hist_show
    print(c)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/proc.py", line 1013, in write
    r = h.write(s)
OSError: [Errno 9] Bad file descriptor
```

**Comment by mitnk** [comment]
It's not raising errors your side?

**Comment by scopatz** [comment]
I can't seem to trigger the write() error... But I think I have figured out what was wrong anyway.  The fix was a little more involved.  Would you mind trying it again, please?

**Comment by mitnk** [comment]
Yes, it fixed the issue. Thanks a lot!

**Comment by melund** [comment]
Lgtm

**Pull request merged**
