### PR TITLE
fix signal hook issue

### PR DESCRIPTION
**Pull request by mitnk**
An addition fix for #1954, fixes issue like following:

```
$ Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/xonsh", line 3, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/main.py", line 221, in main
    shell.shell.cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/readline_shell.py", line 399, in cmdloop
    self._cmdloop(intro=intro)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/readline_shell.py", line 359, in _cmdloop
    line = self.singleline()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/readline_shell.py", line 249, in singleline
    rtn = input(self.prompt)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/proc.py", line 733, in _signal_winch
    self.proc.send_signal(signal.SIGWINCH)
AttributeError: 'NoneType' object has no attribute 'send_signal'
```

no news item needed.

### CODE REVIEW

**Comment by mitnk** [comment]
Found another issue, which should be fixed in the above commit:
```
$ Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/xonsh", line 3, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/main.py", line 221, in main
    shell.shell.cmdloop()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/readline_shell.py", line 399, in cmdloop
    self._cmdloop(intro=intro)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/readline_shell.py", line 359, in _cmdloop
    line = self.singleline()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/readline_shell.py", line 249, in singleline
    rtn = input(self.prompt)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/proc.py", line 758, in _signal_int
    self.send_signal(signum)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/xonsh/proc.py", line 878, in send_signal
    while self.proc is None and dt < self.timeout:
AttributeError: 'PopenThread' object has no attribute 'timeout'
```

**Comment by scopatz** [comment]
This looks great, @mitnk! Thanks so much. Trying to figure out what is wrong with circle now...

**Comment by laerus** [comment]
one of my latest tests, i think this has to do with vc_timetout, not sure though

**Comment by scopatz** [comment]
@mitnk, can you update from master please to get the test fix?

**Comment by mitnk** [comment]
updated, circle passed :)

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
