### PR TITLE
Revert "Fix for alias resolution in threadable predition"

### PR DESCRIPTION
**Pull request by gforsyth**
Reverts xonsh/xonsh#2191

Putting this in as a place to continue discussion started by @mitnk in #2198 #2202 and elsewhere.

It does solve #2198 for me.

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks for putting this in @gforsyth. I think that this restores the other bug with resolving aliases. I'll look into the underlying cause of the bug this weekend, because I think the code on master right now is correct.

**Comment by mitnk** [comment]
Thanks @gforsyth for open this discussion.

> underlying cause of the bug .. I think the code on master right now is correct.

@scopatz I agree on the "reverting solution" is a temporary/not-ideal one. We need to make `Popen` and `PopenThread` both to work for same programs (i.e. fix the underlying issues).

> I think the code on master right now is correct.

Agreed. But a bit of small issues here in `threadable_predictors`, we defined `xonsh`, `xo` etc in the `predictors` mapping which would never be matched because or of them are `#!/usr/bin/python` and will use `python`s predictor. For other script-ed program too (e.g. I have a tool named `psj`, which is a bash script with `#! /bin/bash`, it will go through `bash`'s predictor).

**Comment by scopatz** [comment]
See #2211

**Comment by mitnk** [comment]
replaced by #2211, thanks again @gforsyth!

**Pull request closed without merging**
