### PR TITLE
Redirection no longer require a space

### PR DESCRIPTION
**Pull request by scopatz**
This expands the capability for redirections to not require a space. This should address the remaining issue in #1628

### CODE REVIEW

**Comment by laerus** [comment]
so something like `echo ok err>out` will redirect stderr to stdout or stderr to a filename 'out'? what if i want to redirect to a filename 'err' or the filename '1' will these be special cases?

**Comment by scopatz** [comment]
Hi @laerus, so in ambiguous cases, the redirection token always wins (because it is tokenized first). Thus `err>out` will redirect to standard out. It will not create a file called out. I should note that I don't think that we should advertise this too strong because of these ambiguous cases. I put this in only so that programs like vim and emacs would be able to use xonsh without too much extra effort.  It inches us towards more sh-lang comparability, just so that we can interoperate with other tools.

**Comment by melund** [comment]
This looks fine to me. You are really killing issues these days @scopatz

**Comment by scopatz** [comment]
Ummhmm! I want to polish everything up and step one is to fix all of the bugs. Thanks for the reviews!

**Pull request merged**
