### PR TITLE
Amalgamate completers

### PR DESCRIPTION
**Pull request by scopatz**
This PR amalgamates the completer subpackage.  It does not attempt to make the completers lazy, I'll leave that for another PR.

However, this does add the feature of warning if an amalgamated name is defined across multiple different modules in the amalgamated package.  This exposed a handful of bugs that have since been fixed.

### CODE REVIEW

**Comment by gforsyth** [comment]
> This exposed a handful of bugs that have since been fixed.

Do you want to add a mention of these to the news entry?

**Comment by scopatz** [comment]
done!

**Comment by scopatz** [comment]
Woohoo! The tests finally pass.

**Comment by gforsyth** [comment]
Hey @scopatz -- this is doing something weird to xontrib completion files.  Gimme a sec to investigate

**Comment by gforsyth** [comment]
Ok, on current master, the way I add completers in xontribs is to end the xsh file with

```console
#add to list of completers
__xonsh_completers__['pacman'] = pacman_completer
#bump to top of list (otherwise bash completion interferes)
__xonsh_completers__.move_to_end('pacman', last=False)
```

but on this branch, leads to:

```console
/home/gil/git/xonsh/xonsh/environ.py:1432: RuntimeWarning: error running xonsh run control file '/home/gil/.xonshrc': module 'builtins' has no attribute '__xonsh_shell__'
  warnings.warn(msg.format(rcfile, err), RuntimeWarning)
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/home/gil/git/xonsh/xonsh/proc.py", line 341, in wrapped_simple_command
    r = f(args, i)
  File "/home/gil/git/xonsh/xonsh/xontribs.py", line 145, in xontribs_main
    return _MAIN_XONTRIB_ACTIONS[ns.action](ns)
  File "/home/gil/git/xonsh/xonsh/xontribs.py", line 67, in _load
    update_context(name, ctx=ctx)
  File "/home/gil/git/xonsh/xonsh/xontribs.py", line 49, in update_context
    modctx = xontrib_context(name)
  File "/home/gil/git/xonsh/xonsh/xontribs.py", line 38, in xontrib_context
    m = importlib.import_module(spec.name)
  File "/home/gil/anaconda/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/gil/anaconda/lib/python3.5/site-packages/pacman_tabcomplete-0.1-py3.5.egg/xontrib/pacman_tabcomplete.xsh", line 19, in <module>
    __xonsh_completers__['pacman'] = pacman_completer
NameError: name '__xonsh_completers__' is not defined
```

**Comment by gforsyth** [comment]
To clarify, this is only a problem when the `xontrib load` line is in my `xonshrc`

**Comment by scopatz** [comment]
OK @gforsyth, can you try it now, please?

**Comment by gforsyth** [comment]
```python
gil@theo ~ $ xonsh
/home/gil/git/xonsh/xonsh/__amalgam__.py:11574: RuntimeWarning: error running xonsh run control file '/home/gil/.xonshrc': module 'builtins' has no attribute '__xonsh_shell__'
  warnings.warn(msg.format(rcfile, err), RuntimeWarning)
```

worth noting that it still _works_, just throwing this error.  

On a side note, does `python setup.py install` no longer actually install things in the `site-packages` dir?

**Comment by scopatz** [comment]
> worth noting that it still works, just throwing this error.

I don't think this is working then.  What does your `xonshrc` look like?

> On a side note, does python setup.py install no longer actually install things in the site-packages dir?

This is definitely strange. `./setup.py install --user` installs into site-packages for me.

**Comment by gforsyth** [comment]
It is working... just not sure why.  
My `xonshrc` is only `xontrib load xonda` (where the xonda.xsh lives [here](https://github.com/gforsyth/xonda/blob/master/xontrib/xonda.xsh)).

But, `completer list` lists `xonda` among the completers and is providing the features it's supposed to.


the `--user` flag works for me, but I want it installed into my anaconda install.  after `python setup.py install`, the `anaconda/bin/xonsh` script is written as 

```
#!/home/gil/anaconda/bin/python -u
# EASY-INSTALL-DEV-SCRIPT: 'xonsh==0.4.3','xonsh'
__requires__ = 'xonsh==0.4.3'
__import__('pkg_resources').require('xonsh==0.4.3')
__file__ = '/home/gil/git/xonsh/scripts/xonsh'
exec(compile(open(__file__).read(), __file__, 'exec'))
```

**Comment by gforsyth** [comment]
ok, just disregard my install for now.  something is totally screwy somewhere and I'm about 3 minutes away from nuking everything

**Comment by gforsyth** [comment]
Ok, so my work computer is totally screwed, weird stuff with `sys.path` going on, but that's neither here nor there.  

I get this error still on this branch if my `xonshrc` contains `xontrib load xonda`

```console
gil@bad_cat ~ $ xonsh
/home/gil/miniconda3/lib/python3.5/site-packages/xonsh/__amalgam__.py:11574: RuntimeWarning: error running xonsh run control file '/home/gil/.xonshrc': module 'builtins' has no attribute '__xonsh_shell__'
  warnings.warn(msg.format(rcfile, err), RuntimeWarning)
```

but the `xonda` completer is listed under `completer list` and those completions work.  

The error is a littel strange to me, since there is no call to `__xonsh_shell__` explicitly in the xonda completer.  just `__xonsh_env__` and `__xonsh_completers__`

**Comment by scopatz** [comment]
@gforsyth - if I add `xontrib load xonda` to my xonshrc, I do not see this warning. Nor do I see this warning if I load any other xontrib from the xonshrc. 

I have added some better error reporting for errors in xonshrc files, now though.

**Comment by gforsyth** [comment]
Ahh, well, this is informative at least.  Now when I run I get this error on start:

```console
/home/gil/anaconda/lib/python3.5/site-packages/xonsh/__amalgam__.py:11577: RuntimeWarning: Traceback (most recent call last):
  File "/home/gil/anaconda/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 11565, in xonshrc_context
    run_script_with_cache(rcfile, execer, env)
  File "/home/gil/anaconda/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 2018, in run_script_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/home/gil/anaconda/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 1938, in run_compiled_code
    func(code, glb, loc)
  File "/home/gil/.xonshrc", line 86, in <module>
    xontrib load xonda
  File "/home/gil/anaconda/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 15959, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/home/gil/anaconda/lib/python3.5/site-packages/xonsh/__amalgam__.py", line 15849, in run_subproc
    pause_call_resume(prev_proc, builtins.__xonsh_shell__.settitle)
AttributeError: module 'builtins' has no attribute '__xonsh_shell__'

error running xonsh run control file '/home/gil/.xonshrc': module 'builtins' has no attribute '__xonsh_shell__'
  warnings.warn(msg.format(exc, rcfile, err), RuntimeWarning)
```

So the error is actually in `settitle`?

**Comment by gforsyth** [comment]
Ok, so I have _no_ idea why this should be, but if I comment out the `settitle` in `built_ins.py` then this starts up without a hitch.

**Comment by scopatz** [comment]
I have put in a hasattr check which should cover this.

**Comment by gforsyth** [comment]
Woohoo!  It works!

**Comment by scopatz** [comment]
Great!

**Comment by gforsyth** [comment]
Ok, I think this is good to go.  Merging in.

**Comment by gforsyth** [comment]
Thanks, @scopatz !  Sorry for the extra pain.

**Comment by scopatz** [comment]
No problem!  Happy to get it working!

**Pull request merged**
