### PR TITLE
repr/str for lazyobject

### LINKED ISSUE #1392: default value for $PATH seems strange in wizard
It's  `<xonsh.__amalgam__.LazyObject object at 0x7f6705929eb8>`. Current value is okay though.

I run fresh xonsh 0.4.3 on Ubuntu 16.04.

### PR DESCRIPTION
**Pull request by laerus**
fixes #1392

### CODE REVIEW

**Comment by gforsyth** [comment]
Thanks, @laerus!

**Comment by scopatz** [comment]
For future reference it is easier to make changes to amalgamate and lazyasd in their own repos and then simply copy the files over here.

1. https://github.com/xonsh/lazyasd
2. https://github.com/xonsh/amalgamate

Thanks a ton @laerus!

**Comment by laerus** [comment]
Copy how?

**Comment by scopatz** [comment]
I do `cp ~/lazyasd/lazyasd.py ~/xonsh/xonsh/lazyasd.py`

**Comment by laerus** [comment]
and you create two different PRs?

**Comment by scopatz** [comment]
yeah, two different prs. presumably the first pr to the lazyasd repo would also contain some tests too, which is part of the motivation for doing it that way

**Comment by laerus** [comment]
allrighty, thanks for the info!!

**Pull request merged**
