### PR TITLE
feat: Added environment variable to hide unwanted printing the stderr when using captured object.

### LINKED ISSUE #4021: Captured object shows unwanted stderr
Hi! 
Captured object shows unwanted stderr i.e. before object repr:

```python
cd /tmp
echo @("""
import sys
print('out', file=sys.stdout)
print('err', file=sys.stderr)
""") > ttt.py

r=!(python ttt.py)  # No stdout, no stderr - good

!(python ttt.py)  # stderr before object repr - bad
# err                          
# CommandPipeline(
#   stdin=<_io.BytesIO object at 0x7f4c48b3c900>,
#   stdout=<_io.BytesIO object at 0x7f4c48b3cdb0>,
#   stderr=<_io.BytesIO object at 0x7f4c48b3c680>,
#   pid=6314,
#   returncode=0,
#   args=['python', 'ttt.py'],
#   alias=None,
#   stdin_redirect=['<stdin>', 'r'],
#   stdout_redirect=[10, 'wb'],
#   stderr_redirect=[12, 'w'],
#   timestamps=[1608146243.7313583, 1608146243.761544],
#   executed_cmd=['python', 'ttt.py'],
#   input='',
#   output='out\n',
#   errors='err\n'
# )

# Prepared by xontrib-hist-format
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### PR DESCRIPTION
**Pull request by anki-code**
Closes #4021
Related #4220

Added XONSH_SUBPROC_CAPTURED_PRINT_STDERR environment variable to hide unwanted printing the stderr when using captured object.

Example:
```python
def _test_stream(args, stdin, stdout, stderr):
    print('hallo on err', file=stderr)
    print('hallo on out', file=stdout)
    return 1

aliases['test-stream'] = _test_stream

x = !(test-stream)
print(x.returncode)
# hallo on err
# 1

# Added:
with __xonsh__.env.swap(XONSH_SUBPROC_CAPTURED_PRINT_STDERR=False):
    x = !(test-stream)
    print(x.returncode)
# 1
```

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

### CODE REVIEW

**Comment by anki-code** [comment]
And the question: what if we set this to False? Personally I'm waiting no any output when use captured object.

**Comment by daniel-shimon** [comment]
Yeah I agree. Capture stderr without printing by default.

**Review by gforsyth — APPROVED** [review]
Thanks @anki-code !

**Comment by anki-code** [comment]
> And the question: what if we set this to False by default? Personally I'm waiting no any output when I'm using captured object.

@gforsyth what do you think about that?

**Comment by gforsyth** [comment]
> @gforsyth Thank you for merge! What do you think about the question?

Fine by me if we set it to False by default

**Pull request merged**
