### PR TITLE
Add github module based on the hub binary

### PR DESCRIPTION
**Pull request by tonybaloney**
This pull request introduces a new prompt module `prompt.github`, which provides a function `github_prompt` which will 
be embedded into the prompt method dictionary.

Timeout is specified in `XONSH_GITHUB_TIMEOUT`

Usage requires hub to be installed via `brew install hub` or github.com/github/hub.

Once configured, it will provide a build circle at the end of the user prompt. Similar to git and vc prompt extensions, it is optional.

/CC @scopatz

### CODE REVIEW

**Comment by astronouth7303** [comment]
Please move this to a xontrib. There is no reason for this to be core or to be part of the main xonsh project.

For a template to get started with, see the [xontrib cookie cutter](https://github.com/laerus/cookiecutter-xontrib).

**Comment by tonybaloney** [comment]
@astronouth7303 will do. It looked similar to the vc and Git modules, I'll build a xontrib

**Comment by astronouth7303** [comment]
It's arguable that VCS support should also be a xontrib, too.

**Comment by scopatz** [comment]
Thanks @tonybaloney! I look forward to seeing the xontrib

**Pull request closed without merging**
