### PR TITLE
Prevent main proc from stopping

### LINKED ISSUE #2196: git commit stuck on Mac
When type `git commit` without an `-m` will got xonsh stuck on Mac OS. It doesn't happen on Linux. (I'd say Linux is too kind for devs :))

Xonsh stuck is because the xonsh process has hand off the controlling terminal to git process, but it still want write something to stdout/stderr. Thus it got a SIGTTOU and stopped by OS.

```
USER   PID  PPID  PGID TPGID STAT COMMAND
hugo 23584 23583 23583 23601 T    Python -u xonsh
hugo 23601 23584 23601 23601 S+   git commit
hugo 23602 23601 23601 23601 S+   vim COMMIT_EDITMSG
```

This is a new issue introduced by #2177, my bad. Fix is on the way.

### PR DESCRIPTION
**Pull request by mitnk**
Try fixes #2196. The current committed code actually fixed the stuck issue, but, obviously, is not the correct way.

The correct way I think should be 1) "not read from stdin or write to stdout/stderr when hand out the terminal" and/or 2) "do not settcattr when should not".

### CODE REVIEW

**Comment by scopatz** [comment]
Is this still a work in progress? I think that #2196 should block the weekly release for the moment, since we can't break git. FWIW, I tried this branch out and it seems to work well on Linux

**Comment by scopatz** [comment]
Also thanks for putting in the fix!

**Comment by mitnk** [comment]
Hi @scopatz, with the last commit added, I think we can merge it into master. This partly fix the `git commit` stucking issue on mac. We can do further clean up in later PRs.

**Comment by mitnk** [comment]
no news item needed, since this is a new issue after 0.5.4.

**Comment by scopatz** [comment]
Is the windows if-statement not needed?

**Comment by mitnk** [comment]
It is needed, SIGTTIN are POSIX things.

**Comment by scopatz** [comment]
Oh whoops I was looking at the wrong diff :)

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
