### PR TITLE
Lazy completers

### PR DESCRIPTION
**Pull request by scopatz**
This PR makes all of the modules in the completers subpackage lazy.  Also, this exposed a bug in amalgamate that I also fixed up.

### CODE REVIEW

**Comment by gforsyth** [comment]
test failure here from a missing `xp.` https://github.com/xonsh/xonsh/pull/1503/files#diff-5a1eac0f7cdb0742679c12037c70fa53R154

**Comment by gforsyth** [comment]
Looks good otherwise, @scopatz.  Style question:  Do we want to standardize how we lazify compiled regexes?

**Comment by scopatz** [comment]
> Looks good otherwise, @scopatz. Style question: Do we want to standardize how we lazify compiled regexes?

I was just doing whatever fits nicely within 80 cols ;)  Maybe we need something more...

**Comment by scopatz** [comment]
Ok! PR is all fixed up

**Comment by gforsyth** [comment]
Looks good!

**Pull request merged**
