### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by gforsyth**
Wild.  They have built-in support for conda environments.  No idea if any of this will work and very much a work in progress, but let's see how this goes...

### CODE REVIEW

**Comment by gforsyth** [comment]
lol, not well

**Comment by scopatz** [comment]
Amazing! Thanks for pushing on this @gforsyth!

**Comment by scopatz** [comment]
@mariusvniekerk has pointed me to this, which he says is less broke than the built-in condas: https://github.com/mariusvniekerk/psutil-feedstock/blob/master/azure-pipelines.yaml

**Comment by scopatz** [comment]
We don't have C extensions and probably don't need to build mac on this yet, but this may be a useful point of reference.

**Comment by gforsyth** [comment]
Wow.  That was... actually pretty easy.  Cool!  

I have a few changes to make, but question: should we have this run in tandem with Appveyor for a bit and then disable Appveyor later?  Or disable it now?

**Comment by gforsyth** [comment]
Also pinging @melund to see if he has any thoughts on windows testing stuff I may have overlooked

**Comment by scopatz** [comment]
I think we can run at least the msys stuff on appveyor for the moment, since this doesn't test that on azure yet (which is fine).  Also, yeah, we should definitely defer to @melund to merge this :)

**Comment by scopatz** [comment]
@gforsyth - woohoo! It works!

**Comment by melund** [comment]
Looks good. We could think about exporting the test results directly to Azure, but I will make a separate PR for that.

**Pull request merged**
