### PR TITLE
Backline

### PR DESCRIPTION
**Pull request by scopatz**
This fixes an issue in the lexer and in wrap subproc that was preventing the correct usage of line continuations in subporc mode. It should address #2254

### CODE REVIEW

**Comment by scopatz** [comment]
Anyone able to review this, please?

**Comment by gforsyth** [comment]
Hey @scopatz -- thanks for putting this in! 

So, this works:
```
gil@theo ~ 🐚  echo --test 1 \
.............. --test2
.............. 
--test 1 --test2
```

but not this (note no space between `test` and `1`)
```
gil@theo ~ 🐚  echo --test1 \
.............. --test2
.............. 
xonsh: subprocess mode: command not found: --test2
```

**Comment by melund** [comment]
Also. Does this still handle the fact that there should always be a white space before the backslash on windows?

**Comment by melund** [comment]
I see the same problem @gforsyth reports.

**Comment by scopatz** [comment]
> Also. Does this still handle the fact that there should always be a white space before the backslash on windows?

Yes, that should not be any different

**Comment by scopatz** [comment]
Thanks @gforsyth for finding that! I am actually surprised that I was able to fix that. That expression is fully ambiquous with Python and the error was happening by wrapping the second line on its own.  Luckily the node the AST Transformer got represented both lines...

**Comment by scopatz** [comment]
This should be ready for another look.

**Comment by scopatz** [comment]
Ok! This is back to passing.

**Comment by gforsyth** [comment]
Nice!

```console
gil@bad_cat ~ $ echo --test1        \
...............      --test2   \
...............      --test3      \
...............      --test4
...............      
--test1 --test2 --test3 --test4
```

I noticed that multiline mode isn't triggered if there's a trailing space _after_ the `\`, but I think that's fine and also I imagine that if it _did_ trigger a newline it would cause problems on Windows.

Looks good to me!

**Comment by scopatz** [comment]
> I noticed that multiline mode isn't triggered if there's a trailing space after the \

Yeah that is the rule for trailing backslashes in most languages :) Thanks for the merge!

**Pull request merged**
